/** Registro único das páginas demonstrativas dentro de /portfolio/.
 * Novos protótipos entram aqui uma única vez; rota, SEO e sitemap consomem
 * a mesma fonte para evitar correções duplicadas.
 */
export type PortfolioPrototype = {
  slug: string;
  vertical: string;
  siteName: string;
  kind: "prototype";
  indexable: boolean;
};

export const PORTFOLIO_PROTOTYPES: readonly PortfolioPrototype[] = [
  {
    slug: "sos-presentes-cosmeticos",
    vertical: "comercios",
    siteName: "SOS Presentes & Cosméticos · São José dos Pinhais",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "marido-de-aluguel",
    vertical: "prestadores-de-servicos",
    siteName: "Marido de Aluguel · Serviços Residenciais",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "clinica-integrada",
    vertical: "clinicas",
    siteName: "Clínica Integrada de Saúde",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "almeida-torres",
    vertical: "advocacia",
    siteName: "Almeida Torres Advocacia",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "casa-nativa",
    vertical: "restaurantes",
    siteName: "Casa Nativa Bistrô",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "emporio-lelecute",
    vertical: "comercios",
    siteName: "Empório LeleCute · Lembrancinhas Artesanais",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "paraiso-do-hot-dog",
    vertical: "restaurantes",
    siteName: "Paraíso do Hot Dog · Cardápio Online",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "rm-fretes",
    vertical: "prestadores-de-servicos",
    siteName: "RM Fretes · Frete Rápido em Curitiba",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "rj-servicos-drywall",
    vertical: "prestadores-de-servicos",
    siteName: "RJ Serviços de Drywall · Curitiba",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "confeitaria-chyrley",
    vertical: "restaurantes",
    siteName: "Chyrley Doces & Festas · Rio Bonito",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "mp-festas-eventos",
    vertical: "comercios",
    siteName: "MP Festas e Eventos · Araucária",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "studio-de-cilios",
    vertical: "beleza",
    siteName: "Studio de Cílios · Extensão personalizada",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "refrigeracao-maresia",
    vertical: "prestadores-de-servicos",
    siteName: "Refrigeração Maresia · Curitiba e Região",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "ag-electrical-services",
    vertical: "prestadores-de-servicos",
    siteName: "A&G Electrical Services · Elétrica e Redes",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "vila-da-capivara",
    vertical: "restaurantes",
    siteName: "Vila da Capivara · Kits Festa em Curitiba",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "lk-alvenaria",
    vertical: "prestadores-de-servicos",
    siteName: "LK Alvenaria · Construção e Acabamento",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "lucas-arruma-maquina-lavar",
    vertical: "prestadores-de-servicos",
    siteName: "Lucas Arruma Máquina de Lavar · Assistência",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "paulo-mestre-de-obras",
    vertical: "prestadores-de-servicos",
    siteName: "Paulo Mestre de Obras · Construção Civil",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "ecommerce-on",
    vertical: "comercios",
    siteName: "Ecommerce On · Agência Digital",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "no-brilho-higienizacao",
    vertical: "prestadores-de-servicos",
    siteName: "No Brilho Higienização · São José dos Pinhais",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "salao-da-marcia",
    vertical: "beleza",
    siteName: "Salão da Marcia · Cidade Jardim",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "espaco-cih-luh",
    vertical: "beleza",
    siteName: "Espaço CIH & LUH · O Casal das Unhas",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "diego-montador-moveis",
    vertical: "prestadores-de-servicos",
    siteName: "Diego Montador de Móveis · Sítio Cercado",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "aguia-sul-sinalizacao",
    vertical: "prestadores-de-servicos",
    siteName: "Águia Sul Sinalização · Pintura e Segurança",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "eletrovale-eletromecanica",
    vertical: "prestadores-de-servicos",
    siteName: "Eletrovale Eletromecânica · Curitiba",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "eletro-solucoes-eficazes",
    vertical: "prestadores-de-servicos",
    siteName: "Eletro Soluções Eficazes · Pinhais",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "eisenfer-tubos-acos",
    vertical: "prestadores-de-servicos",
    siteName: "Eisenfer Tubos e Aços · São José dos Pinhais",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "mary-diarista",
    vertical: "prestadores-de-servicos",
    siteName: "Mary Diarista · Curitiba",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "acai-total-araucaria",
    vertical: "restaurantes",
    siteName: "Açaí Total · Araucária",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "jkl-marcenaria",
    vertical: "prestadores-de-servicos",
    siteName: "JKL Marcenaria · Móveis sob medida",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "santos-montador-de-moveis",
    vertical: "prestadores-de-servicos",
    siteName: "Santos Montador de Móveis · Curitiba e Região",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "marmitaria-dom-diego",
    vertical: "restaurantes",
    siteName: "Marmitaria Dom Diego · Jardim Itália",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "beto-pasteis",
    vertical: "restaurantes",
    siteName: "Beto Pastéis · Jardim Itália",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "woodhouse-hamburgueres",
    vertical: "restaurantes",
    siteName: "Woodhouse Hambúrgueres · Jardim Itália",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "dlara-pizzaria",
    vertical: "restaurantes",
    siteName: "D’Lara Pizzaria, Esfiharia e Hamburgueria · Jardim Itália",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "toquinho-de-gente-brecho",
    vertical: "comercios",
    siteName: "Toquinho de Gente Brechó · Sítio Cercado",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "reuse-house-brecho",
    vertical: "comercios",
    siteName: "REuse House Brechó · Jardim das Américas",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "brecho-sao-francisco",
    vertical: "comercios",
    siteName: "Brechó São Francisco · Curitiba",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "angel-mix-brecho",
    vertical: "comercios",
    siteName: "Angel Mix Brechó · Novo Mundo",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "guaratuba-sabores-da-baia",
    vertical: "restaurantes",
    siteName: "Sabores da Baía · Guaratuba",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "guaratuba-oficina-nautica",
    vertical: "prestadores-de-servicos",
    siteName: "Oficina Náutica Guaratuba · Piçarras",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "guaratuba-atelie-presentes",
    vertical: "comercios",
    siteName: "Ateliê Encanto da Baía · Guaratuba",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "guaratuba-reparos-residenciais",
    vertical: "prestadores-de-servicos",
    siteName: "Reparos do Litoral · Guaratuba",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "mirassol-delicias-caseiras",
    vertical: "restaurantes",
    siteName: "Delícias Caseiras Mirassol · Centro",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "mirassol-conserta-celular",
    vertical: "prestadores-de-servicos",
    siteName: "Conserta Mirassol · São Bernardo",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "bh-barreiro-marmitas",
    vertical: "restaurantes",
    siteName: "Marmitas do Barreiro · Belo Horizonte",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "uberlandia-eletrica-residencial",
    vertical: "prestadores-de-servicos",
    siteName: "Elétrica Bairro Brasil · Uberlândia",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "lolipa-arte-em-festas",
    vertical: "comercios",
    siteName: "Lolipa Arte em Festas Decor · Curitiba",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "confeitaria-sabor-da-realeza",
    vertical: "restaurantes",
    siteName: "Confeitaria Sabor da Realeza · Uberaba",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "premium-envelopamentos",
    vertical: "prestadores-de-servicos",
    siteName: "Premium Envelopamentos · Curitiba",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "miro-tech",
    vertical: "prestadores-de-servicos",
    siteName: "MIRO TECH · São José dos Pinhais",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "galileu-locacao-brinquedos",
    vertical: "comercios",
    siteName: "Galileu Locação de Brinquedos · São José dos Pinhais",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "lj-cleaning",
    vertical: "prestadores-de-servicos",
    siteName: "L&J Cleaning · São José dos Pinhais",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "manu-pasteis",
    vertical: "restaurantes",
    siteName: "Manu Pastéis",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "liz-moraes-nail-designer",
    vertical: "beleza",
    siteName: "Liz Moraes Nail Designer · São José dos Pinhais",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "assistencia-microondas-santos",
    vertical: "prestadores-de-servicos",
    siteName: "Assistência Técnica Microondas Santos",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "artesanatos-darleia-oliveira",
    vertical: "comercios",
    siteName: "Artesanatos Darléia Oliveira",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "thays-camilla",
    vertical: "comercios",
    siteName: "Thays Camilla · Personalizados",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "fernanda-amaral-drywall",
    vertical: "prestadores-de-servicos",
    siteName: "Fernanda & Amaral · Instalação de Drywall",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "denise-gomes-psicologa",
    vertical: "clinicas",
    siteName: "Denise Gomes · Psicóloga",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "ton-e-cor",
    vertical: "prestadores-de-servicos",
    siteName: "Ton & Cor · Pintura e Pequenas Reformas",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "raphael-construcoes",
    vertical: "prestadores-de-servicos",
    siteName: "Raphael Construções",
    kind: "prototype",
    indexable: true,
  },
  {
    slug: "jc-revestimentos",
    vertical: "prestadores-de-servicos",
    siteName: "JC Revestimentos",
    kind: "prototype",
    indexable: true,
  },
];

export function findPortfolioPrototype(slug: string) {
  return PORTFOLIO_PROTOTYPES.find((site) => site.slug === slug);
}
