import { motion } from "motion/react";
import { ArrowRight, Check, CircuitBoard, HardHat, Network, ShieldCheck, Wrench, Zap } from "lucide-react";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";

const quiz = { services: ["Elétrica geral", "Infraestrutura para redes", "Cabeamento estruturado UTP", "Sistema CFTV", "Implantação de redes", "Montagem e organização de rack"], experienceOptions: ["Residencial", "Comercial", "Predial / condomínio", "Industrial"], periodOptions: ["Curitiba", "Região Metropolitana", "Vou confirmar o endereço"], timingOptions: ["Preciso avaliar com urgência", "Nos próximos dias", "Estou planejando"], proposalKind: "service" as const, stepTitles: { service: "Qual solução você precisa?", experience: "Em qual tipo de ambiente?", period: "Onde será o serviço?", timing: "Quando você precisa?", note: "Conte detalhes do projeto" }, notePlaceholder: "Ex.: quantidade de pontos, tamanho do rack, câmeras ou tipo de instalação." };
function CTA({ children }: { children: React.ReactNode }) { return <PortfolioCTAQuiz clientKey="ag-electrical-services" studioName="A&G Electrical Services" recipientName="A&G Electrical Services" theme="navy" mode="proposal" quizConfig={quiz} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#092c52] px-6 py-3.5 font-bold text-white shadow-lg shadow-[#092c52]/20 transition hover:-translate-y-1 hover:bg-[#133f6d] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f47b20]">{children}</PortfolioCTAQuiz>; }
const services = [["Elétrica geral", "Instalações residenciais, prediais e comerciais com planejamento e segurança."], ["Infraestrutura e redes", "Eletrocalhas, canaletas e cabeamento estruturado para dados e voz."], ["CFTV", "Dimensionamento, instalação e organização de sistemas de segurança."], ["Racks e implantação", "Montagem, identificação e fechamento organizado para facilitar a operação."]];
export function AgElectricalServicesPage() { return <div className="min-h-dvh bg-[#f8fafc] text-[#0b294d]">
 <header className="sticky top-0 z-20 border-b border-[#dbe6ef] bg-[#f8fafc]/90 px-5 py-4 backdrop-blur lg:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><a href="#inicio" className="flex items-center gap-3 font-display text-lg font-bold"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#092c52] text-[#f47b20]"><Zap className="h-5 w-5" /></span><span>A&G <span className="text-[#f47b20]">Electrical</span></span></a><nav className="hidden gap-6 text-sm font-semibold md:flex"><a href="#servicos">Serviços</a><a href="#laserway">Laserway</a><a href="#diferenciais">Diferenciais</a></nav><CTA>Solicitar orçamento <ArrowRight className="h-4 w-4" /></CTA></div></header>
 <main><section id="inicio" className="relative overflow-hidden px-5 py-14 lg:px-8 lg:py-24"><div className="pointer-events-none absolute -right-28 -top-24 h-80 w-80 rounded-full bg-[#f47b20]/15 blur-3xl" /><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f47b20]">Elétrica · infraestrutura · redes · CFTV</p><h1 className="mt-5 font-display text-5xl font-bold leading-[.98] sm:text-7xl">Energia e conectividade para sua operação.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#4e6680]">A&G Electrical Services entrega soluções integradas em elétrica e infraestrutura para residências, comércios, condomínios e empresas em Curitiba e Região Metropolitana.</p><div className="mt-8 flex flex-wrap gap-3"><CTA>Agendar avaliação <ArrowRight className="h-4 w-4" /></CTA><a href="#servicos" className="inline-flex min-h-12 items-center rounded-full border border-[#9fb6c7] px-6 py-3.5 font-semibold text-[#092c52]">Conhecer soluções</a></div><div className="mt-8 flex flex-wrap gap-4 text-sm font-semibold text-[#4e6680]"><span><Check className="mr-1 inline h-4 w-4 text-[#f47b20]" />Conformidade técnica</span><span><ShieldCheck className="mr-1 inline h-4 w-4 text-[#f47b20]" />Segurança em primeiro lugar</span></div></div><motion.div initial={{ opacity: 0, y: 20, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: .65 }}><PortfolioImage src="/images/ag-electrical-services/intro.webp" alt="A&G Electrical Services: soluções integradas em elétrica e infraestrutura" priority width={950} height={790} className="w-full rounded-[2rem] object-cover shadow-2xl" /></motion.div></div></section>
 <section id="servicos" className="bg-[#092c52] px-5 py-20 text-white lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f47b20]">Portfólio de serviços</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-bold">Infraestrutura pronta para funcionar — e continuar funcionando.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map(([title, text], i) => <motion.article key={title} whileHover={{ y: -6 }} transition={{ duration: .2 }} className="rounded-3xl border border-white/15 bg-white/10 p-6"><span className="text-sm font-bold text-[#f47b20]">0{i + 1}</span><Wrench className="mt-8 h-7 w-7 text-[#f47b20]" /><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#dce8f1]">{text}</p></motion.article>)}</div></div></section>
 <section id="laserway" className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f47b20]">Mão de obra Laserway</p><h2 className="mt-3 font-display text-4xl font-bold">Organização que você consegue enxergar.</h2><p className="mt-4 max-w-2xl text-lg leading-8 text-[#4e6680]">Confira alguns registros de montagem, identificação e fechamento de racks realizados pela equipe.</p></div><span className="rounded-full bg-[#fff0e4] px-4 py-2 text-sm font-bold text-[#c85e12]">Case real</span></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[["laserway-1.webp", "Distribuição e identificação"], ["laserway-2.webp", "Infraestrutura organizada"], ["rack-1.webp", "Fechamento de rack"], ["rack-2.webp", "Acabamento e padrão"]].map(([src, alt]) => <motion.figure key={src} whileHover={{ y: -5 }} className="overflow-hidden rounded-3xl border border-[#dbe6ef] bg-white shadow-sm"><PortfolioImage src={`/images/ag-electrical-services/${src}`} alt={alt} width={720} height={960} className="h-72 w-full object-cover" /><figcaption className="p-4 text-sm font-semibold">{alt}</figcaption></motion.figure>)}</div></div></section>
 <section id="diferenciais" className="bg-[#eef4f8] px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f47b20]">Diferenciais corporativos</p><h2 className="mt-3 font-display text-4xl font-bold">Clareza no orçamento. Rigor na execução.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-3xl bg-white p-6"><CircuitBoard className="h-7 w-7 text-[#f47b20]" /><h3 className="mt-6 text-xl font-bold">Conformidade técnica</h3><p className="mt-2 text-sm leading-6 text-[#4e6680]">Planejamento e execução alinhados às normas e padrões de segurança.</p></div><div className="rounded-3xl bg-white p-6"><HardHat className="h-7 w-7 text-[#f47b20]" /><h3 className="mt-6 text-xl font-bold">Eficiência em campo</h3><p className="mt-2 text-sm leading-6 text-[#4e6680]">Equipe preparada, organizada e comprometida com prazos.</p></div></div></div><div className="rounded-[2rem] bg-[#f47b20] p-8 text-white"><Network className="h-9 w-9" /><h3 className="mt-8 text-3xl font-bold">Vamos avaliar seu projeto?</h3><p className="mt-4 leading-7 text-white/90">Descreva a instalação, rede ou sistema de câmeras. A A&G organiza a melhor abordagem para o seu cenário.</p><div className="mt-7"><CTA>Solicitar avaliação <ArrowRight className="h-4 w-4" /></CTA></div></div></div></section></main>
 <footer className="bg-[#061d38] px-5 py-8 text-sm text-[#c9d8e8] lg:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-white">A&G <span className="text-[#f47b20]">Electrical Services</span></p><p className="mt-1">Elétrica, infraestrutura e redes em Curitiba e região.</p></div><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4 hover:text-[#f47b20]" /></div></footer>
 <PortfolioSocialProofPopup clientKey="ag-electrical-services" eyebrow="A&G Electrical Services" title="Sua infraestrutura merece organização e segurança." description="Conte o que precisa instalar, modernizar ou organizar e receba um próximo passo claro." ctaLabel="Conhecer serviços" ctaHref="#servicos" delayMs={9000} className="border-[#f47b20]/35 bg-[#092c52]/95 text-white" accentClassName="text-[#f47b20]" /><PortfolioUpsellPopup pageName="portfolio-ag-electrical-services" />
 </div>; }
