import { ArrowRight, BadgeCheck, Bolt, Droplets, Hammer, House, Lightbulb, PaintRoller, ShieldCheck, Wrench } from "lucide-react";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";
import { MotionImageReveal, MotionReveal, MotionScope, MotionStagger } from "@/components/motion";

const quiz = {
  services: ["Pintura", "Elétrica", "Hidráulica", "Pisos e revestimentos", "Drywall e forro", "Acabamentos", "Iluminação em LED"],
  experienceOptions: ["Reforma interna", "Ambiente comercial", "Construção nova", "Manutenção ou reparo"],
  periodOptions: ["Curitiba", "Região Metropolitana", "Vou confirmar o endereço"],
  timingOptions: ["Preciso começar em breve", "Nos próximos meses", "Ainda estou planejando"],
  proposalKind: "service" as const,
  stepTitles: { service: "Qual frente da obra você precisa?", experience: "Que tipo de reforma é?", period: "Onde será o serviço?", timing: "Quando pretende começar?" },
  notePlaceholder: "Conte os ambientes, metragem aproximada e o que você quer transformar.",
};

function CTA({ children }: { children: React.ReactNode }) {
  return <PortfolioCTAQuiz clientKey="btb-construcao" studioName="BTB Construção" recipientName="a equipe da BTB" theme="gold" mode="proposal" quizConfig={quiz}>{children}<ArrowRight className="h-4 w-4" /></PortfolioCTAQuiz>;
}

const services = [
  [PaintRoller, "Pintura", "Cores, preparação e acabamento para renovar o ambiente."],
  [Bolt, "Elétrica", "Instalações seguras, pontos novos e adequações."],
  [Droplets, "Hidráulica", "Reparos e soluções para água, cozinha e banheiro."],
  [House, "Pisos e revestimentos", "Assentamento cuidadoso para mudar a sensação do espaço."],
  [Hammer, "Drywall e forro", "Divisórias, forros e soluções funcionais sob medida."],
  [Lightbulb, "Acabamentos e LED", "Os detalhes que fazem a reforma parecer pronta."],
] as const;

export function BtbConstrucaoPage() {
  return <MotionScope><div className="min-h-dvh overflow-hidden bg-[#f6f3ed] text-[#171717] selection:bg-[#ffdf35] selection:text-black">
    <header className="sticky top-0 z-30 border-b border-white/10 bg-[#111]/95 px-5 py-4 text-white backdrop-blur lg:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><a href="#inicio" className="flex items-center gap-3 font-display text-xl font-black"><span className="grid h-10 w-10 place-items-center bg-[#ffdb19] text-[#111] [clip-path:polygon(0_18%,50%_0,100%_18%,100%_82%,50%_100%,0_82%)]">BTB</span><span>BTB <span className="text-[#ffdb19]">Construção</span></span></a><nav className="hidden gap-7 text-sm font-bold md:flex"><a href="#servicos" className="transition hover:text-[#ffdb19]">Serviços</a><a href="#processo" className="transition hover:text-[#ffdb19]">Como trabalhamos</a><a href="#contato" className="transition hover:text-[#ffdb19]">Orçamento</a></nav><CTA>Planejar reforma</CTA></div></header>
    <main>
      <section id="inicio" className="relative isolate overflow-hidden bg-[#111] px-5 py-14 text-white lg:px-8 lg:py-24"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_78%_50%,rgba(255,219,25,.25),transparent_33%),linear-gradient(110deg,#111_35%,#25221c)]" /><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-sm font-black uppercase tracking-[.24em] text-[#ffdb19]">Reformas internas · Curitiba e região</p><MotionReveal variant="up"><h1 className="mt-5 max-w-2xl font-display text-5xl font-black uppercase leading-[.9] sm:text-7xl lg:text-8xl">Quebre o <span className="text-[#ffdb19]">“um dia”</span>. Transforme agora.</h1></MotionReveal><p className="mt-7 max-w-xl text-lg leading-8 text-white/72">A BTB Construção resolve a parte pesada da reforma para você aproveitar o resultado: pintura, elétrica, hidráulica, revestimentos, drywall e iluminação.</p><div className="mt-8 flex flex-wrap gap-3"><CTA>Solicitar orçamento</CTA><a href="#servicos" className="inline-flex min-h-12 items-center gap-2 border border-white/30 px-6 py-3.5 font-bold text-white transition hover:border-[#ffdb19] hover:text-[#ffdb19]">Ver serviços <ArrowRight className="h-4 w-4" /></a></div><div className="mt-8 flex flex-wrap gap-5 text-sm font-bold text-white/70"><span><ShieldCheck className="mr-1 inline h-4 w-4 text-[#ffdb19]" />Garantia de 90 dias</span><span><BadgeCheck className="mr-1 inline h-4 w-4 text-[#ffdb19]" />Profissionais qualificados</span></div></div><MotionImageReveal direction="left"><div className="relative"><div className="absolute -inset-3 -z-10 rotate-2 bg-[#ffdb19]" /><PortfolioImage managedField="heroImageUrl" src="/images/btb-construcao/hero.png" alt="Ambiente interno em reforma com parede exposta, ferramentas e iluminação de obra" priority width={1536} height={1024} className="aspect-[4/3] w-full object-cover shadow-2xl" /><div className="absolute -bottom-5 -left-5 bg-[#ee1977] px-5 py-4 font-display text-xl font-black uppercase text-white shadow-xl sm:text-2xl">A gente quebra<br />para transformar.</div></div></MotionImageReveal></div></section>
      <section id="servicos" className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-sm font-black uppercase tracking-[.24em] text-[#df136e]">Do bruto ao detalhe</p><h2 className="mt-3 max-w-3xl font-display text-4xl font-black uppercase leading-none sm:text-6xl">Uma equipe para a reforma andar.</h2></div><Wrench className="hidden h-16 w-16 text-[#df136e] md:block" /></div><MotionStagger className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map(([Icon, title, text]) => <article key={title} className="group border-2 border-[#171717] bg-white p-6 transition hover:-translate-y-1 hover:bg-[#ffdb19] hover:shadow-[8px_8px_0_#ee1977]"><Icon className="h-9 w-9 text-[#df136e] group-hover:text-[#171717]" /><h3 className="mt-6 font-display text-2xl font-black uppercase">{title}</h3><p className="mt-2 leading-7 text-[#444] group-hover:text-[#171717]">{text}</p></article>)}</MotionStagger></div></section>
      <section id="processo" className="bg-[#ffdb19] px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-black uppercase tracking-[.24em] text-[#df136e]">Sem susto no caminho</p><h2 className="mt-3 font-display text-5xl font-black uppercase leading-[.9] sm:text-7xl">A bagunça é temporária. O resultado fica.</h2><p className="mt-6 max-w-md text-lg leading-8">Você explica o que deseja, a BTB organiza as etapas e a obra avança com comunicação clara.</p><CTA>Conversar sobre minha obra</CTA></div><div className="grid gap-4 sm:grid-cols-2">{[["01", "Diagnóstico", "Entendemos o ambiente, o escopo e a prioridade."], ["02", "Orçamento", "Você recebe uma proposta alinhada ao que precisa."], ["03", "Execução", "Equipe qualificada cuidando de cada etapa."], ["04", "Entrega", "Acabamento conferido e garantia de 90 dias."]].map(([n, title, text]) => <div key={n} className="border-2 border-[#171717] bg-[#f6f3ed] p-6"><span className="font-display text-5xl font-black text-[#ee1977]">{n}</span><h3 className="mt-5 font-display text-2xl font-black uppercase">{title}</h3><p className="mt-2 leading-7 text-[#444]">{text}</p></div>)}</div></div></section>
      <section id="contato" className="bg-[#111] px-5 py-16 text-white lg:px-8"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 border-l-8 border-[#ffdb19] bg-[#1c1c1c] p-8 md:flex-row md:items-center md:p-12"><div><p className="text-sm font-black uppercase tracking-[.24em] text-[#ffdb19]">Curitiba e região</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-black uppercase leading-none sm:text-6xl">Sua reforma pode começar agora.</h2><p className="mt-4 max-w-xl leading-7 text-white/65">Pagamento à vista com desconto e parcelamento em até 12x, conforme condições do orçamento.</p></div><CTA>Montar meu orçamento</CTA></div></section>
    </main><footer className="bg-[#0a0a0a] px-5 py-8 text-sm text-white/60 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-display text-xl font-black text-white">BTB <span className="text-[#ffdb19]">Construção</span></p><p className="mt-1">Reformas internas, acabamentos e transformação de ambientes.</p></div><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4" /></div></footer><PortfolioSocialProofPopup clientKey="btb-construcao" eyebrow="BTB Construção" title="A próxima transformação começa na conversa." description="Conte o que você quer reformar e receba um próximo passo claro." ctaLabel="Planejar reforma" ctaHref="#contato" delayMs={10000} className="border-[#ffdb19]/40 bg-[#171717]/95 text-white" accentClassName="text-[#ffdb19]" /><PortfolioUpsellPopup pageName="portfolio-btb-construcao" /></div></MotionScope>;
}
