import { ArrowRight, Facebook, Instagram, MapPin, MessageCircle, Wrench } from "lucide-react";
import { MotionReveal } from "@/components/motion";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";

const links = { instagram: "https://www.instagram.com/centro.mega/", facebook: "https://www.facebook.com/CentroMega.com.br/", opening: "https://www.facebook.com/ShoppingCidadeCuritiba/posts/venha-conhecer-a-loja-centro-mega-que-inaugurou-hoje-aqui-no-cidade-a-loja-%C3%A9-esp/1850210055013641/", linktree: "https://linktr.ee/centro.mega", store: "https://www.vhsys.net/centromega/contato/" };
const socialPosts = [
  ["Reel", "https://www.instagram.com/centro.mega/reel/DV8haszkdOy/"],
  ["Reel", "https://www.instagram.com/centro.mega/reel/DHzjkeutEKu/"],
  ["Post", "https://www.instagram.com/centro.mega/p/DDPCypWxVZZ/"],
  ["Reel", "https://www.instagram.com/centro.mega/reel/DHmlQd6tCNi/"],
  ["Post", "https://www.instagram.com/centro.mega/p/DGjBSGIPSKO/"],
  ["Post", "https://www.instagram.com/centro.mega/p/DCt4G0HxLRu/"],
] as const;
function CTA({ children }: { children: React.ReactNode }) { return <PortfolioCTAQuiz clientKey="centro-mega" studioName="Centro Mega" recipientName="a equipe Centro Mega" theme="navy" mode="proposal" className="inline-flex min-h-12 items-center justify-center gap-3 rounded-full bg-[var(--mega-cyan)] px-6 py-3.5 text-sm font-black text-[var(--mega-ink)] transition hover:-translate-y-1 hover:bg-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white">{children}</PortfolioCTAQuiz>; }
export function CentroMegaPage() { return <div data-client-slug="centro-mega" className="min-h-dvh bg-[var(--mega-ink)] text-white" style={{ "--mega-ink": "#071a35", "--mega-blue": "#0b2f5b", "--mega-cyan": "#35d4ed", "--mega-gold": "#f4c64e" } as React.CSSProperties}>
  <header className="sticky top-0 z-30 border-b border-white/10 bg-[var(--mega-ink)]/90 px-5 py-4 backdrop-blur lg:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5"><a href="#inicio" aria-label="Centro Mega — início"><PortfolioImage src="/images/centro-mega/logo.png" alt="Logo Centro Mega" width={500} height={500} priority managedField="logoUrl" className="h-12 w-12 rounded-xl object-cover" /></a><nav aria-label="Navegação principal" className="hidden gap-7 text-xs font-black uppercase tracking-[.16em] text-white/70 md:flex"><a href="#servicos">Serviços</a><a href="#lojas">Lojas</a><a href="#contato">Contato</a></nav><CTA>Falar com a equipe <ArrowRight className="h-4 w-4" /></CTA></div></header>
  <main><section id="inicio" className="relative isolate overflow-hidden px-5 py-16 lg:px-10 lg:py-28"><div className="pointer-events-none absolute inset-0 -z-10 opacity-30" style={{ backgroundImage: "linear-gradient(rgba(53,212,237,.18) 1px,transparent 1px),linear-gradient(90deg,rgba(53,212,237,.18) 1px,transparent 1px)", backgroundSize: "48px 48px" }} /><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.82fr_1.18fr]"><div><p className="inline-flex items-center gap-2 text-[11px] font-black uppercase tracking-[.28em] text-[var(--mega-cyan)]"><Wrench className="h-4 w-4" />Assistência técnica & acessórios</p><MotionReveal as="h1" variant="mask" intensity="EXPRESSIVE" className="mt-6 max-w-3xl text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-7xl">Tecnologia que funciona. <span className="text-[var(--mega-cyan)]">Atendimento que resolve.</span></MotionReveal><p className="mt-7 max-w-xl text-lg leading-8 text-white/75">A Centro Mega reúne assistência técnica especializada, acessórios e soluções para seus dispositivos em Curitiba e Região Metropolitana.</p><div className="mt-9 flex flex-wrap gap-4"><CTA>Pedir atendimento <MessageCircle className="h-4 w-4" /></CTA><a href={links.store} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-white/20 px-6 py-3.5 text-sm font-black">Ver canais e lojas <ArrowRight className="h-4 w-4" /></a></div></div><MotionReveal variant="right"><PortfolioImage src="/images/centro-mega/hero.png" alt="Centro Mega, assistência técnica e acessórios para tecnologia" width={1600} height={900} priority managedField="heroImageUrl" className="aspect-video w-full rounded-[2rem] border border-white/15 object-cover shadow-2xl" /></MotionReveal></div></section>
  <section id="servicos" className="bg-white px-5 py-20 text-[var(--mega-ink)] lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.24em] text-sky-700">Um só ponto para cuidar da sua tecnologia</p><h2 className="mt-4 max-w-3xl text-4xl font-black sm:text-6xl">Assistência, acessórios e orientação sem complicação.</h2><div className="mt-12 grid gap-5 md:grid-cols-3"><article className="rounded-3xl bg-slate-100 p-7"><Wrench className="h-8 w-8 text-sky-700" /><h3 className="mt-6 text-2xl font-black">Assistência técnica</h3><p className="mt-3 leading-7 text-slate-600">Avaliação e suporte especializado para eletrônicos, com atendimento próximo e transparente.</p></article><article className="rounded-3xl bg-[var(--mega-ink)] p-7 text-white"><MessageCircle className="h-8 w-8 text-[var(--mega-cyan)]" /><h3 className="mt-6 text-2xl font-black">Acessórios</h3><p className="mt-3 leading-7 text-white/70">Encontre acessórios e soluções para manter seus equipamentos prontos para a rotina.</p></article><article className="rounded-3xl bg-[var(--mega-gold)] p-7"><MapPin className="h-8 w-8" /><h3 className="mt-6 text-2xl font-black">Lojas próximas</h3><p className="mt-3 leading-7 opacity-80">Consulte a unidade mais conveniente pelos canais oficiais.</p></article></div></div></section>
  <section id="lojas" className="bg-[var(--mega-blue)] px-5 py-20 lg:px-10"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.24em] text-[var(--mega-cyan)]">Onde encontrar</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">Escolha o canal mais perto de você.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-white/70">O Linktree oficial concentra SAC e canais das unidades Centro Mega.</p><a href={links.linktree} target="_blank" rel="noreferrer" className="mt-8 inline-flex min-h-12 items-center gap-3 rounded-full bg-[var(--mega-cyan)] px-6 py-3.5 font-black text-[var(--mega-ink)]">Abrir Linktree oficial <ArrowRight className="h-4 w-4" /></a></div><div className="rounded-[2rem] border border-white/15 bg-white/5 p-8"><p className="text-sm font-black uppercase tracking-[.18em] text-[var(--mega-gold)]">Canais oficiais</p><div className="mt-7 space-y-5 text-lg"><p>WhatsApp e telefone disponíveis no Linktree e no fluxo seguro de atendimento.</p><p className="flex gap-3"><MapPin className="mt-1 h-5 w-5 shrink-0 text-[var(--mega-cyan)]" />Rua XV de Novembro, 1821 — Galeria Di Bruno</p></div></div></div></section>
  <section id="contato" className="bg-[var(--mega-ink)] px-5 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><div className="rounded-[2rem] border border-white/10 bg-white/[.04] p-8 sm:p-12"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[.24em] text-[var(--mega-cyan)]">Presença oficial</p><h2 className="mt-4 text-4xl font-black sm:text-5xl">Conheça a Centro Mega nas redes.</h2></div><div className="flex flex-wrap gap-3"><a href={links.instagram} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-white/20 px-5 font-black"><Instagram className="h-5 w-5" />Instagram</a><a href={links.facebook} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-white/20 px-5 font-black"><Facebook className="h-5 w-5" />Facebook</a></div></div><p className="mt-8 max-w-3xl text-white/65">Acompanhe as publicações oficiais e veja novidades, produtos e serviços diretamente no Instagram.</p><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{socialPosts.map(([kind, href], index) => <a key={href} href={href} target="_blank" rel="noreferrer" className="group rounded-2xl border border-white/10 bg-white/5 p-5 transition hover:-translate-y-1 hover:border-[var(--mega-cyan)]"><span className="text-[10px] font-black uppercase tracking-[.2em] text-[var(--mega-cyan)]">{kind} · publicação {index + 1}</span><span className="mt-3 flex items-center justify-between font-black">Abrir no Instagram <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></a>)}</div><a href={links.opening} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 text-sm font-black text-[var(--mega-cyan)]">Ver publicação de inauguração no Facebook <ArrowRight className="h-4 w-4" /></a></div></div></section></main>
  <footer className="border-t border-white/10 bg-[var(--mega-ink)] px-5 py-8 lg:px-10"><div className="mx-auto flex max-w-7xl justify-between gap-4 text-sm text-white/60"><p>Centro Mega — assistência técnica & acessórios</p><a href={links.linktree} target="_blank" rel="noreferrer">Linktree oficial</a></div><PortfolioHostCredit /></footer><PortfolioSocialProofPopup clientKey="centro-mega" eyebrow="Centro Mega" title="Precisa resolver sua tecnologia?" description="Veja os canais oficiais e fale com a unidade mais conveniente." ctaLabel="Falar com a equipe" ctaHref="#inicio" delayMs={10000} className="border-[var(--mega-cyan)]/30 bg-[var(--mega-ink)] text-white" accentClassName="text-[var(--mega-cyan)]" /><PortfolioUpsellPopup pageName="portfolio-centro-mega" /></div>; }
