import { ManagedText } from "@/components/portfolio/ManagedText";
import { motion } from "motion/react";
import { ArrowRight, CakeSlice, Check, CreditCard, Gift, MapPin, Star } from "lucide-react";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";

const offers = [["Bolos personalizados", "Temas infantis, aniversários e celebrações com acabamento artesanal."], ["Kit festa", "Combinações para 6 a 100 pessoas, com bolo, doces e salgados na medida."], ["Salgados em bandeja", "Pequenas quantidades para reunir a família ou completar seu evento."], ["Copo da Felicidade", "A dose extra de doçura para presentear ou matar a vontade de doce."]];
const quiz = { services: ["Bolo personalizado", "Kit festa", "Salgados", "Copo da Felicidade", "Quero montar uma festa"], experienceOptions: ["Aniversário", "Festa em casa", "Presente", "Evento ou confraternização"], periodOptions: ["Retirar no Rio Bonito", "Enviar por Uber", "Ainda preciso combinar"], timingOptions: ["Para esta semana", "Para a próxima semana", "Estou planejando"], proposalKind: "service" as const, stepTitles: { service: "O que você quer encomendar?", experience: "Qual é a ocasião?", period: "Como prefere receber?", timing: "Para quando precisa?", note: "Conte os detalhes da sua festa" }, notePlaceholder: "Ex.: bolo para 20 pessoas, tema Jurassic Park, salgados assados e endereço para Uber." };

function CTA({ children }: { children: React.ReactNode }) { return <PortfolioCTAQuiz clientKey="confeitaria-chyrley" studioName="Chyrley Doces & Festas" recipientName="Chyrley" theme="pink" mode="proposal" quizConfig={quiz} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#e56b83] px-6 py-3.5 font-bold text-white hover:-translate-y-1">{children}</PortfolioCTAQuiz>; }

export function ConfeitariaChyrleyPage() {
 return <div className="min-h-dvh bg-[#fff8f5] text-[#3b1d1b]">
  <header className="sticky top-0 z-20 border-b border-[#f1d9d1] bg-[#fff8f5]/90 px-5 py-4 backdrop-blur lg:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><a href="#inicio" className="flex items-center gap-3 font-display text-lg font-bold"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#7d2f35] text-[#ffd3df]"><CakeSlice className="h-5 w-5" /></span>Chyrley Doces & Festas</a><nav className="hidden gap-6 text-sm font-semibold md:flex"><a href="#encomendas">Encomendas</a><a href="#galeria">Inspirações</a><a href="#como-funciona">Como funciona</a></nav><CTA>Pedir orçamento <ArrowRight className="h-4 w-4" /></CTA></div></header>
  <main>
   <section id="inicio" className="px-5 py-14 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[1fr_.95fr]"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#b95768]">Bolos · kits festa · salgados · doces</p><h1 className="mt-5 font-display text-5xl font-bold leading-[.98] sm:text-7xl">
            <ManagedText field="heroHeadline" fallback={"Sua comemora\u00e7\u00e3o merece ser inesquec\u00edvel."} />
          </h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#744e4b]">
            <ManagedText field="heroSubheadline" fallback={"A Chyrley cuida de cada detalhe com bolos molhadinhos, salgados caprichados e doces que fazem a festa acontecer."} />
          </p><div className="mt-8 flex flex-wrap gap-3"><CTA>Montar minha encomenda <ArrowRight className="h-4 w-4" /></CTA><a href="#encomendas" className="inline-flex min-h-12 items-center rounded-full border border-[#c98b93] px-6 py-3.5 font-semibold text-[#7d2f35]">Ver opções</a></div><div className="mt-8 flex flex-wrap gap-4 text-sm font-semibold text-[#744e4b]"><span><Check className="mr-1 inline h-4 w-4 text-[#e56b83]" />Aceita crédito e débito</span><span><MapPin className="mr-1 inline h-4 w-4 text-[#e56b83]" />Rio Bonito</span></div></div><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }}><PortfolioImage src="/images/confeitaria-chyrley/capa.webp" alt="Bolos e salgados artesanais da Chyrley Doces & Festas" priority width={1200} height={1600} className="w-full rounded-[2rem] object-cover shadow-2xl"
            managedField="heroImageUrl"
          /></motion.div></div></section>
   <section id="encomendas" className="bg-[#7d2f35] px-5 py-20 text-white lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#ffd3df]">Feito para a sua ocasião</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-bold">Escolha a ideia. A gente transforma em festa.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{offers.map(([title, text], i) => <article key={title} className="rounded-3xl border border-white/15 bg-white/10 p-5 transition hover:-translate-y-1"><span className="text-3xl font-black text-[#ffd3df]">0{i + 1}</span><h3 className="mt-8 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#ffe8ed]">{text}</p></article>)}</div></div></section>
   <section id="galeria" className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#b95768]">Inspirações reais</p><h2 className="mt-3 font-display text-4xl font-bold">Um pedacinho das festas que já adoçamos.</h2><div className="mt-10 grid gap-5 md:grid-cols-2"><motion.figure whileHover={{ y: -5 }} className="overflow-hidden rounded-3xl border border-[#f1d9d1] bg-white shadow-sm"><img src="/images/confeitaria-chyrley/bolos.webp" alt="Bolos personalizados para festas" className="h-full max-h-[620px] w-full object-cover" loading="lazy" decoding="async" width={899} height={1599} /><figcaption className="p-5 font-semibold">Temas personalizados para crianças e adultos.</figcaption></motion.figure><div className="grid gap-5 sm:grid-cols-2"><div className="rounded-3xl bg-[#ffd3df] p-6"><Gift className="h-8 w-8 text-[#7d2f35]" /><h3 className="mt-8 text-2xl font-bold">Festa na caixa</h3><p className="mt-3 leading-7 text-[#744e4b]">Kits de 6 até 100 pessoas para comemorar sem complicação.</p></div><div className="rounded-3xl bg-[#f5c2a8] p-6"><Star className="h-8 w-8 text-[#7d2f35]" /><h3 className="mt-8 text-2xl font-bold">Salgados na bandeja</h3><p className="mt-3 leading-7 text-[#744e4b]">Porções pequenas ou grandes, sempre fresquinhas.</p></div><div className="rounded-3xl bg-[#7d2f35] p-6 text-white sm:col-span-2"><CreditCard className="h-8 w-8 text-[#ffd3df]" /><h3 className="mt-8 text-2xl font-bold">Pagamento e entrega</h3><p className="mt-3 leading-7 text-[#ffe8ed]">Aceitamos crédito e débito. Retire no Rio Bonito ou combine envio por Uber.</p></div></div></div></div></section>
   <section id="como-funciona" className="bg-[#fff0ec] px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#b95768]">Como encomendar</p><h2 className="mt-3 font-display text-4xl font-bold">Do primeiro desejo ao último docinho.</h2><div className="mt-8 space-y-5">{[["01", "Conte sua ideia", "Escolha o que deseja, quantidade, tema e data."], ["02", "Receba a orientação", "A Chyrley organiza as opções e confirma o orçamento."], ["03", "Celebre sem preocupação", "Retire no Rio Bonito ou combine o envio por Uber."]].map(([n, t, d]) => <div key={n} className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#7d2f35] font-bold text-white">{n}</span><div><h3 className="font-bold">{t}</h3><p className="mt-1 text-sm leading-6 text-[#744e4b]">{d}</p></div></div>)}</div></div><div className="rounded-[2rem] bg-white p-7 shadow-sm"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#b95768]">Atendimento local</p><h3 className="mt-3 text-2xl font-bold">Vamos montar algo lindo?</h3><p className="mt-3 leading-7 text-[#744e4b]">Peça seu orçamento pelo funil e conte como imagina sua comemoração.</p><div className="mt-6"><CTA>Pedir meu orçamento <ArrowRight className="h-4 w-4" /></CTA></div></div></div></section>
  </main>
  <footer className="bg-[#3b1d1b] px-5 py-8 text-sm text-[#f4cfd2] lg:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p><strong className="text-white">Chyrley Doces & Festas</strong> · Bolos, doces e salgados em Rio Bonito</p><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4 hover:text-[#ffd3df]" /></div></footer>
  <PortfolioSocialProofPopup clientKey="confeitaria-chyrley" eyebrow="Encomendas artesanais" title="Sua festa pode ter o sabor e o cuidado que você imaginou." description="Conte a ocasião, a quantidade e o que deseja celebrar para receber uma orientação personalizada." ctaLabel="Montar minha encomenda" ctaHref="#encomendas" delayMs={9000} />
  <PortfolioUpsellPopup pageName="portfolio-confeitaria-chyrley" />
 </div>;
}
