import { ManagedText } from "@/components/portfolio/ManagedText";
import { ArrowRight, CakeSlice, Check, Gift, Sparkles } from "lucide-react";
import { FunnelCTAButton } from "@/components/funnel/FunnelCTAButton";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";
import { MotionImageReveal, MotionReveal, MotionScope } from "@/components/motion";

const products = [
  ["Bolos", "Bolos preparados sob encomenda para aniversários e momentos especiais."],
  ["Doces", "Doces feitos com carinho para compor sua mesa e presentear."],
  ["Salgados", "Salgados para compartilhar em festas, reuniões e eventos."],
];

export function ConfeitariaSaborDaRealezaPage() {
  return <div className="min-h-dvh bg-[#fff8f0] text-[#40251e]">
    <header className="sticky top-0 z-20 border-b border-[#efd9bd] bg-[#fff8f0]/90 px-5 py-4 backdrop-blur lg:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><a href="#inicio" aria-label="Confeitaria Sabor da Realeza" className="shrink-0"><PortfolioImage managedField="logoUrl" priority src="/images/confeitaria-sabor-da-realeza/logo.png" alt="Confeitaria Sabor da Realeza" width={920} height={256} decoding="async" className="h-10 w-auto" /></a><nav className="hidden gap-6 text-sm font-semibold md:flex"><a href="#sabores">Sabores</a><a href="#festas">Festas</a><a href="#pedido">Pedido</a></nav><FunnelCTAButton clientKey="confeitaria-sabor-da-realeza" companySlug="confeitaria-sabor-da-realeza" formSlug="funnel-confeitaria-sabor-da-realeza" location="realeza_header" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#9d2443] px-5 py-2.5 text-sm font-bold text-white">Fazer encomenda <ArrowRight className="h-4 w-4" /></FunnelCTAButton></div></header>
    <MotionScope intensity="BALANCED">
    <main>
      <section id="inicio" className="mx-auto grid max-w-6xl items-center gap-10 px-5 py-14 lg:grid-cols-[.95fr_1.05fr] lg:px-8 lg:py-24"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#b27b1e]">Bolos · doces · salgados · Uberaba</p><MotionReveal variant="up"><h1 className="mt-5 max-w-xl font-display text-5xl font-black leading-[.98] sm:text-7xl">
            <ManagedText field="heroHeadline" fallback={"O sabor que faz voc\u00ea se sentir da realeza."} />
          </h1></MotionReveal><MotionReveal variant="up" delay={140}><p className="mt-6 max-w-xl text-lg leading-8 text-[#76564a]">
            <ManagedText field="heroSubheadline" fallback={"Momentos especiais ganham outra dimens\u00e3o quando cada receita \u00e9 preparada com ingredientes selecionados, carinho e aten\u00e7\u00e3o aos detalhes."} />
          </p></MotionReveal><div className="mt-8 flex flex-wrap gap-3"><FunnelCTAButton clientKey="confeitaria-sabor-da-realeza" companySlug="confeitaria-sabor-da-realeza" formSlug="funnel-confeitaria-sabor-da-realeza" location="realeza_hero" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#9d2443] px-6 py-3 font-bold text-white">Planejar meu pedido <ArrowRight className="h-4 w-4" /></FunnelCTAButton><a href="#sabores" className="inline-flex min-h-12 items-center rounded-full border border-[#d8b78a] px-6 py-3 font-semibold text-[#7d5420]">Conhecer sabores</a></div></div><MotionImageReveal direction="left"><PortfolioImage src="/images/confeitaria-sabor-da-realeza/hero.png" alt="Bolo, doces e salgados da Confeitaria Sabor da Realeza" priority width={1024} height={1536} className="mx-auto max-h-[680px] w-full max-w-xl rounded-[2rem] object-cover shadow-2xl shadow-[#9d2443]/15"
            managedField="heroImageUrl"
          /></MotionImageReveal></section>
      <section id="sabores" className="bg-[#9d2443] px-5 py-20 text-white lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f6d9a3]">Feito para celebrar</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-black">Escolha a combinação que combina com seu momento.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{products.map(([title, text], i) => <MotionReveal as="article" key={title} variant="scale" delay={i * 120} className="rounded-[1.6rem] border border-white/15 bg-white/10 p-6 transition-transform duration-200 hover:-translate-y-1"><span className="text-sm font-bold text-[#f6d9a3]">0{i + 1}</span><h3 className="mt-8 font-display text-2xl font-black">{title}</h3><p className="mt-3 leading-7 text-white/80">{text}</p></MotionReveal>)}</div></div></section>
      <section id="festas" className="px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2 lg:items-center"><MotionReveal variant="left"><CakeSlice className="h-9 w-9 text-[#b27b1e]" /><p className="mt-6 text-sm font-bold uppercase tracking-[.2em] text-[#b27b1e]">Encomendas para festas e eventos</p><h2 className="mt-3 font-display text-4xl font-black">Uma mesa com sabor, qualidade e carinho.</h2><p className="mt-5 text-lg leading-8 text-[#76564a]">Conte a ocasião, a data e o que você imaginou. A confeitaria organiza a encomenda de acordo com a sua celebração.</p><ul className="mt-7 grid gap-3 text-sm font-semibold"><li><Check className="mr-2 inline h-4 w-4 text-[#9d2443]" />Atendimento para encomendas</li><li><Check className="mr-2 inline h-4 w-4 text-[#9d2443]" />Bolos, doces e salgados no mesmo pedido</li><li><Check className="mr-2 inline h-4 w-4 text-[#9d2443]" />Detalhes e disponibilidade confirmados no atendimento</li></ul></MotionReveal><MotionReveal variant="right" delay={140} className="rounded-[2rem] bg-[#f4dfc4] p-8"><Gift className="h-8 w-8 text-[#9d2443]" /><h3 className="mt-8 font-display text-3xl font-black">Seu evento começa no planejamento.</h3><p className="mt-4 leading-7 text-[#76564a]">Uma página própria para apresentar o trabalho da Sabor da Realeza e facilitar o próximo passo de cada cliente.</p><FunnelCTAButton clientKey="confeitaria-sabor-da-realeza" companySlug="confeitaria-sabor-da-realeza" formSlug="funnel-confeitaria-sabor-da-realeza" location="realeza_festas" className="mt-7 inline-flex min-h-11 items-center gap-2 rounded-full bg-[#9d2443] px-5 py-3 font-bold text-white">Solicitar orçamento <ArrowRight className="h-4 w-4" /></FunnelCTAButton></MotionReveal></div></section>
      <section id="pedido" className="px-5 pb-20 lg:px-8"><MotionReveal variant="scale" className="mx-auto max-w-5xl rounded-[2rem] bg-[#f4dfc4] px-7 py-12 text-center sm:px-12"><Sparkles className="mx-auto h-9 w-9 text-[#9d2443]" /><h2 className="mt-5 font-display text-4xl font-black">Vamos preparar algo especial?</h2><p className="mx-auto mt-4 max-w-2xl text-lg leading-8 text-[#76564a]">Fale sobre sua ocasião e receba orientação para montar sua encomenda.</p><FunnelCTAButton clientKey="confeitaria-sabor-da-realeza" companySlug="confeitaria-sabor-da-realeza" formSlug="funnel-confeitaria-sabor-da-realeza" location="realeza_footer" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-full bg-[#9d2443] px-7 py-3.5 font-bold text-white">Fazer meu pedido <ArrowRight className="h-4 w-4" /></FunnelCTAButton></MotionReveal></section>
    </main>
    </MotionScope><footer className="bg-[#40251e] px-5 py-8 text-sm text-[#f4dfc4] lg:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p><strong className="text-white">Confeitaria Sabor da Realeza</strong><br />Bolos, doces e salgados em Uberaba.</p><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4" /></div></footer><PortfolioSocialProofPopup clientKey="confeitaria-sabor-da-realeza" eyebrow="Sabor da Realeza" title="Seu momento especial merece esse sabor." description="Conheça bolos, doces e salgados para sua próxima comemoração." ctaLabel="Ver sabores" ctaHref="#sabores" delayMs={9000} className="border-[#9d2443]/35 bg-[#40251e]/95 text-white" accentClassName="text-[#f6d9a3]" /><PortfolioUpsellPopup pageName="portfolio-confeitaria-sabor-da-realeza" />
  </div>;
}
