import { ArrowRight, Check, Gift, MapPin, PackageSearch, PenTool, Puzzle, Sparkles, Watch } from "lucide-react";
import type { ReactNode } from "react";
import { MotionReveal, MotionScope, MotionStagger } from "@/components/motion";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";

const quizConfig = {
  services: ["Brinquedos e artigos recreativos","Papelaria","Armarinho","Doces, balas e bombons","Joalheria e relojoaria","Quero ajuda para encontrar um presente"],
  experienceOptions: ["Presente para criança","Presente para adulto","Material de papelaria","Item para uso do dia a dia","Ainda estou escolhendo"],
  periodOptions: ["Quero retirar na loja","Quero confirmar se tem disponível","Quero combinar antes de ir"],
  timingOptions: ["Hoje","Nesta semana","Estou pesquisando"],
  proposalKind: "service" as const,
  stepTitles: { service: "O que você está procurando?", experience: "Para quem ou para qual necessidade?", period: "Como prefere seguir?", timing: "Para quando você precisa?", note: "Quer dar mais algum detalhe?" },
  notePlaceholder: "Ex.: idade, ocasião, faixa de preço, tipo de brinquedo ou item de papelaria.",
};

function CTA({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <PortfolioCTAQuiz clientKey="cris-presentes-colonia-rio-grande" studioName="Cris Presentes · Colônia Rio Grande" recipientName="Cris Presentes" theme="gold" mode="proposal" funnelIntent="pedido" quizConfig={quizConfig} ariaLabel="Consultar produtos na Cris Presentes" className={`inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#bd3e72] px-6 py-3.5 font-bold text-white shadow-xl shadow-[#bd3e72]/20 transition hover:-translate-y-0.5 hover:bg-[#9d2f5d] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f2a4c4] focus-visible:ring-offset-2 ${className}`}>{children}</PortfolioCTAQuiz>;
}

const categories = [
  { title: "Brinquedos", text: "A atividade principal registrada da filial é comércio varejista de brinquedos e artigos recreativos.", icon: Puzzle },
  { title: "Papelaria", text: "O cadastro empresarial também contempla artigos de papelaria.", icon: PenTool },
  { title: "Armarinho", text: "Itens de armarinho aparecem entre as atividades comerciais registradas.", icon: PackageSearch },
  { title: "Doces e lembranças", text: "Doces, balas e bombons fazem parte das categorias secundárias cadastradas.", icon: Gift },
  { title: "Acessórios", text: "Joalheria e relojoaria constam entre as atividades secundárias da empresa.", icon: Watch },
];

export function CrisPresentesColoniaRioGrandePage() {
  return <MotionScope intensity="BALANCED"><div className="min-h-dvh overflow-hidden bg-[#fffaf8] text-[#351d2a]">
    <header className="sticky top-0 z-30 border-b border-[#bd3e72]/10 bg-[#fffaf8]/92 px-5 py-3 backdrop-blur lg:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4">
      <a href="#inicio" className="flex items-center gap-3" aria-label="Cris Presentes"><PortfolioImage src="/images/cris-presentes-colonia-rio-grande/logo.svg" alt="" width={54} height={54} className="h-11 w-11" /><span className="font-display text-lg font-black text-[#6f2447]">Cris <span className="text-[#bd3e72]">Presentes</span></span></a>
      <nav className="hidden gap-6 text-sm font-semibold text-[#725664] md:flex"><a href="#categorias">Categorias</a><a href="#loja">A loja</a><a href="#local">Localização</a></nav>
      <CTA>Encontrar um presente <ArrowRight className="h-4 w-4" /></CTA>
    </div></header>
    <main>
      <section id="inicio" className="relative px-5 py-12 lg:px-10 lg:py-20"><div className="pointer-events-none absolute -right-24 top-0 h-80 w-80 rounded-full bg-[#f4b8cf]/35 blur-3xl" /><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[.9fr_1.1fr]">
        <div className="relative z-10"><p className="text-xs font-black uppercase tracking-[.28em] text-[#bd3e72]">Colônia Rio Grande · São José dos Pinhais</p><MotionReveal as="h1" variant="up" className="mt-5 max-w-2xl font-display text-5xl font-black leading-[.94] text-[#59213c] sm:text-7xl">Um lugar para transformar <span className="text-[#bd3e72]">“não sei o que dar”</span> em uma boa escolha.</MotionReveal><p className="mt-6 max-w-xl text-lg leading-8 text-[#765966]">A Cris Presentes da Rua Pedro Trevisan reúne categorias para presentear, brincar, estudar e resolver pequenas compras do dia a dia. Conte o que procura e deixe o funil organizar seu pedido.</p><div className="mt-8 flex flex-wrap gap-3"><CTA>Quero ajuda para escolher <Gift className="h-4 w-4" /></CTA><a href="#categorias" className="inline-flex min-h-12 items-center rounded-full border border-[#e2bfd0] px-6 py-3.5 font-semibold text-[#8a3157]">Ver categorias</a></div><div className="mt-8 flex flex-wrap gap-4 text-sm font-semibold text-[#765966]"><span><Check className="mr-1 inline h-4 w-4 text-[#bd3e72]" />Filial ativa em São José dos Pinhais</span><span><MapPin className="mr-1 inline h-4 w-4 text-[#bd3e72]" />Rua Pedro Trevisan, 58 · lojas 06 e 07</span></div></div>
        <MotionReveal variant="scale" className="relative mx-auto w-full max-w-2xl"><div className="absolute -inset-3 rounded-[2.4rem] bg-gradient-to-br from-[#f6bfd5] via-[#ffe5b6] to-[#bd3e72] opacity-50 blur-xl" /><PortfolioImage src="/images/cris-presentes-colonia-rio-grande/hero.svg" alt="Arte editorial da Cris Presentes com referências a brinquedos, papelaria e presentes" width={1200} height={1400} priority className="relative max-h-[720px] w-full rounded-[2.2rem] object-cover shadow-2xl shadow-[#8a3157]/15" /></MotionReveal>
      </div></section>
      <section id="categorias" className="bg-[#59213c] px-5 py-20 text-white lg:px-10 lg:py-24"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.28em] text-[#ffd0e2]">O que procurar por aqui</p><h2 className="mt-3 max-w-3xl font-display text-4xl font-black sm:text-5xl">Categorias encontradas no cadastro comercial da filial.</h2><p className="mt-4 max-w-3xl leading-7 text-white/70">O estoque muda. Por isso a página não inventa marcas, preços ou disponibilidade: você informa o que deseja e a loja confirma.</p><MotionStagger variant="up" step={70} className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{categories.map(({ title, text, icon: Icon }) => <article key={title} className="rounded-[1.6rem] border border-white/10 bg-white/8 p-5"><Icon className="h-7 w-7 text-[#ffd0e2]" /><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/70">{text}</p></article>)}</MotionStagger></div></section>
      <section id="loja" className="px-5 py-20 lg:px-10"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><PortfolioImage src="/images/cris-presentes-colonia-rio-grande/capa-card.svg" alt="Composição editorial de presentes, brinquedos e papelaria da Cris Presentes" width={1200} height={900} className="w-full rounded-[2rem] shadow-xl shadow-[#8a3157]/10" /><div className="rounded-[2rem] border border-[#eed9e2] bg-white p-7 sm:p-9"><p className="text-xs font-black uppercase tracking-[.24em] text-[#bd3e72]">Filial 2 · comércio local</p><h2 className="mt-3 font-display text-4xl font-black text-[#59213c]">Uma unidade identificada no endereço do Jacomar Colônia Rio Grande.</h2><p className="mt-5 leading-8 text-[#765966]">O registro empresarial público identifica a unidade como Cris Presentes Filial 2, na Rua Pedro Trevisan, 58, lojas 06 e 07. O mesmo endereço corresponde ao Jacomar Colônia Rio Grande.</p><div className="mt-7"><CTA>Consultar um item <ArrowRight className="h-4 w-4" /></CTA></div></div></div></section>
      <section id="local" className="border-y border-[#eed9e2] bg-[#f9eef3] px-5 py-16 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 md:flex-row md:items-center"><div><p className="text-xs font-black uppercase tracking-[.24em] text-[#bd3e72]">Onde encontrar</p><h2 className="mt-3 font-display text-4xl font-black text-[#59213c]">Rua Pedro Trevisan, 58 · lojas 06 e 07</h2><p className="mt-3 text-[#765966]">Colônia Rio Grande · São José dos Pinhais — PR · CEP 83025-580.</p></div><CTA>Verificar disponibilidade <ArrowRight className="h-4 w-4" /></CTA></div></section>
      <section id="pedido" className="px-5 py-20 lg:px-10"><div className="mx-auto max-w-5xl rounded-[2.4rem] bg-gradient-to-br from-[#bd3e72] to-[#59213c] px-7 py-12 text-center text-white shadow-2xl shadow-[#59213c]/20 sm:px-12"><Sparkles className="mx-auto h-9 w-9 text-[#ffe0ec]" /><h2 className="mt-5 font-display text-4xl font-black sm:text-5xl">Diga o que você está procurando.</h2><p className="mx-auto mt-4 max-w-2xl text-lg leading-8 text-white/80">O funil registra a intenção, o tipo de item, a ocasião e o prazo, e encaminha tudo ao WhatsApp da própria unidade.</p><div className="mt-8"><CTA className="bg-white text-[#7b2c50] hover:bg-[#fff7fa]">Começar consulta <ArrowRight className="h-4 w-4" /></CTA></div></div></section>
    </main>
    <footer className="bg-[#3d1529] px-5 py-8 text-sm text-white/65 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p><strong className="text-white">Cris Presentes · Colônia Rio Grande</strong><br />Disponibilidade e condições confirmadas diretamente no atendimento.</p><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4" /></div></footer>
    <PortfolioSocialProofPopup clientKey="cris-presentes-colonia-rio-grande" eyebrow="Cris Presentes" title="Procurando um presente e ainda não decidiu?" description="Conte para quem é e o que você imaginou. O funil organiza a consulta para a loja." ctaLabel="Quero ajuda para escolher" ctaHref="#pedido" delayMs={9000} className="border-[#bd3e72]/35 bg-[#59213c]/95 text-white" accentClassName="text-[#ffd0e2]" />
  </div></MotionScope>;
}
