import { ArrowRight, Clock3, ExternalLink, Heart, MapPin, ShoppingBag, Sparkles, Truck, Utensils, Zap } from "lucide-react";
import { MotionReveal, MotionScope } from "@/components/motion";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";

const MENU_URL = "https://instadelivery.com.br/donalucysalgados";
const quiz = { services: ["Combo de salgados a partir de R$ 11,99", "Salgados fritos", "Churros de doce de leite", "Encomenda para evento", "Entrega agendada"], experienceOptions: ["Domingo em família", "Festa ou comemoração", "Reunião ou encontro", "Quero só experimentar"], periodOptions: ["Hoje", "Terça a domingo", "Quero agendar outro horário"], timingOptions: ["Quero pedir agora", "Quero consultar o cardápio", "Quero fazer uma encomenda"], proposalKind: "service" as const, stepTitles: { service: "O que vai deixar seu domingo melhor?", experience: "Qual é a ocasião?", period: "Quando você precisa?", timing: "Qual o próximo passo?", note: "Conte um pouco mais" }, notePlaceholder: "Ex.: quantidade, sabores, endereço ou horário desejado." };
function CTA({ children, location }: { children: React.ReactNode; location: string }) { return <PortfolioCTAQuiz clientKey="dona-lucy-salgados" studioName="Dona Lucy Salgados" recipientName="a equipe Dona Lucy" theme="pink" mode="proposal" quizConfig={quiz} ariaLabel="Fazer pedido ou orçamento pelo WhatsApp" className="inline-flex min-h-12 items-center justify-center gap-3 rounded-full bg-[var(--lucy-red)] px-6 py-3.5 font-black uppercase tracking-[.05em] text-white shadow-[0_12px_28px_rgba(159,54,46,.2)] transition hover:-translate-y-1 hover:bg-[var(--lucy-red-dark)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--lucy-gold)]" data-location={location}>{children}</PortfolioCTAQuiz>; }
const highlights = [[Utensils, "Fritos na hora", "Salgados dourados para chegar quentinhos."], [Heart, "Qualidade e carinho", "Ingredientes selecionados e atendimento próximo."], [Truck, "Delivery Araucária", "Entrega para Campina da Barra e região."] ] as const;
export function DonaLucySalgadosPage() { return <MotionScope intensity="BALANCED"><div style={{ "--lucy-red": "#a63b32", "--lucy-red-dark": "#7d2722", "--lucy-gold": "#e4a321", "--lucy-cream": "#fff8e9", "--lucy-ink": "#2e211d", "--lucy-muted": "#75635b" } as React.CSSProperties} className="min-h-dvh overflow-hidden bg-[var(--lucy-cream)] text-[var(--lucy-ink)]">
    <header className="sticky top-0 z-30 border-b border-[var(--lucy-gold)]/30 bg-[var(--lucy-cream)]/95 px-5 py-4 backdrop-blur lg:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5"><a href="#inicio" aria-label="Dona Lucy Salgados"><PortfolioImage src="/images/dona-lucy-salgados/logo.png" alt="Logo Dona Lucy Salgados Delivery" width={360} height={180} priority managedField="logoUrl" className="h-12 w-auto max-w-[13rem] object-contain" /></a><nav aria-label="Navegação principal" className="hidden gap-7 text-xs font-black uppercase tracking-[.12em] text-[var(--lucy-ink)]/70 md:flex"><a href="#sabores">Sabores</a><a href="#como-pedir">Como pedir</a><a href="#horarios">Horários</a></nav><a href={MENU_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[var(--lucy-red)] px-5 py-3 text-sm font-black text-white transition hover:bg-[var(--lucy-red-dark)]">Abrir cardápio <ExternalLink className="h-4 w-4" /></a></div></header>
    <main><section id="inicio" className="relative overflow-hidden bg-[var(--lucy-red)] px-5 py-14 text-white lg:px-10 lg:py-24"><div className="pointer-events-none absolute -right-32 -top-32 h-96 w-96 rounded-full border-[40px] border-[var(--lucy-gold)]/20" /><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="inline-flex items-center gap-2 text-[11px] font-black uppercase tracking-[.28em] text-[var(--lucy-gold)]"><Sparkles className="h-4 w-4" />Delivery feito na hora</p><MotionReveal as="h1" variant="mask" intensity="EXPRESSIVE" className="mt-6 max-w-2xl text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-7xl">Aquele lanchinho que transforma o <span className="text-[var(--lucy-gold)]">domingo em família.</span></MotionReveal><p className="mt-7 max-w-xl text-lg leading-8 text-white/80">Salgados fritos e churros de doce de leite, preparados na hora para chegar quentinhos, crocantes e cheios de carinho.</p><div className="mt-9 flex flex-wrap gap-4"><a href={MENU_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-3 rounded-full bg-[var(--lucy-gold)] px-6 py-3.5 font-black uppercase text-[var(--lucy-ink)]">Ver combos a partir de R$ 11,99 <ExternalLink className="h-4 w-4" /></a><CTA location="dona_lucy_hero">Fazer pedido <ArrowRight className="h-4 w-4" /></CTA></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-xs font-bold uppercase tracking-[.1em] text-white/65"><span><Zap className="mr-2 inline h-4 w-4 text-[var(--lucy-gold)]" />Fritamos na hora</span><span><Truck className="mr-2 inline h-4 w-4 text-[var(--lucy-gold)]" />Somente delivery</span></div></div><MotionReveal variant="right"><PortfolioImage src="/images/dona-lucy-salgados/hero.png" alt="Caixa de salgados dourados e churros de doce de leite em mesa familiar" width={1680} height={945} priority managedField="heroImageUrl" className="aspect-video w-full rounded-[1.75rem] object-cover shadow-2xl" /></MotionReveal></div></section>
    <section id="sabores" className="bg-[var(--lucy-cream)] px-5 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-[11px] font-black uppercase tracking-[.3em] text-[var(--lucy-red)]">O que chega na sua mesa</p><h2 className="mt-4 max-w-3xl text-4xl font-black leading-[.95] sm:text-6xl">Pequenos momentos, <span className="text-[var(--lucy-red)]">grande sabor.</span></h2><div className="mt-10 grid gap-5 md:grid-cols-3">{highlights.map(([Icon, title, text]) => <article key={title} className="rounded-[1.75rem] border border-[var(--lucy-red)]/10 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><Icon className="h-9 w-9 text-[var(--lucy-red)]" /><h3 className="mt-7 text-2xl font-black">{title}</h3><p className="mt-3 leading-7 text-[var(--lucy-muted)]">{text}</p></article>)}</div></div></section>
    <section id="como-pedir" className="bg-[var(--lucy-ink)] px-5 py-20 text-white lg:px-10"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-[11px] font-black uppercase tracking-[.3em] text-[var(--lucy-gold)]">Pedido sem complicação</p><h2 className="mt-5 text-4xl font-black leading-[.95] sm:text-6xl">Você escolhe. A Dona Lucy prepara.</h2><p className="mt-6 max-w-lg leading-8 text-white/65">Consulte o cardápio, escolha seus combos e peça pelo delivery. Para encomendas ou horários especiais, combine durante o expediente.</p><div className="mt-8 flex flex-wrap gap-4"><CTA location="dona_lucy_process">Montar meu pedido <ArrowRight className="h-4 w-4" /></CTA><a href={MENU_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-white/25 px-6 py-3.5 font-bold text-white">Abrir InstaDelivery <ExternalLink className="h-4 w-4" /></a></div></div><div className="grid gap-4 sm:grid-cols-3"><article className="rounded-3xl border border-white/10 bg-white/[.06] p-6"><span className="text-3xl font-black text-[var(--lucy-gold)]">01</span><h3 className="mt-10 font-black">Escolha</h3><p className="mt-2 text-sm leading-6 text-white/55">Veja os combos, salgados e churros no cardápio.</p></article><article className="rounded-3xl border border-white/10 bg-white/[.06] p-6"><span className="text-3xl font-black text-[var(--lucy-gold)]">02</span><h3 className="mt-10 font-black">Peça</h3><p className="mt-2 text-sm leading-6 text-white/55">Informe endereço, quantidade e melhor horário.</p></article><article className="rounded-3xl border border-white/10 bg-white/[.06] p-6"><span className="text-3xl font-black text-[var(--lucy-gold)]">03</span><h3 className="mt-10 font-black">Receba</h3><p className="mt-2 text-sm leading-6 text-white/55">Salgados fritos na hora chegando até você.</p></article></div></div></section>
    <section id="horarios" className="bg-[var(--lucy-gold)] px-5 py-16 lg:px-10"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-2"><div><Clock3 className="h-9 w-9 text-[var(--lucy-ink)]" /><h2 className="mt-5 text-4xl font-black">Terça a domingo, das 14h às 22h.</h2><p className="mt-4 max-w-xl leading-7 text-[var(--lucy-ink)]/75">Precisa de entrega fora desse horário? Agende durante o expediente e combine o dia e a hora.</p></div><div className="rounded-3xl bg-[var(--lucy-cream)] p-7"><MapPin className="h-7 w-7 text-[var(--lucy-red)]" /><p className="mt-4 font-black">Campina da Barra · Araucária</p><p className="mt-2 text-sm leading-6 text-[var(--lucy-muted)]">R. das Camélias, 1715 — Araucária, PR.</p><CTA location="dona_lucy_hours">Consultar disponibilidade <ArrowRight className="h-4 w-4" /></CTA></div></div></section></main>
    <footer className="bg-[var(--lucy-ink)] px-5 py-8 text-white lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xl font-black">Dona <span className="text-[var(--lucy-gold)]">Lucy</span> Salgados</p><p className="mt-1 text-xs text-white/55">Delivery de salgados fritos e churros.</p></div><div className="flex items-center gap-4 text-xs text-white/55"><a href={MENU_URL} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 hover:text-[var(--lucy-gold)]"><ShoppingBag className="h-4 w-4" />Cardápio online</a><PortfolioHostCredit linkClassName="font-semibold text-white underline" /></div></div></footer>
    <PortfolioSocialProofPopup clientKey="dona-lucy-salgados" eyebrow="Dona Lucy Salgados" title="Seu domingo merece um combo quentinho." description="Escolha os sabores e conte o melhor horário para receber." ctaLabel="Fazer pedido" ctaHref="#como-pedir" delayMs={10000} className="border-[var(--lucy-gold)]/40 bg-[var(--lucy-ink)] text-white" accentClassName="text-[var(--lucy-gold)]" /><PortfolioUpsellPopup pageName="portfolio-dona-lucy-salgados" />
  </div></MotionScope>; }
