import { ArrowRight, Armchair, Car, Check, Droplets, Home, ShieldCheck, Sparkles, SprayCan, Sofa, Wind } from "lucide-react";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";
import { MotionImageReveal, MotionReveal, MotionScope, MotionStagger } from "@/components/motion";

const quiz = {
  services: ["Sofá ou estofado", "Colchão", "Poltrona, cadeira ou puff", "Banco ou teto de carro", "Impermeabilização"],
  experienceOptions: ["Minha casa", "Empresa ou escritório", "Veículo", "Condomínio"],
  periodOptions: ["Curitiba", "Região Metropolitana", "Vou confirmar o endereço"],
  timingOptions: ["Preciso agendar em breve", "Nos próximos dias", "Ainda estou planejando"],
  proposalKind: "service" as const,
  stepTitles: { service: "O que precisa higienizar?", experience: "Onde será o atendimento?", period: "Qual região?", timing: "Quando pretende começar?" },
  notePlaceholder: "Conte a quantidade de peças, tecido e se deseja impermeabilização.",
};

function CTA({ children }: { children: React.ReactNode }) {
  return <PortfolioCTAQuiz clientKey="easy-clean" studioName="Easy Clean Higienização a Seco" recipientName="a equipe Easy Clean" theme="navy" mode="proposal" quizConfig={quiz}>{children}<ArrowRight className="h-4 w-4" /></PortfolioCTAQuiz>;
}

const services = [
  [Sofa, "Estofados", "Lavagem a seco para sofás, poltronas, cadeiras e puffs."],
  [Wind, "Colchões", "Higienização profunda para uma noite mais limpa e confortável."],
  [Car, "Interior do carro", "Bancos e teto de carro cuidados no conforto de onde você estiver."],
  [Droplets, "Impermeabilização", "Proteção para manter seu estofado limpo por mais tempo."],
] as const;

export function EasyCleanPage() {
  return <MotionScope><div className="min-h-dvh overflow-hidden bg-[#f4fbf7] text-[#102a3c]">
    <header className="sticky top-0 z-30 border-b border-[#b9e5d0] bg-[#f4fbf7]/95 px-5 py-4 backdrop-blur lg:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><a href="#inicio" className="flex items-center gap-3 font-display text-xl font-black"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#69c942] text-sm text-white shadow-[0_5px_0_#0f7f71]">EC</span><span>Easy <span className="text-[#13847a]">Clean</span></span></a><nav className="hidden gap-6 text-sm font-bold md:flex"><a href="#servicos" className="hover:text-[#13847a]">Serviços</a><a href="#cuidados" className="hover:text-[#13847a]">Cuidados</a><a href="#contato" className="hover:text-[#13847a]">Orçamento</a></nav><CTA>Solicitar orçamento</CTA></div></header>
    <main>
      <section id="inicio" className="relative overflow-hidden bg-[#102a3c] px-5 py-14 text-white lg:px-8 lg:py-24"><div className="absolute -right-40 -top-40 h-[32rem] w-[32rem] rounded-full bg-[#69c942]/20 blur-3xl" /><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[.88fr_1.12fr]"><div><p className="text-sm font-black uppercase tracking-[.24em] text-[#86e85d]">Higienização a seco · Curitiba e região</p><MotionReveal variant="up"><h1 className="mt-5 max-w-xl font-display text-5xl font-black leading-[.92] sm:text-7xl">Conforto limpo, <span className="text-[#86e85d]">sem sair de casa.</span></h1></MotionReveal><p className="mt-6 max-w-xl text-lg leading-8 text-white/75">A Easy Clean vai até você para higienizar estofados, colchões e interiores de carro com cuidado, praticidade e equipamentos profissionais.</p><div className="mt-8 flex flex-wrap gap-3"><CTA>Chamar a Easy Clean</CTA><a href="#servicos" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-white/25 px-6 py-3.5 font-bold transition hover:border-[#86e85d] hover:text-[#86e85d]">Conhecer serviços <ArrowRight className="h-4 w-4" /></a></div><div className="mt-8 flex flex-wrap gap-4 text-sm font-semibold text-white/70"><span><ShieldCheck className="mr-1 inline h-4 w-4 text-[#86e85d]" />Produtos seguros</span><span><Home className="mr-1 inline h-4 w-4 text-[#86e85d]" />Atendimento em domicílio</span></div></div><MotionImageReveal direction="left"><div className="relative"><div className="absolute -inset-3 rotate-2 rounded-[2rem] bg-[#69c942]" /><PortfolioImage managedField="heroImageUrl" src="/images/easy-clean/hero.png" alt="Sofá claro higienizado em ambiente residencial confortável" priority width={1536} height={1024} className="relative aspect-[4/3] w-full rounded-[1.5rem] object-cover shadow-2xl" /><div className="absolute -bottom-5 -left-4 rounded-2xl bg-[#f4fbf7] px-5 py-4 font-display text-xl font-black text-[#102a3c] shadow-xl sm:text-2xl">Limpeza profunda.<br /><span className="text-[#13847a]">Rotina mais leve.</span></div></div></MotionImageReveal></div></section>
      <section id="servicos" className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-black uppercase tracking-[.24em] text-[#13847a]">Cuidado que se sente</p><h2 className="mt-3 max-w-3xl font-display text-4xl font-black leading-none sm:text-6xl">Higienizar é devolver vida ao que você usa todos os dias.</h2><MotionStagger className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{services.map(([Icon, title, text]) => <article key={title} className="rounded-[1.75rem] border border-[#b9e5d0] bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><Icon className="h-9 w-9 text-[#13847a]" /><h3 className="mt-6 font-display text-2xl font-black">{title}</h3><p className="mt-3 leading-7 text-[#466272]">{text}</p></article>)}</MotionStagger></div></section>
      <section id="cuidados" className="bg-[#dff6e8] px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-sm font-black uppercase tracking-[.24em] text-[#13847a]">O que a limpeza remove</p><h2 className="mt-3 font-display text-4xl font-black leading-none sm:text-6xl">Mais cuidado para o seu ambiente.</h2><p className="mt-6 text-lg leading-8 text-[#315568]">A higienização e a impermeabilização ajudam a conservar tecidos e tornar a rotina mais agradável.</p><CTA>Organizar meu orçamento</CTA></div><div className="grid gap-3 sm:grid-cols-2">{["Ácaros", "Mofos", "Fungos", "Bactérias", "Odores", "Sujeira acumulada"].map((item) => <div key={item} className="flex items-center gap-3 rounded-2xl border border-[#a5dbbe] bg-white/75 p-5 font-bold"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#69c942] text-white"><Check className="h-5 w-5" /></span>{item}</div>)}</div></div></section>
      <section id="contato" className="bg-[#102a3c] px-5 py-16 text-white lg:px-8"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-8 rounded-[2rem] border border-[#69c942]/35 bg-[#173d4f] p-8 md:flex-row md:items-center md:p-12"><div><p className="text-sm font-black uppercase tracking-[.24em] text-[#86e85d]">Em casa ou na empresa</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-black leading-none sm:text-6xl">Seu estofado limpo e protegido por mais tempo.</h2><p className="mt-4 max-w-xl leading-7 text-white/70">Conte o que precisa higienizar e receba uma orientação para o melhor atendimento.</p></div><CTA>Solicitar orçamento</CTA></div></section>
    </main><footer className="bg-[#0b202d] px-5 py-8 text-sm text-white/60 lg:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-display text-xl font-black text-white">Easy <span className="text-[#86e85d]">Clean</span></p><p className="mt-1">Higienização a seco em Curitiba e região.</p></div><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4" /></div></footer><PortfolioSocialProofPopup clientKey="easy-clean" eyebrow="Easy Clean" title="Conforto limpo começa com uma boa higienização." description="Conte qual peça precisa de cuidado e organize seu orçamento." ctaLabel="Conhecer serviços" ctaHref="#servicos" delayMs={10000} className="border-[#69c942]/40 bg-[#102a3c]/95 text-white" accentClassName="text-[#86e85d]" /><PortfolioUpsellPopup pageName="portfolio-easy-clean" /></div></MotionScope>;
}
