import { ArrowRight, Box, Check, MapPin, Package, ShoppingBasket, Sparkles, type LucideIcon } from "lucide-react";
import { MotionReveal, MotionScope } from "@/components/motion";
import { ManagedText } from "@/components/portfolio/ManagedText";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";

const quiz = {
  services: ["Embalagens para alimentos", "Descartáveis e festas", "Produtos de limpeza", "Higiene e utilidades", "Sacos, caixas e papelaria"],
  experienceOptions: ["Minha casa", "Meu comércio", "Festa ou evento", "Compra para revenda"],
  periodOptions: ["Jardim Itália", "São José dos Pinhais", "Vou confirmar a retirada"],
  timingOptions: ["Quero consultar agora", "Para esta semana", "Estou planejando"],
  proposalKind: "service" as const,
  stepTitles: { service: "O que você procura?", experience: "Para qual uso?", period: "Onde será a retirada?", timing: "Quando precisa?", note: "Conte os itens que busca" },
  notePlaceholder: "Ex.: quantidade, tamanho da embalagem, tipo de produto ou data do evento.",
};

function CTA({ children }: { children: React.ReactNode }) {
  return <PortfolioCTAQuiz clientKey="embalar-embalagens" studioName="Embalar Embalagens" recipientName="a equipe Embalar" theme="pink" mode="proposal" quizConfig={quiz} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#dd5c4b] px-7 py-3.5 font-bold text-white shadow-lg shadow-[#dd5c4b]/20 transition hover:-translate-y-1 hover:bg-[#b94638] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#dd5c4b] focus-visible:ring-offset-2 focus-visible:ring-offset-[#fff8f1]">{children}</PortfolioCTAQuiz>;
}

const categories: Array<[string, string, string, LucideIcon]> = [
  ["01", "Embalagens", "Caixas, sacos, potes, bobinas e soluções para apresentar e proteger seus produtos.", Box],
  ["02", "Descartáveis", "Itens para festas, lanchonetes, delivery e o dia a dia do seu negócio.", Package],
  ["03", "Limpeza e utilidades", "Produtos para higiene, organização e manutenção de ambientes e operações.", ShoppingBasket],
];

const gallery = [
  ["/images/embalar-embalagens/loja-01.png", "Prateleiras com embalagens e descartáveis"],
  ["/images/embalar-embalagens/loja-02.png", "Variedade de itens para limpeza e utilidades"],
  ["/images/embalar-embalagens/loja-03.png", "Corredor de produtos de higiene e organização"],
  ["/images/embalar-embalagens/loja-04.png", "Seleção de produtos e embalagens"],
  ["/images/embalar-embalagens/loja-05.png", "Estoque de papéis, sacos e materiais"],
];

export function EmbalarEmbalagensPage() {
  return <MotionScope intensity="BALANCED"><div className="min-h-dvh overflow-hidden bg-[#fff8f1] text-[#26363b]">
    <header className="sticky top-0 z-30 border-b border-[#ead9ce] bg-[#fff8f1]/95 px-5 py-4 backdrop-blur lg:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5"><a href="#inicio" aria-label="Embalar Embalagens" className="flex items-center gap-3"><PortfolioImage src="/images/embalar-embalagens/logo.png" alt="Símbolo editorial de embalagens e utilidades" width={160} height={160} priority managedField="logoUrl" className="h-11 w-11 rounded-xl object-cover" /><span className="font-display text-lg font-bold tracking-tight text-[#26363b]">Embalar <span className="font-normal text-[#dd5c4b]">Embalagens</span></span></a><nav className="hidden gap-7 text-sm font-semibold text-[#6d7778] md:flex" aria-label="Navegação principal"><a href="#categorias" className="transition hover:text-[#dd5c4b]">Categorias</a><a href="#loja" className="transition hover:text-[#dd5c4b]">A loja</a><a href="#contato" className="transition hover:text-[#dd5c4b]">Orçamento</a></nav><CTA>Consultar produtos <ArrowRight className="h-4 w-4" /></CTA></div></header>
    <main>
      <section id="inicio" className="relative overflow-hidden px-5 py-14 lg:px-10 lg:py-24"><div className="pointer-events-none absolute -right-40 -top-48 h-[35rem] w-[35rem] rounded-full bg-[#f3b6a4]/30 blur-3xl" /><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><div className="relative z-10"><p className="font-mono text-[11px] font-bold uppercase tracking-[.27em] text-[#dd5c4b]">Jardim Itália · São José dos Pinhais</p><MotionReveal as="h1" variant="mask" intensity="EXPRESSIVE" className="mt-6 max-w-2xl font-display text-5xl font-bold leading-[.96] tracking-[-.045em] text-[#26363b] sm:text-7xl"><ManagedText field="heroHeadline" fallback="Tudo para embalar, cuidar e fazer acontecer." /></MotionReveal><p className="mt-6 max-w-xl text-base leading-8 text-[#647070]"><ManagedText field="heroSubheadline" fallback="Embalagens, descartáveis, produtos de limpeza e utilidades para sua casa, festa ou negócio." /></p><div className="mt-8 flex flex-wrap gap-3"><CTA>Falar com a Embalar <ArrowRight className="h-4 w-4" /></CTA><a href="#categorias" className="inline-flex min-h-12 items-center rounded-full border border-[#d5afa3] px-6 py-3.5 font-bold text-[#4a5b5d] transition hover:border-[#dd5c4b] hover:text-[#dd5c4b]">Explorar categorias</a></div><div className="mt-9 grid grid-cols-2 gap-3 border-t border-[#ead9ce] pt-5 text-xs font-bold text-[#6d7778] sm:grid-cols-3"><span className="flex items-center gap-2"><Check className="h-4 w-4 text-[#dd5c4b]" /> Variedade</span><span className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-[#dd5c4b]" /> Praticidade</span><span className="flex items-center gap-2"><MapPin className="h-4 w-4 text-[#dd5c4b]" /> Retire no bairro</span></div></div><MotionReveal variant="right" className="relative"><PortfolioImage src="/images/embalar-embalagens/hero.png" alt="Composição editorial com sacolas, caixas, potes, rolos e produtos de limpeza" priority managedField="heroImageUrl" width={1680} height={945} className="aspect-video w-full rounded-[2rem] object-cover shadow-2xl ring-1 ring-[#d8b0a2]" /><p className="mt-3 text-right text-[10px] uppercase tracking-[.16em] text-[#9a7770]">Imagem editorial · composição de marca</p></MotionReveal></div></section>
      <section id="categorias" className="bg-[#26363b] px-5 py-20 text-[#fff8f1] lg:px-10 lg:py-24"><div className="mx-auto max-w-7xl"><div className="grid gap-6 lg:grid-cols-[1fr_.6fr] lg:items-end"><div><p className="font-mono text-[11px] font-bold uppercase tracking-[.27em] text-[#f3b6a4]">No balcão</p><h2 className="mt-4 max-w-3xl font-display text-4xl font-bold leading-tight sm:text-5xl">A solução certa está mais perto do que parece.</h2></div><p className="text-sm leading-7 text-[#c5d0ce]">Conte o que você precisa e a equipe ajuda a encontrar o formato, a quantidade e o tipo de produto para o seu uso.</p></div><div className="mt-12 grid gap-px overflow-hidden border border-[#526568] bg-[#526568] md:grid-cols-3">{categories.map(([code, title, text, Icon], i) => <MotionReveal as="article" variant="up" delay={i * 90} key={code} className="min-h-72 bg-[#304348] p-7 transition hover:bg-[#3d5357]"><p className="font-mono text-xs font-bold tracking-[.2em] text-[#f3b6a4]">{code}</p><Icon className="mt-10 h-7 w-7 text-[#f3b6a4]" aria-hidden /><h3 className="mt-5 font-display text-2xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#c5d0ce]">{text}</p></MotionReveal>)}</div><div className="mt-4 flex flex-col items-start justify-between gap-4 rounded-2xl bg-[#fff8f1] px-6 py-5 text-sm text-[#4a5b5d] sm:flex-row sm:items-center"><span>Quer confirmar disponibilidade?</span><CTA>Descrever minha necessidade <ArrowRight className="h-4 w-4" /></CTA></div></div></section>
      <section id="loja" className="bg-white px-5 py-20 lg:px-10 lg:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-[11px] font-bold uppercase tracking-[.27em] text-[#dd5c4b]">Por dentro da Embalar</p><h2 className="mt-4 max-w-3xl font-display text-4xl font-bold leading-tight text-[#26363b] sm:text-5xl">Uma loja para resolver a rotina real.</h2></div><p className="max-w-md text-sm leading-7 text-[#6d7778]">Fotos reais da loja mostram a variedade do atendimento e dos produtos disponíveis.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{gallery.map(([src, alt], i) => <MotionReveal as="figure" variant="up" delay={i * 60} key={src} className={`overflow-hidden rounded-[1.35rem] bg-[#f4ece5] ${i === 0 ? "lg:col-span-2 lg:row-span-2" : ""}`}><PortfolioImage src={src} alt={alt} width={960} height={720} className="h-full min-h-52 w-full object-cover transition duration-500 hover:scale-105" /></MotionReveal>)}</div></div></section>
      <section id="contato" className="bg-[#f3b6a4] px-5 py-16 lg:px-10 lg:py-20"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 rounded-[2rem] bg-[#26363b] p-8 text-white shadow-2xl sm:p-12 lg:flex-row lg:items-center"><div><p className="font-mono text-[11px] font-bold uppercase tracking-[.27em] text-[#f3b6a4]">Orçamento e disponibilidade</p><h2 className="mt-4 max-w-2xl font-display text-4xl font-bold leading-tight sm:text-5xl">Diga o que você precisa. A Embalar ajuda a montar a solução.</h2><p className="mt-4 max-w-xl leading-7 text-[#c5d0ce]">Rua Quirino Zagonel, 1330 · Itália · São José dos Pinhais/PR. Atendimento e dúvidas pelo WhatsApp.</p></div><CTA>Solicitar atendimento <ArrowRight className="h-4 w-4" /></CTA></div></section>
    </main>
    <footer className="border-t border-[#ead9ce] bg-[#fff8f1] px-5 py-8 text-sm text-[#6d7778] lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-display font-bold text-[#26363b]">Embalar <span className="text-[#dd5c4b]">Embalagens</span></p><p className="mt-1 text-xs">Embalagens, higiene, descartáveis e utilidades.</p></div><div className="text-left sm:text-right"><p className="text-xs">Rua Quirino Zagonel, 1330 · São José dos Pinhais/PR</p><PortfolioHostCredit linkClassName="mt-2 inline-block font-semibold text-[#26363b] underline underline-offset-4 hover:text-[#dd5c4b]" /></div></div></footer>
    <PortfolioSocialProofPopup clientKey="embalar-embalagens" eyebrow="Embalar Embalagens" title="A rotina fica mais simples quando tudo está à mão." description="Consulte produtos e disponibilidade direto com a equipe." ctaLabel="Consultar produtos" ctaHref="#contato" delayMs={10000} className="border-[#dd5c4b]/40 bg-[#26363b]/95 text-white" accentClassName="text-[#f3b6a4]" /><PortfolioUpsellPopup pageName="portfolio-embalar-embalagens" />
  </div></MotionScope>;
}
