import { useState, type CSSProperties, type ReactNode } from "react";
import { ArrowRight, Check, DoorOpen, Hammer, MapPin, Ruler, ShieldCheck, Sparkles, Wrench } from "lucide-react";
import { MotionReveal, MotionScope } from "@/components/motion";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";

const quiz = {
  services: ["Colocação de portas de madeira", "Regulagem de portas", "Vistas e guarnições", "Caxilhos em geral", "Avaliar um projeto"],
  experienceOptions: ["Casa ou apartamento", "Reforma em andamento", "Obra nova", "Ainda estou planejando"],
  periodOptions: ["Curitiba", "São José dos Pinhais", "Região Metropolitana", "Vou confirmar o local"],
  timingOptions: ["Quero um orçamento", "Preciso resolver em breve", "Estou pesquisando opções"],
  proposalKind: "service" as const,
  stepTitles: { service: "O que precisa resolver?", experience: "Em qual contexto?", period: "Onde será?", timing: "Qual o próximo passo?", note: "Conte um pouco mais" },
  notePlaceholder: "Ex.: medida aproximada, modelo da porta, quantidade ou fase da obra.",
};

function CTA({ children, location }: { children: ReactNode; location: string }) {
  return <PortfolioCTAQuiz clientKey="enoel-portas" studioName="Enoel Portas" recipientName="a equipe Enoel Portas" theme="gold" mode="proposal" quizConfig={quiz} ariaLabel="Solicitar orçamento pelo WhatsApp" className="inline-flex min-h-12 items-center justify-center gap-3 rounded-sm bg-[var(--enoel-yellow)] px-6 py-3.5 font-black uppercase tracking-[.08em] text-[var(--enoel-ink)] shadow-[6px_6px_0_var(--enoel-yellow-dark)] transition hover:-translate-y-0.5 hover:shadow-[3px_3px_0_var(--enoel-yellow-dark)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--enoel-yellow)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--enoel-black)]" data-location={location}>{children}</PortfolioCTAQuiz>;
}

const services = [
  ["01", "Colocação", "Portas de madeira instaladas com prumo, ajuste e acabamento.", DoorOpen],
  ["02", "Regulagem", "Correções de fechamento, folgas, dobradiças e ferragens.", Wrench],
  ["03", "Vistas", "Molduras e guarnições que fecham o desenho do ambiente.", Ruler],
  ["04", "Caxilhos", "Soluções para portas, vãos e arremates em geral.", Hammer],
] as const;

export function EnoelPortasPage() {
  const [selected, setSelected] = useState("Colocação");
  const theme = { "--enoel-black": "#0b0c0d", "--enoel-ink": "#17191b", "--enoel-yellow": "#ffd21a", "--enoel-yellow-dark": "#a87400", "--enoel-paper": "#f4f0e7", "--enoel-muted": "#b8b3a7" } as CSSProperties;
  return <MotionScope intensity="BALANCED"><div style={theme} className="min-h-dvh overflow-hidden bg-[var(--enoel-paper)] text-[var(--enoel-ink)]">
    <header className="border-b-4 border-[var(--enoel-yellow)] bg-[var(--enoel-black)] px-5 py-4 text-white lg:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between gap-6"><a href="#inicio" aria-label="Enoel Portas" className="flex items-center gap-3"><PortfolioImage src="/images/enoel-portas/logo.png" alt="Logo Enoel Portas" width={160} height={90} priority managedField="logoUrl" className="h-12 w-auto max-w-[10rem] object-contain" /><span className="hidden border-l border-white/20 pl-4 text-[10px] font-black uppercase tracking-[.24em] text-white/60 sm:block">Portas que valorizam seu espaço</span></a><nav aria-label="Navegação principal" className="hidden gap-7 text-xs font-black uppercase tracking-[.12em] text-white/70 md:flex"><a href="#servicos" className="transition hover:text-[var(--enoel-yellow)]">Serviços</a><a href="#metodo" className="transition hover:text-[var(--enoel-yellow)]">Como fazemos</a><a href="#orcamento" className="transition hover:text-[var(--enoel-yellow)]">Orçamento</a></nav><CTA location="enoel_header">Fale com a equipe <ArrowRight className="h-4 w-4" /></CTA></div></header>
    <main>
      <section id="inicio" className="relative isolate bg-[var(--enoel-black)] px-5 py-14 text-white lg:px-10 lg:py-24"><div className="pointer-events-none absolute inset-0 -z-10 bg-[linear-gradient(120deg,rgba(255,210,26,.08),transparent_42%)]" /><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.82fr_1.18fr]"><div><p className="inline-flex items-center gap-2 border-l-4 border-[var(--enoel-yellow)] pl-3 text-[11px] font-black uppercase tracking-[.3em] text-[var(--enoel-yellow)]"><Sparkles className="h-4 w-4" />Qualidade, praticidade e segurança</p><MotionReveal as="h1" variant="mask" intensity="EXPRESSIVE" className="mt-6 max-w-2xl text-5xl font-black uppercase leading-[.9] tracking-[-.06em] sm:text-7xl">Uma boa porta muda a <span className="text-[var(--enoel-yellow)]">entrada</span> do seu projeto.</MotionReveal><p className="mt-7 max-w-xl text-lg leading-8 text-white/70">Colocação de portas de madeira, regulagem, vistas e caxilhos em geral — com uma experiência de obra mais organizada do começo ao acabamento.</p><div className="mt-9 flex flex-wrap gap-4"><CTA location="enoel_hero">Pedir orçamento <ArrowRight className="h-4 w-4" /></CTA><a href="#servicos" className="inline-flex min-h-12 items-center gap-2 border border-white/25 px-6 py-3.5 text-sm font-black uppercase tracking-[.08em] text-white transition hover:border-[var(--enoel-yellow)] hover:text-[var(--enoel-yellow)]">Ver serviços</a></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-xs font-bold uppercase tracking-[.12em] text-white/55"><span><Check className="mr-2 inline h-4 w-4 text-[var(--enoel-yellow)]" />Orçamento sem compromisso</span><span><ShieldCheck className="mr-2 inline h-4 w-4 text-[var(--enoel-yellow)]" />Cuidado no detalhe</span></div></div><MotionReveal variant="right" className="relative"><div className="absolute -inset-4 border border-[var(--enoel-yellow)]/35" /><PortfolioImage src="/images/enoel-portas/hero.png" alt="Porta de madeira em composição arquitetônica preto e amarelo" width={1680} height={945} priority managedField="heroImageUrl" className="relative aspect-video w-full object-cover" /><div className="absolute -bottom-5 -left-5 bg-[var(--enoel-yellow)] px-5 py-3 text-xs font-black uppercase tracking-[.16em] text-[var(--enoel-ink)] shadow-[6px_6px_0_var(--enoel-black)]">Portas com quem entende</div></MotionReveal></div></section>
      <section id="servicos" className="bg-[var(--enoel-paper)] px-5 py-20 lg:px-10 lg:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 border-b-2 border-[var(--enoel-ink)]/15 pb-8 md:flex-row md:items-end"><div><p className="text-[11px] font-black uppercase tracking-[.3em] text-[var(--enoel-yellow-dark)]">Escopo claro, execução cuidadosa</p><h2 className="mt-4 max-w-3xl text-4xl font-black uppercase leading-[.95] tracking-[-.04em] sm:text-6xl">O detalhe que faz a porta <span className="text-[var(--enoel-yellow-dark)]">funcionar.</span></h2></div><p className="max-w-sm text-sm leading-7 text-[var(--enoel-ink)]/65">Escolha um serviço para entender como começamos a conversa sobre o seu espaço.</p></div><div className="mt-10 grid gap-px overflow-hidden border border-[var(--enoel-ink)]/15 bg-[var(--enoel-ink)]/15 md:grid-cols-2 lg:grid-cols-4">{services.map(([code, title, text, Icon]) => <button type="button" key={code} onClick={() => setSelected(title)} className={`group min-h-64 p-6 text-left transition focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--enoel-yellow)] ${selected === title ? "bg-[var(--enoel-yellow)]" : "bg-white hover:bg-[var(--enoel-black)] hover:text-white"}`}><div className="flex items-start justify-between"><span className="font-mono text-xs font-bold opacity-50">{code}</span><Icon className="h-7 w-7 transition group-hover:scale-110" aria-hidden="true" /></div><h3 className="mt-14 text-2xl font-black uppercase tracking-[-.03em]">{title}</h3><p className="mt-3 text-sm leading-6 opacity-70">{text}</p><p className="mt-5 text-[10px] font-black uppercase tracking-[.18em] opacity-60">{selected === title ? "selecionado" : "ver detalhe"}</p></button>)}</div></div></section>
      <section id="metodo" className="bg-[var(--enoel-black)] px-5 py-20 text-white lg:px-10 lg:py-24"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_1.15fr] lg:items-center"><div><p className="text-[11px] font-black uppercase tracking-[.3em] text-[var(--enoel-yellow)]">Uma experiência mais tranquila</p><h2 className="mt-5 max-w-xl text-4xl font-black uppercase leading-[.95] tracking-[-.04em] sm:text-6xl">A bagunça é temporária. O resultado fica.</h2><p className="mt-6 max-w-lg text-base leading-8 text-white/65">A gente organiza as informações antes, cuida do encaixe durante e deixa o acabamento pronto para o seu ambiente.</p><div className="mt-9"><CTA location="enoel_metodo">Conversar sobre meu projeto <ArrowRight className="h-4 w-4" /></CTA></div></div><div className="grid gap-4 sm:grid-cols-3"><article className="border-t-4 border-[var(--enoel-yellow)] bg-white/[.06] p-6"><span className="text-3xl font-black text-[var(--enoel-yellow)]">01</span><h3 className="mt-12 text-xl font-black uppercase">Medir</h3><p className="mt-3 text-sm leading-6 text-white/60">Entender vão, modelo e necessidade do ambiente.</p></article><article className="border-t-4 border-[var(--enoel-yellow)] bg-white/[.06] p-6"><span className="text-3xl font-black text-[var(--enoel-yellow)]">02</span><h3 className="mt-12 text-xl font-black uppercase">Ajustar</h3><p className="mt-3 text-sm leading-6 text-white/60">Preparar instalação, regulagem e acabamento.</p></article><article className="border-t-4 border-[var(--enoel-yellow)] bg-white/[.06] p-6"><span className="text-3xl font-black text-[var(--enoel-yellow)]">03</span><h3 className="mt-12 text-xl font-black uppercase">Entregar</h3><p className="mt-3 text-sm leading-6 text-white/60">Deixar a porta funcionando e o espaço valorizado.</p></article></div></div></section>
      <section id="orcamento" className="bg-[var(--enoel-yellow)] px-5 py-16 lg:px-10 lg:py-20"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="text-[11px] font-black uppercase tracking-[.3em] text-[var(--enoel-ink)]/65">Curitiba e região</p><h2 className="mt-4 max-w-3xl text-4xl font-black uppercase leading-[.95] tracking-[-.05em] sm:text-6xl">Seu projeto começa com uma boa conversa.</h2><p className="mt-5 max-w-xl text-base leading-7 text-[var(--enoel-ink)]/70">Envie o contexto, a medida aproximada e o que você precisa resolver. A equipe orienta o próximo passo.</p></div><CTA location="enoel_footer">Solicitar orçamento <ArrowRight className="h-4 w-4" /></CTA></div></section>
    </main>
    <footer className="bg-[var(--enoel-black)] px-5 py-8 text-white lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-5 text-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xl font-black uppercase tracking-[-.04em]">Enoel <span className="text-[var(--enoel-yellow)]">Portas</span></p><p className="mt-1 text-xs text-white/55">Qualidade, praticidade e segurança para o seu ambiente.</p></div><div className="flex items-center gap-4 text-xs text-white/55"><span className="inline-flex items-center gap-2"><MapPin className="h-4 w-4 text-[var(--enoel-yellow)]" />Curitiba e região</span><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4 hover:text-[var(--enoel-yellow)]" /></div></div></footer>
    <PortfolioSocialProofPopup clientKey="enoel-portas" eyebrow="Enoel Portas" title="A próxima entrada do seu projeto começa aqui." description="Conte o ambiente e o serviço que precisa avaliar." ctaLabel="Pedir orçamento" ctaHref="#orcamento" delayMs={10000} className="border-[var(--enoel-yellow)]/40 bg-[var(--enoel-black)] text-white" accentClassName="text-[var(--enoel-yellow)]" /><PortfolioUpsellPopup pageName="portfolio-enoel-portas" />
  </div></MotionScope>;
}
