import { ArrowRight, CalendarDays, Check, ShieldCheck, Sparkles, TentTree } from "lucide-react";
import { FunnelCTAButton } from "@/components/funnel/FunnelCTAButton";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";

const toys = [["Tobogã inflável", "A atração que faz a criançada gastar energia e sorrir."], ["Cama elástica", "Diversão para pular, brincar e movimentar a festa."], ["Piscina de bolinhas", "Um cantinho colorido para os pequenos explorarem."], ["E muito mais", "Monte a combinação de brinquedos para o seu evento."]] as const;

export function GalileuLocacaoBrinquedosPage() {
  return <div className="min-h-dvh bg-[#f4f8ff] text-[#09265b]"><header className="sticky top-0 z-20 border-b border-[#d6e4fb] bg-[#f4f8ff]/95 px-5 py-4 backdrop-blur lg:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><a href="#inicio" aria-label="Galileu Locação de Brinquedos" className="shrink-0"><img src="/images/galileu-locacao-brinquedos/logo.png" alt="Galileu Locação de Brinquedos" width={768} height={256} fetchPriority="high" loading="eager" decoding="async" className="h-10 w-auto" /></a><nav className="hidden gap-6 text-sm font-semibold md:flex"><a href="#brinquedos">Brinquedos</a><a href="#como-funciona">Como funciona</a><a href="#orcamento">Orçamento</a></nav><FunnelCTAButton clientKey="galileu-locacao-brinquedos" companySlug="galileu-locacao-brinquedos" formSlug="funnel-galileu-locacao-brinquedos" location="galileu_header" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#0757c9] px-5 py-2.5 text-sm font-black text-white shadow-lg shadow-[#0757c9]/20">Pedir orçamento <ArrowRight className="h-4 w-4" /></FunnelCTAButton></div></header><main>
    <section id="inicio" className="mx-auto grid max-w-6xl items-center gap-10 px-5 py-14 lg:grid-cols-[.88fr_1.12fr] lg:px-8 lg:py-24"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f3ae00]">Locação de brinquedos · festas e eventos</p><h1 className="mt-5 max-w-xl text-5xl font-black leading-[.98] tracking-tight sm:text-7xl">Diversão garantida para momentos inesquecíveis.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#4a638e]">Brinquedos coloridos para transformar festas em memórias alegres: tobogã inflável, cama elástica, piscina de bolinhas e muito mais.</p><div className="mt-8 flex flex-wrap gap-3"><FunnelCTAButton clientKey="galileu-locacao-brinquedos" companySlug="galileu-locacao-brinquedos" formSlug="funnel-galileu-locacao-brinquedos" location="galileu_hero" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#f3ae00] px-6 py-3 font-black text-[#09265b]">Garantir diversão <ArrowRight className="h-4 w-4" /></FunnelCTAButton><a href="#brinquedos" className="inline-flex min-h-12 items-center rounded-full border border-[#8db0df] px-6 py-3 font-semibold text-[#0757c9]">Conhecer brinquedos</a></div><div className="mt-7 flex flex-wrap gap-4 text-sm font-semibold text-[#4a638e]"><span><Check className="mr-1 inline h-4 w-4 text-[#0757c9]" />Para festas e eventos</span><span><Check className="mr-1 inline h-4 w-4 text-[#0757c9]" />Diversão sem fim</span></div></div><PortfolioImage src="/images/galileu-locacao-brinquedos/hero.png" alt="Tobogã inflável, cama elástica e piscina de bolinhas Galileu" priority width={1280} height={1280} className="w-full rounded-[2rem] shadow-2xl shadow-[#0757c9]/20" /></section>
    <section id="brinquedos" className="bg-[#09265b] px-5 py-20 text-white lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#63d5ff]">Escolha sua atração</p><h2 className="mt-3 max-w-2xl text-4xl font-black">Um espaço de brincadeira para cada festa.</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{toys.map(([title, text], index) => <article key={title} className="rounded-2xl border border-white/15 bg-white/10 p-6"><span className="text-sm font-bold text-[#f3ae00]">0{index + 1}</span><h3 className="mt-8 text-2xl font-black">{title}</h3><p className="mt-3 leading-7 text-white/70">{text}</p></article>)}</div></div></section>
    <section id="como-funciona" className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#0757c9]">Como funciona</p><h2 className="mt-3 text-4xl font-black">Do planejamento à diversão.</h2><div className="mt-10 grid gap-5 md:grid-cols-3"><article className="rounded-2xl border border-[#d6e4fb] bg-white p-6"><CalendarDays className="h-8 w-8 text-[#0757c9]" /><h3 className="mt-8 text-2xl font-black">1. Conte a data</h3><p className="mt-3 leading-7 text-[#4a638e]">Informe a data, o local e o tipo de comemoração.</p></article><article className="rounded-2xl border border-[#d6e4fb] bg-white p-6"><ShieldCheck className="h-8 w-8 text-[#0757c9]" /><h3 className="mt-8 text-2xl font-black">2. Monte seu kit</h3><p className="mt-3 leading-7 text-[#4a638e]">Escolha os brinquedos que combinam com seu evento.</p></article><article className="rounded-2xl border border-[#d6e4fb] bg-white p-6"><TentTree className="h-8 w-8 text-[#0757c9]" /><h3 className="mt-8 text-2xl font-black">3. Prepare a festa</h3><p className="mt-3 leading-7 text-[#4a638e]">Receba a orientação para organizar um dia especial.</p></article></div></div></section>
    <section id="orcamento" className="bg-[#f3ae00] px-5 py-16 text-[#09265b] lg:px-8"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div><Sparkles className="h-8 w-8" /><p className="mt-4 text-sm font-bold uppercase tracking-[.2em]">Vamos brincar?</p><h2 className="mt-2 text-3xl font-black">Garanta alegria para a sua festa.</h2><p className="mt-3 max-w-xl leading-7 text-[#09265b]/75">Conte os detalhes do evento e receba orientação para escolher as atrações.</p></div><FunnelCTAButton clientKey="galileu-locacao-brinquedos" companySlug="galileu-locacao-brinquedos" formSlug="funnel-galileu-locacao-brinquedos" location="galileu_footer" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#09265b] px-7 py-3 font-black text-white">Solicitar orçamento <ArrowRight className="h-4 w-4" /></FunnelCTAButton></div></section>
  </main><footer className="bg-[#061638] px-5 py-8 text-sm text-[#c9dcfb] lg:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p><strong className="text-white">Galileu Locação de Brinquedos</strong><br />Brinquedos para festas e eventos.</p><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4" /></div></footer><PortfolioSocialProofPopup clientKey="galileu-locacao-brinquedos" eyebrow="Galileu Locação de Brinquedos" title="Diversão garantida para momentos inesquecíveis." description="Tobogã inflável, cama elástica, piscina de bolinhas e muito mais para festas e eventos." ctaLabel="Pedir orçamento" ctaHref="#orcamento" delayMs={9000} className="border-[#f3ae00]/40 bg-[#061638]/95 text-white" accentClassName="text-[#f3ae00]" /><PortfolioUpsellPopup pageName="portfolio-galileu-locacao-brinquedos" /></div>;
}
