import { ArrowRight, BedDouble, CheckCircle2, ExternalLink, Home, Instagram, Leaf, ShieldCheck, Sofa, Sparkles, Wind } from "lucide-react";
import { MotionReveal, MotionScope } from "@/components/motion";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";

const INSTAGRAM_URL = "https://www.instagram.com/maniadelimpeza_higienizacao/";
const quiz = { services: ["Combo família · 3 ou mais itens", "Higienização de sofá", "Higienização de colchão", "Higienização de tapete", "Quero avaliar outros itens"], experienceOptions: ["Minha casa", "Apartamento", "Empresa ou comércio", "Ainda estou pesquisando"], periodOptions: ["Curitiba", "Região Metropolitana", "Vou confirmar o local"], timingOptions: ["Quero aproveitar o combo", "Quero um orçamento", "Estou pesquisando opções"], proposalKind: "service" as const, stepTitles: { service: "O que você quer higienizar?", experience: "Onde será o atendimento?", period: "Em qual região?", timing: "Qual o próximo passo?", note: "Conte um pouco mais" }, notePlaceholder: "Ex.: quantidade de itens, tipo de tecido, manchas ou prazo desejado." };
function CTA({ children, location }: { children: React.ReactNode; location: string }) { return <PortfolioCTAQuiz clientKey="mania-de-limpeza" studioName="Mania de Limpeza Higienização" recipientName="a equipe Mania de Limpeza" theme="gold" mode="proposal" quizConfig={quiz} ariaLabel="Solicitar orçamento pelo WhatsApp" className="inline-flex min-h-12 items-center justify-center gap-3 rounded-full bg-[var(--mania-yellow)] px-6 py-3.5 font-black uppercase tracking-[.06em] text-[var(--mania-ink)] transition hover:-translate-y-1 hover:bg-[var(--mania-yellow-soft)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--mania-yellow)]" data-location={location}>{children}</PortfolioCTAQuiz>; }
const services = [[Sofa, "Estofados", "Sofás, poltronas, cadeiras e puffs com cuidado no tecido."], [BedDouble, "Colchões", "Mais conforto para a família com limpeza profunda."], [Wind, "Tapetes", "Renovação para superfícies que acumulam poeira."]] as const;
export function ManiaDeLimpezaPage() { return <MotionScope intensity="BALANCED"><div style={{ "--mania-ink": "#11130f", "--mania-black": "#050605", "--mania-yellow": "#ffd000", "--mania-yellow-soft": "#ffe873", "--mania-green": "#1f9d61", "--mania-paper": "#fffdf4", "--mania-muted": "#6c705f" } as React.CSSProperties} className="min-h-dvh overflow-hidden bg-[var(--mania-paper)] text-[var(--mania-ink)]">
    <header className="sticky top-0 z-30 border-b border-[var(--mania-yellow)]/20 bg-[var(--mania-black)]/95 px-5 py-4 text-white backdrop-blur lg:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5"><a href="#inicio" aria-label="Mania de Limpeza Higienização"><PortfolioImage src="/images/mania-de-limpeza/logo.png" alt="Logo Mania de Limpeza Higienização" width={320} height={160} priority managedField="logoUrl" className="h-12 w-auto max-w-[13rem] object-contain" /></a><nav aria-label="Navegação principal" className="hidden gap-7 text-xs font-black uppercase tracking-[.12em] text-white/70 md:flex"><a href="#servicos">Serviços</a><a href="#combo">Combo família</a><a href="#instagram">Instagram</a></nav><CTA location="mania_header">Montar meu combo <ArrowRight className="h-4 w-4" /></CTA></div></header>
    <main><section id="inicio" className="relative isolate overflow-hidden bg-[var(--mania-ink)] px-5 py-14 text-white lg:px-10 lg:py-24"><div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(circle_at_75%_15%,rgba(31,157,97,.22),transparent_30%),linear-gradient(125deg,rgba(255,208,0,.12),transparent_45%)]" /><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.83fr_1.17fr]"><div><p className="inline-flex items-center gap-2 border-l-4 border-[var(--mania-yellow)] pl-3 text-[11px] font-black uppercase tracking-[.28em] text-[var(--mania-yellow)]"><Sparkles className="h-4 w-4" />Renove o conforto da sua casa</p><MotionReveal as="h1" variant="mask" intensity="EXPRESSIVE" className="mt-6 max-w-2xl text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-7xl">Limpeza que você sente. <span className="text-[var(--mania-yellow)]">Cuidado que fica.</span></MotionReveal><p className="mt-7 max-w-xl text-lg leading-8 text-white/72">Higienização profissional para sofás, colchões e tapetes, com um combo família pensado para deixar sua casa mais limpa, cheirosa e confortável.</p><div className="mt-9 flex flex-wrap gap-4"><CTA location="mania_hero">Quero meu orçamento <ArrowRight className="h-4 w-4" /></CTA><a href="#combo" className="inline-flex min-h-12 items-center rounded-full border border-white/25 px-6 py-3.5 text-sm font-black uppercase text-white">Ver combo família</a></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-xs font-bold uppercase tracking-[.1em] text-white/55"><span><CheckCircle2 className="mr-2 inline h-4 w-4 text-[var(--mania-green)]" />A partir de 3 itens</span><span><ShieldCheck className="mr-2 inline h-4 w-4 text-[var(--mania-yellow)]" />Atendimento cuidadoso</span></div></div><MotionReveal variant="right"><PortfolioImage src="/images/mania-de-limpeza/hero.png" alt="Sala com sofá, colchão e tapete recebendo higienização profissional" width={1680} height={945} priority managedField="heroImageUrl" className="aspect-video w-full rounded-[1.5rem] object-cover shadow-2xl" /></MotionReveal></div></section>
    <section id="servicos" className="bg-[var(--mania-paper)] px-5 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-[11px] font-black uppercase tracking-[.3em] text-[var(--mania-green)]">Higienização para a vida real</p><h2 className="mt-4 max-w-3xl text-4xl font-black leading-[.95] sm:text-6xl">Mais saúde, conforto e <span className="text-[var(--mania-green)]">sensação de novo.</span></h2><div className="mt-10 grid gap-5 md:grid-cols-3">{services.map(([Icon, title, text]) => <article key={title} className="rounded-[1.75rem] border border-black/10 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><Icon className="h-9 w-9 text-[var(--mania-green)]" /><h3 className="mt-7 text-2xl font-black">{title}</h3><p className="mt-3 leading-7 text-[var(--mania-muted)]">{text}</p></article>)}</div></div></section>
    <section id="combo" className="bg-[var(--mania-yellow)] px-5 py-20 lg:px-10"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-[11px] font-black uppercase tracking-[.3em] text-black/60">Promoção combo família</p><h2 className="mt-4 text-5xl font-black leading-[.9] sm:text-7xl">A partir de 3 itens, <span className="text-white drop-shadow-[3px_3px_0_var(--mania-ink)]">R$ 100 cada.</span></h2><p className="mt-6 max-w-xl text-lg leading-8 text-black/75">Monte sua combinação com sofá, colchão, tapete ou outros itens e aproveite a condição especial para renovar a casa.</p><CTA location="mania_combo">Montar meu combo <ArrowRight className="h-4 w-4" /></CTA></div><div className="grid grid-cols-2 gap-4 sm:grid-cols-3"><div className="rounded-3xl bg-[var(--mania-ink)] p-5 text-white"><Home className="h-7 w-7 text-[var(--mania-yellow)]" /><p className="mt-10 text-sm font-black uppercase">Casa renovada</p></div><div className="rounded-3xl bg-white p-5"><ShieldCheck className="h-7 w-7 text-[var(--mania-green)]" /><p className="mt-10 text-sm font-black uppercase">Limpeza profunda</p></div><div className="col-span-2 rounded-3xl bg-[var(--mania-green)] p-5 text-white sm:col-span-1"><Leaf className="h-7 w-7 text-[var(--mania-yellow)]" /><p className="mt-10 text-sm font-black uppercase">Mais conforto</p></div></div></div></section>
    <section id="instagram" className="bg-[var(--mania-ink)] px-5 py-20 text-white lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="inline-flex items-center gap-2 text-[11px] font-black uppercase tracking-[.3em] text-[var(--mania-yellow)]"><Instagram className="h-4 w-4" />Conteúdo vivo da marca</p><h2 className="mt-4 max-w-3xl text-4xl font-black sm:text-6xl">Veja as novidades da <span className="text-[var(--mania-yellow)]">Mania de Limpeza.</span></h2><p className="mt-5 max-w-2xl leading-7 text-white/65">O perfil oficial é atualizado pelo próprio Instagram. Abra para conferir as publicações mais recentes, bastidores e ofertas.</p></div><a href={INSTAGRAM_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-[var(--mania-yellow)]/50 px-6 py-3.5 font-black text-[var(--mania-yellow)]"><Instagram className="h-5 w-5" />Abrir Instagram <ExternalLink className="h-4 w-4" /></a></div><div className="mt-10 overflow-hidden rounded-[1.75rem] border border-white/10 bg-white shadow-2xl"><iframe src={`${INSTAGRAM_URL}embed/`} title="Publicações recentes da Mania de Limpeza Higienização" className="block h-[520px] w-full" loading="lazy" scrolling="no" referrerPolicy="strict-origin-when-cross-origin" sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox allow-forms" /></div></div></section>
    <section id="orcamento" className="bg-[var(--mania-paper)] px-5 py-16 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 rounded-[2rem] border border-black/10 bg-white p-8 shadow-xl md:flex-row md:items-center"><div><p className="text-[11px] font-black uppercase tracking-[.3em] text-[var(--mania-green)]">Próximo passo</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">Sua casa merece esse cuidado.</h2><p className="mt-5 max-w-xl leading-7 text-[var(--mania-muted)]">Conte quais itens deseja higienizar e receba orientação para montar seu combo. O catálogo completo é apresentado no atendimento.</p></div><CTA location="mania_footer">Falar no WhatsApp <ArrowRight className="h-4 w-4" /></CTA></div></section></main>
    <footer className="bg-[var(--mania-black)] px-5 py-8 text-white lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-5 text-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xl font-black uppercase">Mania de <span className="text-[var(--mania-yellow)]">Limpeza</span></p><p className="mt-1 text-xs text-white/55">Higienização profissional para sua casa.</p></div><div className="flex items-center gap-4 text-xs text-white/55"><a href={INSTAGRAM_URL} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2"><Instagram className="h-4 w-4" />@maniadelimpeza_higienizacao</a><PortfolioHostCredit linkClassName="font-semibold text-white underline" /></div></div></footer>
    <PortfolioSocialProofPopup clientKey="mania-de-limpeza" eyebrow="Mania de Limpeza" title="Sua casa mais leve começa por um ambiente bem cuidado." description="Conte quais itens deseja higienizar e monte seu combo família." ctaLabel="Montar meu combo" ctaHref="#combo" delayMs={10000} className="border-[var(--mania-yellow)]/40 bg-[var(--mania-ink)] text-white" accentClassName="text-[var(--mania-yellow)]" /><PortfolioUpsellPopup pageName="portfolio-mania-de-limpeza" />
  </div></MotionScope>; }
