import { ArrowRight, CalendarDays, Check, Scissors, Sparkles, Star } from "lucide-react";
import { MotionReveal, MotionScope } from "@/components/motion";
import { ManagedText } from "@/components/portfolio/ManagedText";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";

const quiz = {
  services: ["Corte feminino", "Corte masculino", "Coloração e mechas", "Escova e finalização", "Tratamentos capilares", "Produção para evento"],
  experienceOptions: ["Quero mudar o visual", "Manutenção do corte", "Cor ou iluminação", "Tratamento e cuidado"],
  periodOptions: ["Jardim Itália", "São José dos Pinhais", "Vou confirmar o horário"],
  timingOptions: ["Quero agendar nesta semana", "Nos próximos dias", "Estou planejando"],
  proposalKind: "service" as const,
  stepTitles: { service: "Qual cuidado você procura?", experience: "O que você quer transformar?", period: "Onde fica melhor para você?", timing: "Quando gostaria de vir?", note: "Conte um pouco sobre o seu cabelo" },
  notePlaceholder: "Ex.: comprimento atual, referência de corte, cor desejada ou ocasião.",
};

function CTA({ children }: { children: React.ReactNode }) {
  return <PortfolioCTAQuiz clientKey="maximos-cabeleireiros" studioName="Maximos Cabeleireiros" recipientName="a equipe Maximos" theme="pink" mode="booking" quizConfig={quiz} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#b65c52] px-7 py-3.5 font-bold text-white shadow-lg shadow-[#b65c52]/20 transition hover:-translate-y-1 hover:bg-[#97483f] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#b65c52] focus-visible:ring-offset-2 focus-visible:ring-offset-[#f7efe8]">{children}</PortfolioCTAQuiz>;
}

const services = [
  ["01", "Cortes com intenção", "Do clássico ao novo, um corte pensado para a sua rotina e para o movimento do seu cabelo."],
  ["02", "Cor que conversa", "Coloração, mechas e iluminação com uma leitura cuidadosa do seu tom e do resultado desejado."],
  ["03", "Ritual de cuidado", "Tratamentos e finalizações para devolver toque, brilho e presença aos fios."],
];

export function MaximosCabeleireirosPage() {
  return <MotionScope intensity="BALANCED"><div className="min-h-dvh overflow-hidden bg-[#f7efe8] text-[#3b2b2a]">
    <header className="sticky top-0 z-30 border-b border-[#dfcfc7] bg-[#f7efe8]/95 px-5 py-4 backdrop-blur lg:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5"><a href="#inicio" aria-label="Maximos Cabeleireiros" className="flex items-center gap-3"><PortfolioImage src="/images/maximos-cabeleireiros/logo.png" alt="Marca abstrata Maximos Cabeleireiros" width={160} height={160} priority managedField="logoUrl" className="h-11 w-11 rounded-full object-cover" /><span className="font-display text-lg font-bold tracking-tight text-[#3b2b2a]">Maximos <span className="font-normal text-[#b65c52]">Cabeleireiros</span></span></a><nav className="hidden gap-7 text-sm font-semibold text-[#7a625e] md:flex" aria-label="Navegação principal"><a href="#servicos" className="transition hover:text-[#b65c52]">Serviços</a><a href="#ritual" className="transition hover:text-[#b65c52]">Ritual</a><a href="#contato" className="transition hover:text-[#b65c52]">Agendamento</a></nav><CTA>Agendar horário <ArrowRight className="h-4 w-4" /></CTA></div></header>
    <main>
      <section id="inicio" className="relative overflow-hidden px-5 py-14 lg:px-10 lg:py-24"><div className="pointer-events-none absolute -left-48 -top-40 h-[34rem] w-[34rem] rounded-full bg-[#e7b8a5]/30 blur-3xl" /><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.84fr_1.16fr]"><div className="relative z-10"><p className="font-mono text-[11px] font-bold uppercase tracking-[.27em] text-[#b65c52]">Jardim Itália · São José dos Pinhais</p><MotionReveal as="h1" variant="mask" intensity="EXPRESSIVE" className="mt-6 max-w-2xl font-display text-5xl font-bold leading-[.96] tracking-[-.045em] text-[#3b2b2a] sm:text-7xl"><ManagedText field="heroHeadline" fallback="Seu cabelo, do jeito que faz sentido para você." /></MotionReveal><p className="mt-6 max-w-xl text-base leading-8 text-[#715d59]"><ManagedText field="heroSubheadline" fallback="Cortes, cor e cuidados em um atendimento próximo, cuidadoso e pensado para a sua beleza real." /></p><div className="mt-8 flex flex-wrap gap-3"><CTA>Quero conversar sobre meu visual <ArrowRight className="h-4 w-4" /></CTA><a href="#servicos" className="inline-flex min-h-12 items-center rounded-full border border-[#cba69c] px-6 py-3.5 font-bold text-[#5c4642] transition hover:border-[#b65c52] hover:text-[#b65c52]">Conhecer serviços</a></div><div className="mt-9 flex flex-wrap gap-5 border-t border-[#dfcfc7] pt-5 text-xs font-bold text-[#7a625e]"><span className="inline-flex items-center gap-2"><Scissors className="h-4 w-4 text-[#b65c52]" /> Escuta antes de criar</span><span className="inline-flex items-center gap-2"><Sparkles className="h-4 w-4 text-[#b65c52]" /> Beleza possível</span><span className="inline-flex items-center gap-2"><CalendarDays className="h-4 w-4 text-[#b65c52]" /> Horário combinado</span></div></div><MotionReveal variant="right" className="relative"><PortfolioImage src="/images/maximos-cabeleireiros/hero.png" alt="Bancada editorial de salão com tesouras, pentes e espelho" priority managedField="heroImageUrl" width={1680} height={945} className="aspect-video w-full rounded-[2rem] object-cover shadow-2xl ring-1 ring-[#caa89a]" /><p className="mt-3 text-right text-[10px] uppercase tracking-[.16em] text-[#947870]">Imagem editorial · atmosfera da marca</p></MotionReveal></div></section>
      <section id="servicos" className="bg-[#3b2b2a] px-5 py-20 text-[#fff8f3] lg:px-10 lg:py-24"><div className="mx-auto max-w-7xl"><div className="grid gap-6 lg:grid-cols-[1fr_.6fr] lg:items-end"><div><p className="font-mono text-[11px] font-bold uppercase tracking-[.27em] text-[#e7b8a5]">Serviços</p><h2 className="mt-4 max-w-3xl font-display text-4xl font-bold leading-tight sm:text-5xl">Um cuidado que começa na conversa.</h2></div><p className="text-sm leading-7 text-[#d9c4bd]">Você chega com uma ideia, uma dúvida ou só vontade de se sentir bem. A equipe ajuda a encontrar o próximo passo.</p></div><div className="mt-12 grid gap-px overflow-hidden border border-[#74504a] bg-[#74504a] md:grid-cols-3">{services.map(([code, title, text], i) => <MotionReveal as="article" variant="up" delay={i * 90} key={code} className="min-h-72 bg-[#493332] p-7 transition hover:bg-[#5b3c39]"><p className="font-mono text-xs font-bold tracking-[.2em] text-[#e7b8a5]">{code}</p><Scissors className="mt-10 h-7 w-7 text-[#e7b8a5]" aria-hidden /><h3 className="mt-5 font-display text-2xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#d9c4bd]">{text}</p></MotionReveal>)}</div><div className="mt-4 flex flex-col items-start justify-between gap-4 rounded-2xl bg-[#f7efe8] px-6 py-5 text-sm text-[#5c4642] sm:flex-row sm:items-center"><span>Já sabe o que quer fazer?</span><CTA>Falar com o Maximos <ArrowRight className="h-4 w-4" /></CTA></div></div></section>
      <section id="ritual" className="bg-[#fffaf6] px-5 py-20 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><p className="font-mono text-[11px] font-bold uppercase tracking-[.27em] text-[#b65c52]">O ritual Maximos</p><h2 className="mt-4 font-display text-4xl font-bold leading-tight text-[#3b2b2a] sm:text-5xl">Não é só sobre mudar. É sobre reconhecer você no espelho.</h2><p className="mt-6 max-w-2xl text-base leading-8 text-[#715d59]">Cada atendimento parte do seu momento, da sua rotina e do que você quer sentir. O resultado é uma beleza mais leve de levar para a vida.</p><div className="mt-9 grid gap-4 sm:grid-cols-3">{[["Escutar", "Entender o que você procura."], ["Desenhar", "Traduzir intenção em forma e cor."], ["Cuidar", "Finalizar com atenção aos detalhes."]].map(([title, text]) => <div key={title} className="border-l-2 border-[#b65c52] pl-4"><p className="font-bold text-[#3b2b2a]">{title}</p><p className="mt-2 text-xs leading-5 text-[#7a625e]">{text}</p></div>)}</div></div><figure className="relative m-0"><div className="absolute -inset-4 rounded-[2rem] border border-[#e7b8a5]" /><PortfolioImage src="/images/maximos-cabeleireiros/logo.png" alt="Emblema abstrato com tesouras e mecha de cabelo" width={1024} height={1024} className="relative mx-auto aspect-square max-w-md rounded-[2rem] object-cover shadow-xl" /></figure></div></section>
      <section id="contato" className="bg-[#e7b8a5] px-5 py-16 lg:px-10 lg:py-20"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 rounded-[2rem] bg-[#3b2b2a] p-8 text-white shadow-2xl sm:p-12 lg:flex-row lg:items-center"><div><p className="font-mono text-[11px] font-bold uppercase tracking-[.27em] text-[#e7b8a5]">Agendamento</p><h2 className="mt-4 max-w-2xl font-display text-4xl font-bold leading-tight sm:text-5xl">Seu próximo horário pode começar aqui.</h2><p className="mt-4 max-w-xl leading-7 text-[#d9c4bd]">Atendimento no Jardim Itália, em São José dos Pinhais. Conte o que você procura e receba orientação pelo WhatsApp.</p></div><CTA>Solicitar meu horário <ArrowRight className="h-4 w-4" /></CTA></div></section>
    </main>
    <footer className="border-t border-[#dfcfc7] bg-[#f7efe8] px-5 py-8 text-sm text-[#7a625e] lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-display font-bold text-[#3b2b2a]">Maximos <span className="text-[#b65c52]">Cabeleireiros</span></p><p className="mt-1 text-xs">Jd. Itália · Rua Quirino Zagonel, 1359 · Braga · São José dos Pinhais/PR</p></div><div className="text-left sm:text-right"><p className="text-xs">Atendimento com hora marcada</p><PortfolioHostCredit linkClassName="mt-2 inline-block font-semibold text-[#3b2b2a] underline underline-offset-4 hover:text-[#b65c52]" /></div></div></footer>
    <PortfolioSocialProofPopup clientKey="maximos-cabeleireiros" eyebrow="Maximos Cabeleireiros" title="Seu visual merece uma conversa atenta." description="Agende seu horário e conte o que você quer transformar." ctaLabel="Agendar horário" ctaHref="#contato" delayMs={10000} className="border-[#b65c52]/40 bg-[#3b2b2a]/95 text-white" accentClassName="text-[#e7b8a5]" /><PortfolioUpsellPopup pageName="portfolio-maximos-cabeleireiros" />
  </div></MotionScope>;
}
