import { ArrowRight, Check, Cpu, Database, Instagram, Monitor, Microwave, Sparkles } from "lucide-react";
import { FunnelCTAButton } from "@/components/funnel/FunnelCTAButton";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";

const services = [["TV", "Manutenção em todas as marcas e modelos.", Monitor], ["Computadores", "Manutenção preventiva e corretiva, formatação, limpeza e upgrade.", Cpu], ["Micro-ondas", "Manutenção em geral para devolver praticidade à rotina.", Microwave], ["Recuperação de dados", "Recuperação de dados de HD com segurança e tecnologia avançada.", Database]] as const;

export function MiroTechPage() {
  return <div className="min-h-dvh bg-[#050805] text-white"><header className="sticky top-0 z-20 border-b border-[#9be500]/25 bg-[#050805]/95 px-5 py-4 backdrop-blur lg:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><a href="#inicio" aria-label="MIRO TECH" className="shrink-0"><img src="/images/miro-tech/logo.png" alt="MIRO TECH" className="h-10 w-auto" /></a><nav className="hidden gap-6 text-sm font-semibold text-white/80 md:flex"><a href="#servicos">Serviços</a><a href="#diferenciais">Diferenciais</a><a href="#instagram">Instagram</a></nav><FunnelCTAButton clientKey="miro-tech" companySlug="miro-tech" formSlug="funnel-miro-tech" location="miro_header" className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#9be500] px-5 py-2.5 text-sm font-black text-black">Solicitar atendimento <ArrowRight className="h-4 w-4" /></FunnelCTAButton></div></header><main>
    <section id="inicio" className="mx-auto grid max-w-6xl items-center gap-10 px-5 py-14 lg:grid-cols-[.9fr_1.1fr] lg:px-8 lg:py-24"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#9be500]">Assistência técnica · São José dos Pinhais</p><h1 className="mt-5 max-w-xl text-5xl font-black leading-[.98] tracking-tight sm:text-7xl">Seu equipamento em boas mãos.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/70">Manutenção especializada para TVs, computadores, micro-ondas e recuperação de dados de HD, com atendimento no bairro Academia e região.</p><div className="mt-8 flex flex-wrap gap-3"><FunnelCTAButton clientKey="miro-tech" companySlug="miro-tech" formSlug="funnel-miro-tech" location="miro_hero" className="inline-flex min-h-12 items-center gap-2 rounded-lg bg-[#9be500] px-6 py-3 font-black text-black">Falar com a MIRO TECH <ArrowRight className="h-4 w-4" /></FunnelCTAButton><a href="#servicos" className="inline-flex min-h-12 items-center rounded-lg border border-[#9be500]/60 px-6 py-3 font-semibold text-[#d8ff8b]">Ver serviços</a></div><div className="mt-7 flex flex-wrap gap-4 text-sm font-semibold text-white/70"><span><Check className="mr-1 inline h-4 w-4 text-[#9be500]" />Profissionais qualificados</span><span><Check className="mr-1 inline h-4 w-4 text-[#9be500]" />Atendimento rápido</span></div></div><PortfolioImage src="/images/miro-tech/hero.png" alt="Serviços de manutenção da MIRO TECH" priority width={854} height={1280} className="w-full rounded-2xl border border-[#9be500]/30 object-cover shadow-2xl shadow-[#9be500]/10" /></section>
    <section id="servicos" className="bg-[#101610] px-5 py-20 lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#9be500]">Manutenção especializada</p><h2 className="mt-3 max-w-2xl text-4xl font-black">Diagnóstico claro para cada equipamento.</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{services.map(([title, text, Icon]) => <article key={title} className="rounded-2xl border border-[#9be500]/25 bg-black/30 p-6"><Icon className="h-8 w-8 text-[#9be500]" /><h3 className="mt-8 text-2xl font-black">{title}</h3><p className="mt-3 leading-7 text-white/65">{text}</p></article>)}</div></div></section>
    <section id="diferenciais" className="px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><Sparkles className="h-9 w-9 text-[#9be500]" /><p className="mt-6 text-sm font-bold uppercase tracking-[.2em] text-[#9be500]">Por que escolher</p><h2 className="mt-3 text-4xl font-black">Soluções inteligentes, resultados reais.</h2></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-white/10 p-5"><h3 className="font-bold text-[#d8ff8b]">Atendimento rápido</h3><p className="mt-2 text-sm leading-6 text-white/65">Organize o diagnóstico e combine o próximo passo pelo atendimento.</p></div><div className="rounded-xl border border-white/10 p-5"><h3 className="font-bold text-[#d8ff8b]">Preços justos</h3><p className="mt-2 text-sm leading-6 text-white/65">Cada serviço é avaliado conforme o equipamento e a necessidade.</p></div></div></div></section>
    <section id="instagram" className="bg-[#9be500] px-5 py-16 text-black lg:px-8"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div><Instagram className="h-8 w-8" /><p className="mt-4 text-sm font-bold uppercase tracking-[.2em]">Presença digital</p><h2 className="mt-2 text-3xl font-black">Veja dicas e serviços da MIRO TECH.</h2><p className="mt-3 max-w-xl leading-7 text-black/70">Um espaço para acompanhar soluções, cuidados e novidades da assistência técnica.</p></div><FunnelCTAButton clientKey="miro-tech" companySlug="miro-tech" formSlug="funnel-miro-tech" location="miro_social" className="inline-flex min-h-12 items-center gap-2 rounded-lg bg-black px-6 py-3 font-bold text-white">Falar com a equipe <ArrowRight className="h-4 w-4" /></FunnelCTAButton></div></section>
    <section className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-5xl rounded-2xl border border-[#9be500]/30 bg-[#101610] px-7 py-12 text-center sm:px-12"><h2 className="text-4xl font-black">Precisa recuperar ou consertar?</h2><p className="mx-auto mt-4 max-w-2xl text-lg leading-8 text-white/70">Conte qual equipamento precisa de atenção e organize seu atendimento.</p><FunnelCTAButton clientKey="miro-tech" companySlug="miro-tech" formSlug="funnel-miro-tech" location="miro_footer" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-lg bg-[#9be500] px-7 py-3.5 font-black text-black">Solicitar avaliação <ArrowRight className="h-4 w-4" /></FunnelCTAButton></div></section>
  </main><footer className="bg-black px-5 py-8 text-sm text-white/60 lg:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p><strong className="text-white">MIRO TECH</strong><br />Manutenção especializada em São José dos Pinhais.</p><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4" /></div></footer><PortfolioSocialProofPopup clientKey="miro-tech" eyebrow="MIRO TECH" title="Seu equipamento em boas mãos." description="Manutenção especializada para TV, computadores, micro-ondas e recuperação de dados." ctaLabel="Ver serviços" ctaHref="#servicos" delayMs={9000} className="border-[#9be500]/35 bg-black/95 text-white" accentClassName="text-[#9be500]" /><PortfolioUpsellPopup pageName="portfolio-miro-tech" /></div>;
}
