import { ManagedText } from "@/components/portfolio/ManagedText";
import { motion } from "motion/react";
import { ArrowRight, CalendarDays, Check, Heart, Instagram, MapPin, Sparkles, Star } from "lucide-react";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";

const quiz = {
  services: ["Festa na Mesa · a partir de R$ 160", "Decoração Clássica · a partir de R$ 250", "Decoração Premium · a partir de R$ 350", "Casamento ou evento especial", "Ainda não sei — quero uma sugestão"],
  experienceOptions: ["Aniversário infantil", "Aniversário adulto", "Casamento ou noivado", "Evento corporativo / especial"],
  periodOptions: ["Araucária", "Curitiba e região", "Ainda vou confirmar o local"],
  timingOptions: ["Nos próximos 30 dias", "Neste semestre", "Estou planejando"],
  proposalKind: "service" as const,
  stepTitles: { service: "Qual decoração combina com sua festa?", experience: "Que momento vamos celebrar?", period: "Onde será o evento?", timing: "Quando é a sua data?", note: "Conte um pouco mais" },
  notePlaceholder: "Ex.: tema, número de convidados, cores, endereço e referências que você imagina.",
};

function CTA({ children }: { children: React.ReactNode }) {
  return <PortfolioCTAQuiz clientKey="mp-festas-eventos" studioName="MP Festas e Eventos" recipientName="MP Festas e Eventos" theme="navy" mode="proposal" quizConfig={quiz} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#0b2b62] px-6 py-3.5 font-bold text-white shadow-lg shadow-[#0b2b62]/20 transition hover:-translate-y-1 hover:bg-[#123d83] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#d5a83d]">{children}</PortfolioCTAQuiz>;
}

const packages = [
  { name: "Festa na Mesa", price: "R$ 160", detail: "Uma composição charmosa e prática para comemorar com economia.", accent: "bg-[#e96d8a]" },
  { name: "Decoração Clássica", price: "R$ 250", detail: "Painel, arco orgânico e detalhes coordenados para uma mesa completa.", accent: "bg-[#1762b5]" },
  { name: "Decoração Premium", price: "R$ 350", detail: "Mais impacto, volume e personalidade para uma festa inesquecível.", accent: "bg-[#7352a8]" },
];

export function MpFestasEventosPage() {
  return <div className="min-h-dvh bg-[#fffaf4] text-[#102b55]">
    <header className="sticky top-0 z-20 border-b border-[#eadfce] bg-[#fffaf4]/90 px-5 py-4 backdrop-blur lg:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><a href="#inicio" className="flex items-center gap-3 font-display text-lg font-bold"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#0b2b62] text-[#f4c24c]"><Sparkles className="h-5 w-5" /></span><span>MP Festas <span className="text-[#c3932e]">& Eventos</span></span></a><nav className="hidden gap-6 text-sm font-semibold md:flex"><a href="#pacotes" className="hover:text-[#c3932e]">Pacotes</a><a href="#inspiracoes" className="hover:text-[#c3932e]">Inspirações</a><a href="#local" className="hover:text-[#c3932e]">Atendimento</a></nav><CTA>Consultar disponibilidade <ArrowRight className="h-4 w-4" /></CTA></div></header>
    <main>
      <section id="inicio" className="relative overflow-hidden px-5 py-14 lg:px-8 lg:py-24"><div className="pointer-events-none absolute -right-32 -top-24 h-80 w-80 rounded-full bg-[#f4c24c]/25 blur-3xl" /><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[.9fr_1.1fr]"><div className="relative"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#b27e1d]">Decoração afetiva · Araucária e região</p><h1 className="mt-5 font-display text-5xl font-bold leading-[.98] sm:text-7xl">
            <ManagedText field="heroHeadline" fallback={"Sua festa linda, do jeitinho que voc\u00ea sonhou."} />
          </h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#536987]">
            <ManagedText field="heroSubheadline" fallback={"Festas infantis, celebra\u00e7\u00f5es e eventos especiais com cen\u00e1rios cheios de cor, carinho e personalidade \u2014 sem precisar gastar uma fortuna."} />
          </p><div className="mt-8 flex flex-wrap gap-3"><CTA>Chamar no WhatsApp <ArrowRight className="h-4 w-4" /></CTA><a href="#pacotes" className="inline-flex min-h-12 items-center rounded-full border border-[#b9a77c] px-6 py-3.5 font-semibold text-[#0b2b62]">Ver pacotes</a></div><div className="mt-8 flex flex-wrap gap-4 text-sm font-semibold text-[#536987]"><span><Check className="mr-1 inline h-4 w-4 text-[#c3932e]" />Agenda com datas limitadas</span><span><MapPin className="mr-1 inline h-4 w-4 text-[#c3932e]" />Araucária e região</span></div></div><motion.div initial={{ opacity: 0, y: 20, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: .65 }} className="relative"><div className="absolute -inset-3 rounded-[2rem] bg-[#f4c24c]/30 blur-xl" /><PortfolioImage src="/images/mp-festas-eventos/capa.webp" alt="Três opções de decoração da MP Festas e Eventos" priority width={1024} height={1536} className="relative w-full rounded-[2rem] object-cover shadow-2xl"
            managedField="heroImageUrl"
          /></motion.div></div></section>
      <section id="pacotes" className="bg-[#0b2b62] px-5 py-20 text-white lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f4c24c]">Escolha o seu cenário</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-bold">Três formas de deixar a data ainda mais especial.</h2><div className="mt-10 grid gap-5 lg:grid-cols-3">{packages.map((item, index) => <motion.article key={item.name} whileHover={{ y: -7 }} transition={{ duration: .2 }} className="overflow-hidden rounded-3xl border border-white/15 bg-white/10"><div className={`h-2 ${item.accent}`} /><div className="p-6"><span className="text-sm font-bold text-[#f4c24c]">0{index + 1}</span><h3 className="mt-8 text-2xl font-bold">{item.name}</h3><p className="mt-3 text-4xl font-black text-[#f4c24c]">{item.price}</p><p className="mt-4 leading-7 text-[#dbe5f5]">{item.detail}</p><a href="#pedido" className="mt-6 inline-flex min-h-11 items-center gap-2 font-bold text-[#f4c24c] hover:underline">Quero este pacote <ArrowRight className="h-4 w-4" /></a></div></motion.article>)}</div></div></section>
      <section id="inspiracoes" className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#b27e1d]">Inspirações reais</p><h2 className="mt-3 font-display text-4xl font-bold">Temas para crianças, adultos e grandes histórias.</h2></div><a href="https://www.instagram.com/mp_festa_na_mesa" target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#b9a77c] px-5 font-semibold hover:bg-[#fff1c9]"><Instagram className="h-4 w-4" /> @mp_festa_na_mesa</a></div><div className="mt-10 grid gap-5 md:grid-cols-[1.15fr_.85fr]"><motion.figure whileHover={{ y: -5 }} className="overflow-hidden rounded-[2rem] border border-[#eadfce] bg-white shadow-sm"><PortfolioImage src="/images/mp-festas-eventos/galeria.webp" alt="Bolos e decorações personalizadas em diferentes temas" width={900} height={1600} className="h-full max-h-[720px] w-full object-cover" /><figcaption className="p-5 font-semibold">Cada tema ganha uma composição pensada para a sua história.</figcaption></motion.figure><div className="grid gap-5"><div className="rounded-3xl bg-[#f9df9d] p-7"><Heart className="h-8 w-8 text-[#0b2b62]" /><h3 className="mt-8 text-2xl font-bold">Carinho em cada detalhe</h3><p className="mt-3 leading-7 text-[#536987]">Do primeiro briefing à montagem, tudo é planejado para a celebração fluir leve.</p></div><div className="rounded-3xl bg-[#e9eff8] p-7"><Star className="h-8 w-8 text-[#c3932e]" /><h3 className="mt-8 text-2xl font-bold">Acervo em expansão</h3><p className="mt-3 leading-7 text-[#536987]">Temas infantis e novas opções para casamentos e eventos especiais chegando.</p></div></div></div></div></section>
      <section id="local" className="bg-[#f4eee4] px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#b27e1d]">Atendimento local</p><h2 className="mt-3 font-display text-4xl font-bold">Araucária e região, com montagem inclusa.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-[#536987]">A MP Festas e Eventos leva a decoração até você e cobra apenas a taxa de deslocamento. Reserve com antecedência para garantir sua data.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-white p-5"><CalendarDays className="h-6 w-6 text-[#c3932e]" /><p className="mt-4 font-bold">Reserve antes</p><p className="mt-1 text-sm text-[#536987]">Agenda limitada por data.</p></div><div className="rounded-2xl bg-white p-5"><MapPin className="h-6 w-6 text-[#c3932e]" /><p className="mt-4 font-bold">Onde atendemos</p><p className="mt-1 text-sm text-[#536987]">Araucária e região.</p></div></div></div><div id="pedido" className="rounded-[2rem] bg-white p-8 shadow-xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#b27e1d]">Vamos criar juntos?</p><h3 className="mt-3 text-3xl font-bold">Conte a sua ideia para a MP.</h3><p className="mt-3 leading-7 text-[#536987]">Em poucos passos, você informa o tema, a data e o pacote que mais combina com a sua comemoração.</p><div className="mt-7"><CTA>Pedir orçamento <ArrowRight className="h-4 w-4" /></CTA></div></div></div></section>
    </main>
    <footer className="bg-[#071d43] px-5 py-8 text-sm text-[#c9d6ea] lg:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-white">MP Festas <span className="text-[#f4c24c]">& Eventos</span></p><p className="mt-1">Decoração de festas em Araucária e região.</p></div><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4 hover:text-[#f4c24c]" /></div></footer>
    <PortfolioSocialProofPopup clientKey="mp-festas-eventos" eyebrow="MP Festas e Eventos" title="Uma decoração especial transforma a memória da sua festa." description="Escolha o pacote, conte o tema e receba uma orientação para a sua data." ctaLabel="Ver pacotes" ctaHref="#pacotes" delayMs={9000} className="border-[#f4c24c]/30 bg-[#0b2b62]/95 text-white" accentClassName="text-[#f4c24c]" />
    <PortfolioUpsellPopup pageName="portfolio-mp-festas-eventos" />
  </div>;
}
