import { Clock3, MapPin, ShoppingBag, Store, Truck } from "lucide-react";
import { FunnelCTAButton } from "@/components/funnel/FunnelCTAButton";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";

export function PastelariaRoute66Page() {
  return <div data-client-slug="pastelaria-route-66" className="min-h-dvh bg-[#fff9ee] text-[#35151b]">
    <header className="sticky top-0 z-30 border-b border-[#ead7c5] bg-[#fff9ee]/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><a href="#inicio" aria-label="Route 66, início"><PortfolioImage managedField="logoUrl" priority src="/images/pastelaria-route-66/logo.svg" alt="Route 66 Pastelaria e Lanchonete" width={160} height={48} decoding="async" className="h-12 w-auto" /></a><nav className="hidden items-center gap-6 text-sm font-semibold md:flex"><a href="#atendimento">Atendimento</a><a href="#horarios">Horários</a><a href="#localizacao">Como chegar</a></nav><FunnelCTAButton clientKey="pastelaria-route-66" companySlug="pastelaria-route-66" formSlug="funnel-pastelaria-route-66" location="route66_header">Estou com fome</FunnelCTAButton></div></header>
    <main id="inicio">
      <section className="bg-[#6e1f2b] text-[#fff9ee]"><div className="mx-auto grid max-w-6xl items-center gap-10 px-5 py-14 md:grid-cols-[1.05fr_.95fr] md:py-20"><div><p className="mb-5 inline-flex rounded-full border border-[#f4c447] px-4 py-2 text-xs font-bold uppercase tracking-[0.18em] text-[#f4c447]">Prado Velho · Curitiba</p><h1 className="max-w-xl text-5xl font-black leading-[.95] tracking-tight md:text-7xl">Tá com fome? Pega a estrada para a Route 66.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#ffe9d2]">Café da manhã, salgados e almoço para consumir no local, retirar ou receber em casa. Uma parada simples, gostosa e feita para a rotina do bairro.</p><div className="mt-8 flex flex-wrap gap-3"><FunnelCTAButton clientKey="pastelaria-route-66" companySlug="pastelaria-route-66" formSlug="funnel-pastelaria-route-66" location="route66_hero">Quero pedir</FunnelCTAButton><a href="#atendimento" className="rounded-full border border-[#ffe9d2]/50 px-6 py-3 font-bold">Ver atendimento</a></div><p className="mt-5 flex items-center gap-2 text-sm text-[#ffe9d2]"><MapPin className="h-4 w-4" /> Rua Comendador Roseira, 505 · Prado Velho</p></div><PortfolioImage src="/images/pastelaria-route-66/fachada.webp" alt="Fachada real da Pastelaria e Lanchonete Route 66" className="aspect-[4/3] w-full rounded-[2rem] object-cover shadow-2xl" /></div></section>
      <section id="atendimento" className="mx-auto max-w-6xl px-5 py-16 md:py-24"><div className="grid gap-10 md:grid-cols-[.8fr_1.2fr] md:items-start"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a53642]">Atendimento que cabe no seu dia</p><h2 className="mt-3 text-4xl font-black leading-tight md:text-5xl">Escolha como quer viver a sua parada.</h2><p className="mt-5 leading-7 text-[#6c4f4b]">A Route 66 atende quem passa pelo Prado Velho e quem prefere pedir de casa. O próximo passo é seu.</p></div><div className="grid gap-4 sm:grid-cols-3"><article className="rounded-3xl border border-[#ead7c5] bg-white p-6 transition-transform hover:-translate-y-1"><Store className="text-[#a53642]"/><h3 className="mt-5 font-black">No local</h3><p className="mt-2 text-sm text-[#6c4f4b]">Sente, faça sua pausa e aproveite o atendimento.</p></article><article className="rounded-3xl border border-[#ead7c5] bg-white p-6 transition-transform hover:-translate-y-1"><ShoppingBag className="text-[#a53642]"/><h3 className="mt-5 font-black">Retirada</h3><p className="mt-2 text-sm text-[#6c4f4b]">Combine seu pedido e passe para buscar.</p></article><article className="rounded-3xl border border-[#ead7c5] bg-white p-6 transition-transform hover:-translate-y-1"><Truck className="text-[#a53642]"/><h3 className="mt-5 font-black">Entrega</h3><p className="mt-2 text-sm text-[#6c4f4b]">Consulte a entrega pelo WhatsApp.</p></article></div></div><div className="mt-12 overflow-hidden rounded-[2rem] bg-[#f2dfc5] md:grid md:grid-cols-2"><PortfolioImage src="/images/pastelaria-route-66/interior.webp" alt="Interior real da Pastelaria e Lanchonete Route 66" className="h-full min-h-72 w-full object-cover transition-transform duration-700 hover:scale-[1.02]"/><div className="p-8 md:p-12"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a53642]">Uma parada no bairro</p><h3 className="mt-3 text-3xl font-black">Café, salgado e almoço com jeito de vizinhança.</h3><p className="mt-5 leading-7 text-[#6c4f4b]">Informações diretas para você decidir rápido: estamos no Prado Velho, de segunda a sábado, das 7h às 20h.</p></div></div></section>
      <section id="horarios" className="border-y border-[#ead7c5] bg-[#fffdf8]"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-16 md:grid-cols-2 md:py-20"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a53642]">Planeje sua visita</p><h2 className="mt-3 text-4xl font-black">Horário e localização sem complicação.</h2></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-3xl bg-[#6e1f2b] p-7 text-[#fff9ee]"><Clock3 className="text-[#f4c447]"/><h3 className="mt-5 font-black">Segunda a sábado</h3><p className="mt-2 text-2xl font-black">7h às 20h</p><p className="mt-2 text-sm text-[#ffe9d2]">Domingo: fechado</p></div><div id="localizacao" className="rounded-3xl border border-[#ead7c5] p-7"><MapPin className="text-[#a53642]"/><h3 className="mt-5 font-black">Prado Velho</h3><p className="mt-2 leading-6 text-[#6c4f4b]">Rua Comendador Roseira, 505<br/>Curitiba — PR</p></div></div></div></section>
      <section className="mx-auto max-w-6xl px-5 py-16 text-center md:py-24"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a53642]">Sua próxima parada</p><h2 className="mx-auto mt-3 max-w-2xl text-4xl font-black md:text-6xl">Quando a fome apertar, a Route 66 está no caminho.</h2><p className="mx-auto mt-5 max-w-xl text-[#6c4f4b]">Conte o que você precisa e escolha entre local, retirada ou entrega.</p><div className="mt-8"><FunnelCTAButton clientKey="pastelaria-route-66" companySlug="pastelaria-route-66" formSlug="funnel-pastelaria-route-66" location="route66_final">Fazer um pedido</FunnelCTAButton></div></section>
    </main>
    <footer className="bg-[#35151b] px-5 py-10 text-[#ffe9d2]"><div className="mx-auto flex max-w-6xl flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><PortfolioImage managedField="logoUrl" src="/images/pastelaria-route-66/logo.svg" alt="Route 66" width={160} height={48} loading="lazy" decoding="async" className="h-12 w-auto brightness-0 invert"/><p className="mt-3 text-sm">Pastelaria e Lanchonete · Prado Velho · Curitiba</p></div><PortfolioHostCredit /></div></footer><PortfolioSocialProofPopup clientKey="pastelaria-route-66" eyebrow="Route 66 · Prado Velho" title="Bateu a fome agora?" description="Peça no local, retire ou receba em casa — é só chamar a equipe." ctaLabel="Quero pedir" ctaHref="#inicio" delayMs={9000} className="border-[#f4c447]/40 bg-[#6e1f2b] text-[#fff9ee]" accentClassName="text-[#f4c447]" /><PortfolioUpsellPopup pageName="portfolio-pastelaria-route-66" />
  </div>;
}
