import { ArrowRight, Check, Instagram, Sparkles } from "lucide-react";
import { FunnelCTAButton } from "@/components/funnel/FunnelCTAButton";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";

const services = [["Plotagem de móveis", "Renove portas e frentes com acabamento premium, cores modernas e aplicação pronta no mesmo dia."], ["Envelopamento de geladeiras", "Escolha entre mais de 800 opções de imagens e cores para personalizar eletros com acabamento profissional."], ["Comunicação visual", "Adesivos para paredes, portas e automóveis, além de lonas, banners e perfurados."], ["Criação de artes", "Logotipos e artes personalizadas para dar unidade à comunicação da sua marca."]] as const;

export function PremiumEnvelopamentosPage() {
  return <div className="min-h-dvh bg-[#f5f8fb] text-[#071d41]">
    <header className="sticky top-0 z-20 border-b border-[#d7e3ef] bg-[#f5f8fb]/95 px-5 py-4 backdrop-blur lg:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><a href="#inicio" aria-label="Premium Envelopamentos" className="shrink-0"><img src="/images/premium-envelopamentos/logo.png" alt="Premium Envelopamentos" width={768} height={256} fetchPriority="high" loading="eager" decoding="async" className="h-10 w-auto" /></a><nav className="hidden gap-6 text-sm font-semibold md:flex"><a href="#servicos">Serviços</a><a href="#galeria">Galeria</a><a href="#instagram">Instagram</a></nav><FunnelCTAButton clientKey="premium-envelopamentos" companySlug="premium-envelopamentos" formSlug="funnel-premium-envelopamentos" location="premium_header" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#0a2b5e] px-5 py-2.5 text-sm font-bold text-white shadow-lg shadow-[#0a2b5e]/20">Solicitar orçamento <ArrowRight className="h-4 w-4" /></FunnelCTAButton></div></header>
    <main>
      <section id="inicio" className="mx-auto grid max-w-6xl items-center gap-10 px-5 py-14 lg:grid-cols-[.9fr_1.1fr] lg:px-8 lg:py-24"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f06a24]">Plotagem · envelopamento · comunicação visual</p><h1 className="mt-5 max-w-xl text-5xl font-black leading-[.98] tracking-tight sm:text-7xl">Seu móvel muda de cara. Seu ambiente ganha presença.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#46617c]">Plotagem de móveis e envelopamento de geladeiras com aplicação limpa, cores atuais e acabamento profissional em Curitiba e região.</p><div className="mt-8 flex flex-wrap gap-3"><FunnelCTAButton clientKey="premium-envelopamentos" companySlug="premium-envelopamentos" formSlug="funnel-premium-envelopamentos" location="premium_hero" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#f06a24] px-6 py-3 font-bold text-white">Quero transformar meu ambiente <ArrowRight className="h-4 w-4" /></FunnelCTAButton><a href="#servicos" className="inline-flex min-h-12 items-center rounded-full border border-[#9db5cb] px-6 py-3 font-semibold text-[#0a2b5e]">Ver serviços</a></div><div className="mt-7 flex flex-wrap gap-4 text-sm font-semibold text-[#46617c]"><span><Check className="mr-1 inline h-4 w-4 text-[#10a8d8]" />Sem barulho e sem sujeira</span><span><Check className="mr-1 inline h-4 w-4 text-[#10a8d8]" />Pronto no mesmo dia</span></div></div><PortfolioImage src="/images/premium-envelopamentos/hero.png" alt="Aplicação de envelopamento em geladeira pela Premium Envelopamentos" priority width={1024} height={1024} className="w-full rounded-[2rem] object-cover shadow-2xl shadow-[#0a2b5e]/20" /></section>
      <section id="servicos" className="bg-[#0a2b5e] px-5 py-20 text-white lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#49d6f3]">Soluções sob medida</p><h2 className="mt-3 max-w-2xl text-4xl font-black">Uma nova superfície para cada ideia.</h2><div className="mt-10 grid gap-5 md:grid-cols-2">{services.map(([title, text], index) => <article key={title} className="rounded-[1.6rem] border border-white/15 bg-white/10 p-6"><span className="text-sm font-bold text-[#f6a05b]">0{index + 1}</span><h3 className="mt-8 text-2xl font-black">{title}</h3><p className="mt-3 leading-7 text-white/75">{text}</p></article>)}</div></div></section>
      <section id="galeria" className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-6xl"><div className="flex items-end justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f06a24]">Acabamento que aparece</p><h2 className="mt-3 text-4xl font-black">Veja possibilidades para o seu espaço.</h2></div><Sparkles className="h-10 w-10 text-[#10a8d8]" /></div><div className="mt-10 grid gap-5 md:grid-cols-2"><figure className="overflow-hidden rounded-[1.6rem] bg-white shadow-lg"><PortfolioImage src="/images/premium-envelopamentos/galeria-oficina.png" alt="Plotagem de móveis em oficina limpa e moderna" width={1536} height={1024} className="aspect-[3/2] w-full object-cover" /><figcaption className="p-4 text-sm font-semibold text-[#46617c]">Aplicação cuidadosa e visual renovado para móveis e eletros.</figcaption></figure><figure className="overflow-hidden rounded-[1.6rem] bg-white shadow-lg"><PortfolioImage src="/images/premium-envelopamentos/hero.png" alt="Envelopamento personalizado de geladeira" width={1024} height={1024} className="aspect-square w-full object-cover" /><figcaption className="p-4 text-sm font-semibold text-[#46617c]">Escolha cores e imagens para criar uma geladeira exclusiva.</figcaption></figure></div></div></section>
      <section id="instagram" className="bg-[#e1f4f8] px-5 py-16 lg:px-8"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-6 rounded-[2rem] bg-white p-8 shadow-sm md:flex-row md:items-center"><div><Instagram className="h-8 w-8 text-[#e1306c]" /><p className="mt-4 text-sm font-bold uppercase tracking-[.2em] text-[#0a2b5e]">Acompanhe no Instagram</p><h2 className="mt-2 text-3xl font-black">Mais ideias, aplicações e acabamentos.</h2><p className="mt-3 max-w-xl leading-7 text-[#46617c]">Conheça o trabalho da Premium Envelopamentos e veja referências reais no perfil oficial.</p></div><a href="https://www.instagram.com/premiumenvelopamentos" target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#e1306c] px-6 py-3 font-bold text-white">Abrir Instagram <ArrowRight className="h-4 w-4" /></a></div></section>
      <section className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-5xl rounded-[2rem] bg-[#f06a24] px-7 py-12 text-center text-white sm:px-12"><h2 className="text-4xl font-black">Pronto para renovar sem reforma?</h2><p className="mx-auto mt-4 max-w-2xl text-lg leading-8 text-white/85">Conte qual móvel ou eletro você quer transformar e receba orientação sobre as possibilidades.</p><FunnelCTAButton clientKey="premium-envelopamentos" companySlug="premium-envelopamentos" formSlug="funnel-premium-envelopamentos" location="premium_footer" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-full bg-[#071d41] px-7 py-3.5 font-bold text-white">Falar com a Premium <ArrowRight className="h-4 w-4" /></FunnelCTAButton></div></section>
    </main><footer className="bg-[#071d41] px-5 py-8 text-sm text-[#c8e4f0] lg:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p><strong className="text-white">Premium Envelopamentos</strong><br />Plotagem, envelopamento e comunicação visual em Curitiba e região.</p><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4" /></div></footer><PortfolioSocialProofPopup clientKey="premium-envelopamentos" eyebrow="Premium Envelopamentos" title="Uma nova superfície muda a sensação do ambiente." description="Conheça plotagem de móveis, envelopamento de geladeiras e soluções de comunicação visual." ctaLabel="Ver serviços" ctaHref="#servicos" delayMs={9000} className="border-[#10a8d8]/35 bg-[#071d41]/95 text-white" accentClassName="text-[#49d6f3]" /><PortfolioUpsellPopup pageName="portfolio-premium-envelopamentos" />
  </div>;
}
