import { motion } from "motion/react";
import { ArrowRight, Check, Clock3, Droplets, Snowflake, Wrench } from "lucide-react";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";

const quiz = { services: ["Recarga de gás", "Troca de motor", "Troca de sensor", "Manutenção preventiva", "Manutenção corretiva", "Ainda não sei — preciso de diagnóstico"], experienceOptions: ["Geladeira não está gelando", "Freezer com problema", "Ruído ou vazamento", "Quero prevenir uma falha"], periodOptions: ["Curitiba", "Região Metropolitana", "Vou confirmar o endereço"], timingOptions: ["Atendimento o quanto antes", "Nos próximos dias", "Orçamento preventivo"], proposalKind: "service" as const, stepTitles: { service: "O que aconteceu com seu equipamento?", experience: "Qual é o sintoma principal?", period: "Onde será o atendimento?", timing: "Quando você precisa?", note: "Conte mais detalhes" }, notePlaceholder: "Ex.: marca, modelo, quando começou e se o aparelho liga normalmente." };

function CTA({ children }: { children: React.ReactNode }) { return <PortfolioCTAQuiz clientKey="refrigeracao-maresia" studioName="Refrigeração Maresia" recipientName="Refrigeração Maresia" theme="navy" mode="proposal" quizConfig={quiz} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#0b2854] px-6 py-3.5 font-bold text-white shadow-lg shadow-[#0b2854]/20 transition hover:-translate-y-1 hover:bg-[#123b76] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#35a947]">{children}</PortfolioCTAQuiz>; }

const services = [["Conserto de geladeiras", "Diagnóstico e reparo para equipamentos que pararam de gelar."], ["Restauração e manutenção", "Cuidado técnico para devolver desempenho e conservação ao aparelho."], ["Peças e componentes", "Reposição com peças originais conforme a necessidade do equipamento."], ["Atendimento em toda a região", "Orientação e serviço para geladeiras e freezers de diferentes marcas."]];

export function RefrigeracaoMaresiaPage() {
 return <div className="min-h-dvh bg-[#f8fbfc] text-[#10284d]">
  <header className="sticky top-0 z-20 border-b border-[#dce8e8] bg-[#f8fbfc]/90 px-5 py-4 backdrop-blur lg:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><a href="#inicio" className="flex items-center gap-3 font-display text-lg font-bold"><img src="/images/refrigeracao-maresia/logo.png" alt="Refrigeração Maresia" width={1536} height={1024} loading="eager" decoding="async" fetchPriority="high" className="h-12 w-auto max-w-[14rem] object-contain" /></a><nav className="hidden gap-6 text-sm font-semibold md:flex"><a href="#servicos">Serviços</a><a href="#diferenciais">Diferenciais</a><a href="#atendimento">Atendimento</a></nav><CTA>Solicitar orçamento <ArrowRight className="h-4 w-4" /></CTA></div></header>
  <main>
   <section id="inicio" className="relative overflow-hidden px-5 py-14 lg:px-8 lg:py-24"><div className="pointer-events-none absolute -right-28 -top-28 h-80 w-80 rounded-full bg-[#8fdc9b]/25 blur-3xl" /><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[.9fr_1.1fr]"><div className="relative"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#12962a]">Geladeiras · freezers · manutenção</p><h1 className="mt-5 font-display text-5xl font-bold leading-[.98] sm:text-7xl">Geladeira parou de gelar?</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#536987]">A Refrigeração Maresia oferece solução no WhatsApp, com peças originais, garantia de serviço e atendimento em toda a região.</p><div className="mt-8 flex flex-wrap gap-3"><CTA>Chamar para diagnóstico <ArrowRight className="h-4 w-4" /></CTA><a href="#servicos" className="inline-flex min-h-12 items-center rounded-full border border-[#8db4b8] px-6 py-3.5 font-semibold text-[#0b2854]">Ver serviços</a></div><div className="mt-8 flex flex-wrap gap-4 text-sm font-semibold text-[#536987]"><span><Check className="mr-1 inline h-4 w-4 text-[#12962a]" />Peças originais</span><span><Clock3 className="mr-1 inline h-4 w-4 text-[#12962a]" />Resposta rápida no Zap</span></div></div><motion.div initial={{ opacity: 0, y: 20, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: .65 }} className="relative"><div className="absolute -inset-3 rounded-[2rem] bg-[#65c874]/25 blur-xl" /><PortfolioImage src="/images/refrigeracao-maresia/hero.png" alt="Refrigeração Maresia: solução para geladeiras que pararam de gelar" priority width={720} height={1000} className="relative w-full rounded-[2rem] object-cover shadow-2xl" /></motion.div></div></section>
   <section id="servicos" className="bg-[#0b2854] px-5 py-20 text-white lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#55c566]">Nossos serviços</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-bold">Diagnóstico preciso para devolver o frio à sua rotina.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map(([title, text], i) => <motion.article key={title} whileHover={{ y: -6 }} transition={{ duration: .2 }} className="rounded-3xl border border-white/15 bg-white/10 p-6"><span className="text-sm font-bold text-[#55c566]">0{i + 1}</span><Wrench className="mt-8 h-7 w-7 text-[#55c566]" /><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#d9e7f0]">{text}</p></motion.article>)}</div><div className="mt-10 flex flex-wrap items-center gap-4 rounded-2xl border border-[#55c566]/35 bg-[#123b76] p-5"><Snowflake className="h-8 w-8 text-[#55c566]" /><p><strong>Restaurando o gelo, trazendo a paz... pelo Zap!</strong> Solicite seu orçamento para o equipamento.</p></div></div></section>
   <section id="diferenciais" className="px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#12962a]">Por que escolher a Maresia?</p><h2 className="mt-3 font-display text-4xl font-bold">Mais economia, durabilidade e tranquilidade.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-3xl bg-white p-6 shadow-sm"><Droplets className="h-7 w-7 text-[#12962a]" /><h3 className="mt-6 text-xl font-bold">Qualidade garantida</h3><p className="mt-2 text-sm leading-6 text-[#536987]">Manutenção com atenção aos detalhes e orientação clara.</p></div><div className="rounded-3xl bg-[#e7f5e9] p-6"><Snowflake className="h-7 w-7 text-[#0b2854]" /><h3 className="mt-6 text-xl font-bold">Todas as marcas</h3><p className="mt-2 text-sm leading-6 text-[#536987]">Atendimento para geladeiras e freezers de diferentes fabricantes.</p></div></div></div><div id="atendimento" className="rounded-[2rem] bg-[#e7f5e9] p-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#12962a]">Curitiba e região</p><h3 className="mt-3 text-3xl font-bold">Seu equipamento merece voltar a funcionar bem.</h3><p className="mt-4 leading-7 text-[#536987]">Conte o problema, a marca e o melhor momento. A equipe organiza o próximo passo pelo WhatsApp.</p><div className="mt-7"><CTA>Solicitar meu orçamento <ArrowRight className="h-4 w-4" /></CTA></div></div></div></section>
  </main>
  <footer className="bg-[#071b3b] px-5 py-8 text-sm text-[#c7d6e8] lg:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-white">Refrigeração <span className="text-[#55c566]">Maresia</span></p><p className="mt-1">Manutenção de geladeiras e freezers em Curitiba e Região Metropolitana.</p></div><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4 hover:text-[#55c566]" /></div></footer>
  <PortfolioSocialProofPopup clientKey="refrigeracao-maresia" eyebrow="Refrigeração Maresia" title="Atendimento rápido para o seu equipamento voltar a gelar." description="Conte o sintoma e receba uma orientação para o próximo passo." ctaLabel="Ver serviços" ctaHref="#servicos" delayMs={9000} className="border-[#55c566]/35 bg-[#0b2854]/95 text-white" accentClassName="text-[#55c566]" />
  <PortfolioUpsellPopup pageName="portfolio-refrigeracao-maresia" />
 </div>;
}
