import { ArrowRight, Check, Gift, Heart, Sparkles, Truck } from "lucide-react";
import type { ReactNode } from "react";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";

const quiz = {
  services: ["Quero uma cesta pronta", "Quero montar um presente", "Caneca ou xícara personalizada", "Cosméticos e acessórios", "Quero ajuda para escolher"],
  experienceOptions: ["É para aniversário", "É para uma data especial", "É para presentear alguém", "Quero deixar disponível para retirada"],
  periodOptions: ["Preciso para hoje", "Para os próximos dias", "Estou planejando com antecedência", "Quero consultar a entrega"],
  timingOptions: ["Quero falar sobre disponibilidade", "Quero montar meu pedido", "Quero personalizar uma caneca", "Quero conhecer a loja"],
  proposalKind: "service" as const,
  stepTitles: { service: "O que você quer presentear?", experience: "Qual é a ocasião?", period: "Quando você precisa?", timing: "Como podemos ajudar?", note: "Conte os detalhes do presente" },
  notePlaceholder: "Ex.: para quem é, cores, frase, tema, data e faixa de valor.",
};

function CTA({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <PortfolioCTAQuiz clientKey="sos-presentes-cosmeticos" studioName="SOS Presentes & Cosméticos" recipientName="SOS Presentes & Cosméticos" theme="pink" mode="proposal" quizConfig={quiz} className={`inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#d72f70] px-6 py-3 font-bold text-white shadow-lg shadow-[#d72f70]/25 transition hover:-translate-y-0.5 hover:bg-[#ba205b] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#d72f70] ${className}`}>{children}</PortfolioCTAQuiz>;
}

const products = [
  { title: "Cestas para surpreender", text: "Opções prontas e montadas para aniversários, datas especiais e gestos de carinho.", image: "/images/sos-presentes-cosmeticos/cesta-lilas.png" },
  { title: "Mini cafés e presentes", text: "Combinações com canecas, cookies, bebidas, chocolates e uma apresentação especial.", image: "/images/sos-presentes-cosmeticos/cestas-feliz-aniversario.png" },
  { title: "Canecas personalizadas", text: "Sua imagem, frase ou lembrança em uma peça para presentear com significado.", image: "/images/sos-presentes-cosmeticos/canecas-combo.png" },
];

export function SosPresentesCosmeticosPage() {
  return <div className="min-h-dvh bg-[#fff8fb] text-[#3a1830]">
    <header className="sticky top-0 z-20 border-b border-[#f7d3e3] bg-[#fff8fb]/90 px-5 py-4 backdrop-blur lg:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><a href="#inicio" className="font-display text-lg font-black tracking-tight text-[#d72f70]">SOS <span className="text-[#572039]">Presentes</span></a><nav className="hidden gap-5 text-sm font-semibold md:flex"><a href="#presentes">Presentes</a><a href="#personalizados">Personalizados</a><a href="#papelaria">Papelaria</a></nav><CTA>Montar meu presente <ArrowRight className="h-4 w-4" /></CTA></div></header>
    <main>
      <section id="inicio" className="relative overflow-hidden px-5 py-14 lg:px-8 lg:py-24"><div className="pointer-events-none absolute -left-28 -top-24 h-80 w-80 rounded-full bg-[#f7b4d1]/35 blur-3xl" /><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[.95fr_1.05fr]"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#d72f70]">Cestas · presentes · cosméticos · personalizados</p><h1 className="mt-5 max-w-xl font-display text-5xl font-black leading-[.96] sm:text-7xl">Presentes que fazem alguém se sentir especial.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#6e4159]">Na SOS Presentes & Cosméticos você encontra cestas à pronta entrega, opções personalizadas e muitos detalhes para transformar uma data comum em uma lembrança.</p><div className="mt-8 flex flex-wrap gap-3"><CTA>Encontrar um presente <Gift className="h-4 w-4" /></CTA><a href="#presentes" className="inline-flex min-h-12 items-center rounded-full border border-[#e8a8c5] px-6 py-3 font-semibold text-[#7c3157]">Ver opções</a></div><div className="mt-8 flex flex-wrap gap-4 text-sm font-semibold text-[#6e4159]"><span><Check className="mr-1 inline h-4 w-4 text-[#d72f70]" />Pronta entrega</span><span><Truck className="mr-1 inline h-4 w-4 text-[#d72f70]" />Entrega sob consulta</span></div></div><PortfolioImage src="/images/sos-presentes-cosmeticos/cesta-lilas.png" alt="Cesta de presente da SOS Presentes e Cosméticos" priority width={960} height={1120} className="mx-auto max-h-[620px] w-full max-w-xl rounded-[2rem] object-cover shadow-2xl shadow-[#d72f70]/15" /></div></section>
      <section id="presentes" className="bg-[#572039] px-5 py-20 text-white lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f8b7d5]">Escolha pelo momento</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-black">Uma vitrine para celebrar, agradecer e encantar.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{products.map((product) => <article key={product.title} className="overflow-hidden rounded-[1.7rem] border border-white/15 bg-white/10"><PortfolioImage src={product.image} alt={product.title} width={720} height={720} className="h-64 w-full object-cover" /><div className="p-6"><Gift className="h-6 w-6 text-[#ffb8d6]" /><h3 className="mt-5 text-xl font-bold">{product.title}</h3><p className="mt-3 text-sm leading-6 text-white/75">{product.text}</p></div></article>)}</div></div></section>
      <section id="personalizados" className="px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2 lg:items-center"><PortfolioImage src="/images/sos-presentes-cosmeticos/canecas-combo.png" alt="Canecas personalizadas da SOS Presentes e Cosméticos" width={850} height={1040} className="h-[470px] w-full rounded-[2rem] object-cover" /><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#d72f70]">Feito com a sua ideia</p><h2 className="mt-3 font-display text-4xl font-black">Uma caneca pode guardar uma história inteira.</h2><p className="mt-5 text-lg leading-8 text-[#6e4159]">Canecas e xícaras personalizadas permitem usar frases, imagens e referências de quem vai receber. A embalagem de presente completa a experiência.</p><ul className="mt-7 grid gap-3 text-sm font-semibold text-[#572039]"><li><Check className="mr-2 inline h-4 w-4 text-[#d72f70]" />Arte baseada na imagem ou ideia enviada</li><li><Check className="mr-2 inline h-4 w-4 text-[#d72f70]" />Opções para presentear em datas especiais</li><li><Check className="mr-2 inline h-4 w-4 text-[#d72f70]" />Disponibilidade e prazo confirmados no atendimento</li></ul><div className="mt-8"><CTA>Quero personalizar <Heart className="h-4 w-4" /></CTA></div></div></div></section>
      <section id="papelaria" className="bg-[#fdebf3] px-5 py-20 lg:px-8"><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#d72f70]">Amostra de papelaria</p><h2 className="mt-3 font-display text-4xl font-black">A identidade que pode acompanhar cada presente.</h2><p className="mt-4 text-lg leading-8 text-[#6e4159]">Estudo conceitual de cartão e panfleto: uma amostra visual da presença gráfica que pode ser desenvolvida para a marca. Não representa material impresso já produzido.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2"><article className="rounded-[1.8rem] bg-[#d72f70] p-8 text-white shadow-xl shadow-[#d72f70]/15"><Sparkles className="h-8 w-8" /><p className="mt-12 text-sm font-bold uppercase tracking-[.18em] text-white/75">Cartão de visitas · estudo visual</p><h3 className="mt-3 font-display text-4xl font-black">SOS Presentes</h3><p className="mt-4 max-w-sm text-white/85">Presentes que encantam. Cestas, cosméticos e personalizados para cada ocasião.</p></article><article className="rounded-[1.8rem] border-2 border-dashed border-[#e59abb] bg-white p-8"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#d72f70]">Panfleto · estudo visual</p><h3 className="mt-8 font-display text-4xl font-black text-[#572039]">Um presente pronto para marcar o dia.</h3><p className="mt-4 max-w-sm text-[#6e4159]">Cestas e opções personalizadas, com atendimento para escolher a melhor surpresa.</p><div className="mt-8 inline-flex rounded-full bg-[#fdebf3] px-4 py-2 text-sm font-bold text-[#a9275d]">Conheça a coleção</div></article></div></div></section>
      <section className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-5xl rounded-[2rem] bg-[#d72f70] px-7 py-12 text-center text-white shadow-xl shadow-[#d72f70]/20"><Heart className="mx-auto h-9 w-9" /><h2 className="mt-5 font-display text-4xl font-black">Quer encontrar o presente certo?</h2><p className="mx-auto mt-4 max-w-2xl text-lg leading-8 text-white/85">Conte para quem é, qual é a ocasião e quando precisa. A SOS ajuda a transformar sua ideia em uma surpresa especial.</p><div className="mt-8"><CTA className="bg-white text-[#bd245f] hover:bg-[#fff4f8]">Começar meu pedido <ArrowRight className="h-4 w-4" /></CTA></div></div></section>
    </main>
    <footer className="bg-[#3a1830] px-5 py-8 text-sm text-[#f9d8e7] lg:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p><strong className="text-white">SOS Presentes & Cosméticos</strong><br />Cestas, cosméticos e personalizados em São José dos Pinhais.</p><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4" /></div></footer>
    <PortfolioSocialProofPopup clientKey="sos-presentes-cosmeticos" eyebrow="SOS Presentes & Cosméticos" title="Uma surpresa especial começa com uma boa ideia." description="Veja cestas, presentes e opções personalizadas para a sua ocasião." ctaLabel="Ver presentes" ctaHref="#presentes" delayMs={9000} className="border-[#d72f70]/35 bg-[#572039]/95 text-white" accentClassName="text-[#ffb8d6]" /><PortfolioUpsellPopup pageName="portfolio-sos-presentes-cosmeticos" />
  </div>;
}
