import { ManagedText } from "@/components/portfolio/ManagedText";
import { motion } from "motion/react";
import { ArrowRight, Calendar, Check, Eye, Heart, Sparkles, Star } from "lucide-react";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";

const quiz = {
  services: ["Mega Brasileiro · R$ 130", "Mega Egípcio · R$ 130", "Mega Fox Eyes · R$ 130", "Fio a Fio · R$ 100", "Quero ajuda para escolher"],
  experienceOptions: ["Primeira aplicação", "Já uso extensão de cílios", "Manutenção", "Quero mudar o estilo"],
  periodOptions: ["Tenho flexibilidade", "Preciso de um horário específico", "Quero saber os próximos horários"],
  timingOptions: ["O quanto antes", "Nos próximos 15 dias", "Estou planejando"],
  proposalKind: "service" as const,
  stepTitles: { service: "Qual olhar você quer criar?", experience: "Como estão seus cílios hoje?", period: "Que tipo de horário você procura?", timing: "Quando gostaria de agendar?", note: "Conte o que você imaginou" },
  notePlaceholder: "Ex.: prefiro um efeito delicado, tenho uma referência ou preciso de manutenção.",
};

function CTA({ children }: { children: React.ReactNode }) {
  return <PortfolioCTAQuiz clientKey="studio-de-cilios" studioName="Studio de Cílios" recipientName="Studio de Cílios" theme="pink" mode="proposal" quizConfig={quiz} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#7e3f4e] px-6 py-3.5 font-bold text-white shadow-lg shadow-[#7e3f4e]/20 transition hover:-translate-y-1 hover:bg-[#66303f] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#dca7a8]">{children}</PortfolioCTAQuiz>;
}

const looks = [
  ["Mega Brasileiro", "R$ 130", "Volume marcante e curvatura elegante para destacar o olhar."],
  ["Mega Egípcio", "R$ 130", "Fios alinhados e intensos para um acabamento sofisticado."],
  ["Mega Fox Eyes", "R$ 130", "Efeito alongado no canto externo para um olhar felino."],
  ["Fio a Fio", "R$ 100", "Leveza e naturalidade para realçar sua beleza todos os dias."],
];

export function StudioDeCiliosPage() {
  return <div className="min-h-dvh bg-[#fff9f7] text-[#3a2630]">
    <header className="sticky top-0 z-20 border-b border-[#f0dfe0] bg-[#fff9f7]/90 px-5 py-4 backdrop-blur lg:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><a href="#inicio" className="flex items-center gap-3 font-display text-lg font-bold"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#7e3f4e] text-[#f7d5ce]"><Eye className="h-5 w-5" /></span><span>Studio <span className="text-[#a45d68]">de Cílios</span></span></a><nav className="hidden gap-6 text-sm font-semibold md:flex"><a href="#estilos" className="hover:text-[#a45d68]">Estilos</a><a href="#galeria" className="hover:text-[#a45d68]">Inspirações</a><a href="#cuidado" className="hover:text-[#a45d68]">Cuidado</a></nav><CTA>Agendar horário <ArrowRight className="h-4 w-4" /></CTA></div></header>
    <main>
      <section id="inicio" className="relative overflow-hidden px-5 py-14 lg:px-8 lg:py-24"><div className="pointer-events-none absolute -left-24 -top-24 h-72 w-72 rounded-full bg-[#f3c8c1]/35 blur-3xl" /><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[.95fr_1.05fr]"><div className="relative"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a45d68]">Extensão de cílios · olhar personalizado</p><h1 className="mt-5 font-display text-5xl font-bold leading-[.98] sm:text-7xl">
            <ManagedText field="heroHeadline" fallback={"Seu olhar, sua assinatura."} />
          </h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#765963]">
            <ManagedText field="heroSubheadline" fallback={"Escolha o efeito que combina com voc\u00ea e viva a praticidade de acordar pronta. Aplica\u00e7\u00f5es pensadas para valorizar seus tra\u00e7os com delicadeza e presen\u00e7a."} />
          </p><div className="mt-8 flex flex-wrap gap-3"><CTA>Agendar meu horário <ArrowRight className="h-4 w-4" /></CTA><a href="#estilos" className="inline-flex min-h-12 items-center rounded-full border border-[#cfa4a9] px-6 py-3.5 font-semibold text-[#7e3f4e]">Conhecer estilos</a></div><div className="mt-8 flex flex-wrap gap-4 text-sm font-semibold text-[#765963]"><span><Check className="mr-1 inline h-4 w-4 text-[#b56b76]" />Horários sob agendamento</span><span><Sparkles className="mr-1 inline h-4 w-4 text-[#b56b76]" />Acabamento personalizado</span></div></div><motion.div initial={{ opacity: 0, y: 20, rotate: 1 }} animate={{ opacity: 1, y: 0, rotate: 0 }} transition={{ duration: .65 }} className="relative"><div className="absolute -inset-3 rounded-[2rem] bg-[#e9b7b2]/30 blur-xl" /><PortfolioImage src="/images/studio-de-cilios/portfolio-1.webp" alt="Aplicação Mega Brasileiro e Mega Egípcio no Studio de Cílios" priority width={900} height={1600} className="relative w-full rounded-[2rem] object-cover shadow-2xl"
            managedField="heroImageUrl"
          /></motion.div></div></section>
      <section id="estilos" className="bg-[#7e3f4e] px-5 py-20 text-white lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f4c9c4]">Escolha o seu efeito</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-bold">Quatro estilos para você encontrar o seu olhar.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{looks.map(([name, price, detail], index) => <motion.article key={name} whileHover={{ y: -7 }} transition={{ duration: .2 }} className="rounded-3xl border border-white/15 bg-white/10 p-6"><span className="text-sm font-bold text-[#f4c9c4]">0{index + 1}</span><h3 className="mt-8 text-xl font-bold">{name}</h3><p className="mt-3 text-3xl font-black text-[#f4c9c4]">{price}</p><p className="mt-4 text-sm leading-6 text-[#f9e9e8]">{detail}</p><a href="#agendar" className="mt-6 inline-flex min-h-11 items-center gap-2 font-bold text-[#f4c9c4] hover:underline">Quero conhecer <ArrowRight className="h-4 w-4" /></a></motion.article>)}</div></div></section>
      <section id="galeria" className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a45d68]">Inspirações reais</p><h2 className="mt-3 font-display text-4xl font-bold">Do natural ao marcante: escolha a sua vibe.</h2><div className="mt-10 grid gap-5 md:grid-cols-2"><motion.figure whileHover={{ y: -5 }} className="overflow-hidden rounded-[2rem] border border-[#f0dfe0] bg-white shadow-sm"><PortfolioImage src="/images/studio-de-cilios/portfolio-2.webp" alt="Aplicações Fox Eyes e Fio a Fio em diferentes olhos" width={900} height={1600} className="h-full max-h-[720px] w-full object-cover" /><figcaption className="p-5 font-semibold">Referências para conversar sobre curvatura, volume e acabamento.</figcaption></motion.figure><div className="grid gap-5 sm:grid-cols-2"><div className="rounded-3xl bg-[#f8dfdc] p-7"><Heart className="h-8 w-8 text-[#7e3f4e]" /><h3 className="mt-8 text-2xl font-bold">Beleza que combina</h3><p className="mt-3 leading-7 text-[#765963]">O efeito é escolhido respeitando seu estilo e o resultado que você deseja.</p></div><div className="rounded-3xl bg-[#f3e9e6] p-7"><Star className="h-8 w-8 text-[#a45d68]" /><h3 className="mt-8 text-2xl font-bold">Detalhes importam</h3><p className="mt-3 leading-7 text-[#765963]">Uma conversa cuidadosa antes da aplicação deixa tudo mais confortável.</p></div></div></div></div></section>
      <section id="cuidado" className="bg-[#f6ece9] px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a45d68]">Experiência tranquila</p><h2 className="mt-3 font-display text-4xl font-bold">Seu momento de autocuidado começa antes do procedimento.</h2><div className="mt-8 space-y-5">{[["01", "Conversa inicial", "Entendemos o efeito, a ocasião e a rotina dos seus cílios."], ["02", "Aplicação personalizada", "A técnica é escolhida para entregar conforto e o resultado combinado."], ["03", "Orientação de cuidado", "Você sai sabendo como preservar a beleza e a durabilidade do olhar."]].map(([n, title, text]) => <div key={n} className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#7e3f4e] font-bold text-white">{n}</span><div><h3 className="font-bold">{title}</h3><p className="mt-1 text-sm leading-6 text-[#765963]">{text}</p></div></div>)}</div></div><div id="agendar" className="rounded-[2rem] bg-white p-8 shadow-xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a45d68]">Vamos conversar?</p><h3 className="mt-3 text-3xl font-bold">Encontre o efeito perfeito para você.</h3><p className="mt-3 leading-7 text-[#765963]">Responda algumas perguntas rápidas e solicite seu horário com o Studio de Cílios.</p><div className="mt-7"><CTA>Solicitar meu horário <ArrowRight className="h-4 w-4" /></CTA></div><p className="mt-5 text-xs text-[#765963]"><Calendar className="mr-1 inline h-4 w-4" />Agenda mediante disponibilidade.</p></div></div></section>
    </main>
    <footer className="bg-[#351f29] px-5 py-8 text-sm text-[#e8cfd0] lg:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-white">Studio <span className="text-[#f4c9c4]">de Cílios</span></p><p className="mt-1">Extensão de cílios com estilo e cuidado.</p></div><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4 hover:text-[#f4c9c4]" /></div></footer>
    <PortfolioSocialProofPopup clientKey="studio-de-cilios" eyebrow="Studio de Cílios" title="Seu olhar pode ganhar a presença que você imaginou." description="Escolha um estilo, conte sua preferência e encontre um horário para cuidar de você." ctaLabel="Conhecer estilos" ctaHref="#estilos" delayMs={9000} className="border-[#e9b7b2]/40 bg-[#7e3f4e]/95 text-white" accentClassName="text-[#f4c9c4]" />
    <PortfolioUpsellPopup pageName="portfolio-studio-de-cilios" />
  </div>;
}
