import { ManagedText } from "@/components/portfolio/ManagedText";
import { motion } from "motion/react";
import { ArrowRight, CakeSlice, Check, Instagram, MapPin, Sparkles, Truck } from "lucide-react";
import { PortfolioCTAQuiz } from "@/components/site/BeautyBookingQuiz";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioSocialProofPopup } from "@/components/portfolio/PortfolioSocialProofPopup";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";

const quiz = { services: ["Kit Festa para 10 pessoas · R$ 259,90", "Kit Festa para 20 pessoas · R$ 499,90", "Kit Festa para 50 pessoas · R$ 1.249,90", "Kit Festa para 70 pessoas · R$ 1.749,90", "Kit Festa para 100 pessoas · R$ 2.499,90", "Bolos, doces ou salgados avulsos"], experienceOptions: ["Aniversário", "Confraternização", "Evento corporativo", "Casamento ou celebração"], periodOptions: ["Campo Comprido", "Curitiba e região", "Vou confirmar o endereço"], timingOptions: ["Preciso para breve", "Estou planejando", "Quero consultar disponibilidade"], proposalKind: "service" as const, stepTitles: { service: "O que você quer encomendar?", experience: "Qual é a ocasião?", period: "Onde será a entrega?", timing: "Quando será a sua festa?", note: "Conte os detalhes do pedido" }, notePlaceholder: "Ex.: tema do bolo, quantidade de convidados, sabores e preferência de entrega." };
function CTA({ children }: { children: React.ReactNode }) { return <PortfolioCTAQuiz clientKey="vila-da-capivara" studioName="Vila da Capivara" recipientName="Vila da Capivara" theme="gold" mode="proposal" quizConfig={quiz} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#f5b800] px-6 py-3.5 font-bold text-[#201308] shadow-lg shadow-[#f5b800]/20 transition hover:-translate-y-1 hover:bg-[#ffc928] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f5b800]">{children}</PortfolioCTAQuiz>; }
const kits = [["Kit Festa · 10 pessoas", "R$ 259,90", "100 salgados · 50 brigadeiros · bolo 1,5 kg"], ["Kit Festa · 20 pessoas", "R$ 499,90", "200 salgados · 100 brigadeiros · bolo 3 kg"], ["Kit Festa · 50 pessoas", "R$ 1.249,90", "500 salgados · 250 brigadeiros · bolo 7,5 kg"], ["Kit Festa · 70 pessoas", "R$ 1.749,90", "700 salgados · 350 brigadeiros · bolo 10,5 kg"], ["Kit Festa · 100 pessoas", "R$ 2.499,90", "1.000 salgados · 500 brigadeiros · bolo 15 kg"]];
export function VilaDaCapivaraPage() { return <div className="min-h-dvh bg-[#fffaf0] text-[#2d1b0d]">
 <header className="sticky top-0 z-20 border-b border-[#5c360f] bg-[#110c08]/95 px-5 py-4 text-white backdrop-blur lg:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><a href="#inicio" className="flex items-center gap-3 font-display text-lg font-bold"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#f5b800] text-[#241205]"><CakeSlice className="h-5 w-5" /></span><span>Vila da <span className="text-[#f5b800]">Capivara</span></span></a><nav className="hidden gap-6 text-sm font-semibold md:flex"><a href="#kits">Kits Festa</a><a href="#sabores">Sabores</a><a href="#historia">Nossa essência</a></nav><CTA>Montar meu pedido <ArrowRight className="h-4 w-4" /></CTA></div></header>
 <main><section id="inicio" className="relative overflow-hidden bg-[#261507] px-5 py-14 text-white lg:px-8 lg:py-24"><div className="pointer-events-none absolute -right-24 -top-24 h-80 w-80 rounded-full bg-[#f5b800]/20 blur-3xl" /><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f5b800]">Confeitaria · doces · salgados · festas</p><h1 className="mt-5 font-display text-5xl font-bold leading-[.98] sm:text-7xl">
            <ManagedText field="heroHeadline" fallback={"Mais que sabores, criamos experi\u00eancias."} />
          </h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#f8e7c4]">
            <ManagedText field="heroSubheadline" fallback={"Bolos personalizados, brigadeiros gourmet, salgados fresquinhos e kits festa completos para celebrar em Campo Comprido e Curitiba."} />
          </p><div className="mt-8 flex flex-wrap gap-3"><CTA>Fazer meu orçamento <ArrowRight className="h-4 w-4" /></CTA><a href="#kits" className="inline-flex min-h-12 items-center rounded-full border border-[#d19b2a] px-6 py-3.5 font-semibold text-[#f8d36b]">Ver kits</a></div><div className="mt-8 flex flex-wrap gap-4 text-sm font-semibold text-[#f8e7c4]"><span><Check className="mr-1 inline h-4 w-4 text-[#f5b800]" />Produtos fresquinhos</span><span><MapPin className="mr-1 inline h-4 w-4 text-[#f5b800]" />Campo Comprido · Curitiba</span></div></div><motion.div initial={{ opacity: 0, y: 20, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: .65 }}><PortfolioImage src="/images/vila-da-capivara/capa.webp" alt="Bolos, brigadeiros e salgados da Vila da Capivara" priority width={1220} height={1024} className="w-full rounded-[2rem] object-cover shadow-2xl"
            managedField="heroImageUrl"
          /></motion.div></div></section>
 <section id="kits" className="bg-[#f5b800] px-5 py-20 lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#4a2905]">Festa completa, pronta para servir</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-bold text-[#1e1205]">Escolha o tamanho da sua celebração.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{kits.map(([name, price, detail], i) => <motion.article key={name} whileHover={{ y: -7 }} className="rounded-3xl border border-[#8a5c00]/30 bg-[#17100a] p-5 text-white"><span className="text-sm font-bold text-[#f5b800]">0{i + 1}</span><h3 className="mt-7 text-xl font-bold">{name}</h3><p className="mt-4 text-3xl font-black text-[#f5b800]">{price}</p><p className="mt-3 text-sm leading-6 text-[#f4e6c8]">{detail}</p><a href="#pedido" className="mt-5 inline-flex min-h-11 items-center gap-2 font-bold text-[#f5b800] hover:underline">Consultar <ArrowRight className="h-4 w-4" /></a></motion.article>)}</div><p className="mt-6 text-sm font-semibold text-[#4a2905]">Consulte a taxa de entrega e a disponibilidade da data.</p></div></section>
 <section id="sabores" className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a66c00]">Feito com carinho</p><h2 className="mt-3 font-display text-4xl font-bold">Um cardápio que abraça todos os momentos.</h2></div><a href="https://www.instagram.com/viladacapivaraoficial" target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#b88a32] px-5 font-semibold hover:bg-[#fff1c9]"><Instagram className="h-4 w-4" /> @viladacapivaraoficial</a></div><div className="mt-10 grid gap-5 md:grid-cols-2"><motion.figure whileHover={{ y: -5 }} className="overflow-hidden rounded-[2rem] border border-[#ead9b5] bg-white shadow-sm"><PortfolioImage src="/images/vila-da-capivara/editorial.webp" alt="Bolos, brigadeiros, salgados fritos e assados" width={1024} height={1536} className="h-full max-h-[720px] w-full object-cover" /><figcaption className="p-5 font-semibold">Receitas artesanais para encomendas de festas e eventos.</figcaption></motion.figure><div className="grid gap-5 sm:grid-cols-2"><div className="rounded-3xl bg-[#fff1c9] p-7"><Sparkles className="h-8 w-8 text-[#a66c00]" /><h3 className="mt-8 text-2xl font-bold">Bolos e doces</h3><p className="mt-3 leading-7 text-[#6e4c27]">Bolos personalizados, tradicionais e brigadeiros gourmet.</p></div><div className="rounded-3xl bg-[#f3e1c4] p-7"><Truck className="h-8 w-8 text-[#a66c00]" /><h3 className="mt-8 text-2xl font-bold">Salgados fresquinhos</h3><p className="mt-3 leading-7 text-[#6e4c27]">Fritos e assados para festas, revenda e reuniões.</p></div><div className="overflow-hidden rounded-3xl bg-[#261507] sm:col-span-2"><PortfolioImage src="/images/vila-da-capivara/kit-100.webp" alt="Kit Festa completo para 100 pessoas" width={1086} height={1536} className="h-80 w-full object-cover object-top" /></div></div></div></div></section>
 <section id="historia" className="bg-[#261507] px-5 py-20 text-white lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f5b800]">Para cada ocasião</p><h2 className="mt-3 font-display text-4xl font-bold">Aniversários, casamentos e encontros que pedem sabor.</h2><p className="mt-5 text-lg leading-8 text-[#f8e7c4]">A Vila da Capivara prepara encomendas para aniversários, chá revelação, festas infantis, confraternizações e eventos empresariais. Tudo feito com ingredientes selecionados e muito carinho.</p><div className="mt-7 flex flex-wrap gap-3 text-sm font-semibold text-[#f8e7c4]"><span>🎂 Bolos personalizados</span><span>🍫 Brigadeiros gourmet</span><span>🥟 Salgados fritos e assados</span></div></div><div id="pedido" className="rounded-[2rem] bg-[#f5b800] p-8 text-[#201308]"><p className="text-sm font-bold uppercase tracking-[.2em]">Faça sua encomenda</p><h3 className="mt-3 text-3xl font-bold">Vamos montar a festa ideal?</h3><p className="mt-4 leading-7">Conte o tamanho do evento, a data e os sabores que você deseja. A equipe retorna com as opções.</p><div className="mt-7"><CTA>Solicitar orçamento <ArrowRight className="h-4 w-4" /></CTA></div><a href="https://www.viladacapivara.com" target="_blank" rel="noreferrer" className="mt-5 inline-flex font-semibold underline underline-offset-4">Visitar viladacapivara.com</a></div></div></section></main>
 <footer className="bg-[#120b06] px-5 py-8 text-sm text-[#e9d6ae] lg:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-white">Vila da <span className="text-[#f5b800]">Capivara</span></p><p className="mt-1">Confeitaria, doces e salgados para festas em Curitiba.</p></div><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4 hover:text-[#f5b800]" /></div></footer><PortfolioSocialProofPopup clientKey="vila-da-capivara" eyebrow="Vila da Capivara" title="Sua festa merece um sabor inesquecível." description="Escolha um kit, conte a ocasião e receba uma orientação para sua encomenda." ctaLabel="Ver kits" ctaHref="#kits" delayMs={9000} className="border-[#f5b800]/40 bg-[#261507]/95 text-white" accentClassName="text-[#f5b800]" /><PortfolioUpsellPopup pageName="portfolio-vila-da-capivara" />
 </div>; }
