import { ArrowUpRight, MapPin, Route, UtensilsCrossed } from "lucide-react";
import { FunnelCTAButton } from "@/components/funnel/FunnelCTAButton";
import { MotionReveal, MotionScope } from "@/components/motion";
import { PortfolioHostCredit } from "@/components/portfolio/PortfolioHostCredit";
import { PortfolioImage } from "@/components/portfolio/PortfolioImage";
import { PortfolioUpsellPopup } from "@/components/site/PortfolioUpsellPopup";

const menuUrl = "https://menu.brendi.com.br/brutus-burguer-afonso-pena/";

export function YourBrutusBurguerPage() {
 return <div data-client-slug="your-brutus-burguer" className="min-h-dvh bg-[#10151b] text-[#fff5df] [--ember:#ed6a2c] [--gold:#f5b84b]">
  <header className="sticky top-0 z-30 border-b border-white/10 bg-[#10151b]/90 px-5 py-3 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><a href="#inicio"><PortfolioImage priority managedField="logoUrl" src="/images/your-brutus-burguer/logo.svg" alt="Your Brutus Burguer" width={220} height={60} className="h-11 w-auto" /></a><nav className="hidden gap-6 text-sm font-semibold text-[#f8dca5] md:flex"><a href="#cardapio">Cardápio</a><a href="#presenca">Presença</a></nav><a href={menuUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#ed6a2c] px-4 text-sm font-black text-white transition-colors hover:bg-[#ff7a3d] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f5b84b]">Abrir cardápio <ArrowUpRight className="h-4 w-4" /></a></div></header>
  <MotionScope intensity="EXPRESSIVE"><main id="inicio"><section className="relative isolate overflow-hidden border-b border-white/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_82%_42%,rgba(237,106,44,.28),transparent_29%),linear-gradient(110deg,#10151b_38%,rgba(16,21,27,.35))]"/><div className="relative mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-[.8fr_1.2fr] lg:items-center lg:py-24"><div><p className="inline-flex items-center gap-2 rounded-full border border-[--gold]/50 px-3 py-1 text-xs font-bold uppercase tracking-[.18em] text-[--gold]"><Route className="h-3.5 w-3.5"/> Centro · São José dos Pinhais</p><MotionReveal variant="up"><h1 className="mt-6 max-w-xl font-serif text-5xl font-black leading-[.92] tracking-tight sm:text-7xl">A rota certa para um <span className="text-[--gold]">burger encorpado.</span></h1></MotionReveal><p className="mt-6 max-w-lg text-lg leading-8 text-[#d8c9ae]">Hamburgueria artesanal em ares caseiros, com sandubas encorpados, pães especiais e guarnições da casa.</p><div className="mt-8 flex flex-wrap gap-3"><a href={menuUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#f5b84b] px-6 py-3 font-black text-[#1a1713] transition-colors hover:bg-[#ffd076] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white">Ver cardápio oficial <ArrowUpRight className="h-4 w-4"/></a><FunnelCTAButton clientKey="your_brutus_burguer" companySlug="your-brutus-burguer" formSlug="funnel-your-brutus-burguer" location="brutus_hero" className="inline-flex min-h-12 rounded-full border border-white/25 px-6 py-3 font-bold text-white">Montar meu pedido</FunnelCTAButton></div><p className="mt-5 flex items-center gap-2 text-sm text-[#c8b99e]"><MapPin className="h-4 w-4 text-[--ember]"/> R. Colombo, 1981 · Centro · São José dos Pinhais</p></div><MotionReveal variant="scale" className="relative"><PortfolioImage priority managedField="heroImageUrl" src="/images/your-brutus-burguer/hero-og.png" alt="Arte de marca com hambúrguer artesanal para Your Brutus Burguer" width={1200} height={630} className="aspect-[1.28] w-full rounded-[2.5rem] object-cover shadow-2xl shadow-black/40"/><span className="absolute bottom-4 left-4 rounded-full bg-[#10151b]/85 px-3 py-1 text-xs font-semibold text-[#f8dca5]">Arte de presença digital · não é foto documental</span></MotionReveal></div></section>
  <section id="cardapio" className="mx-auto max-w-7xl px-5 py-20"><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[--ember]">Cardápio oficial</p><h2 className="mt-4 font-serif text-4xl font-black leading-tight">Escolhas que já nascem com personalidade.</h2><p className="mt-5 leading-7 text-[#c8b99e]">O cardápio público mostra burgers de costela, smash, combos e porções. A disponibilidade e os valores são consultados diretamente no canal oficial.</p><a href={menuUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 font-bold text-[--gold] underline underline-offset-4">Consultar opções e condições <ArrowUpRight className="h-4 w-4"/></a></div><div className="grid gap-px overflow-hidden rounded-[2rem] border border-white/10 bg-white/10 sm:grid-cols-3">{[["Smash e clássicos","Uma porta de entrada para escolher seu burger no ritmo da fome."],["Costela e especiais","Combinações da casa destacadas no cardápio oficial."],["Porções e bebidas","Acompanhe seu pedido com as opções disponíveis no dia."]].map(([title,copy])=><article key={title} className="bg-[#171d25] p-7"><UtensilsCrossed className="h-6 w-6 text-[--gold]"/><h3 className="mt-6 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-[#c8b99e]">{copy}</p></article>)}</div></div></section>
  <section className="bg-[#f5b84b] px-5 py-20 text-[#181614]"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-sm font-black uppercase tracking-[.18em] text-[#a43f1e]">Jeito Brutus</p><h2 className="mt-4 max-w-3xl font-serif text-5xl font-black leading-[.95]">Pedido bom não pede adivinhação.</h2></div><ol className="grid gap-4 text-lg font-bold"><li className="border-t border-[#181614]/20 py-4">01 · Abra o cardápio oficial.</li><li className="border-t border-[#181614]/20 py-4">02 · Escolha o que combina com a sua fome.</li><li className="border-y border-[#181614]/20 py-4">03 · Use o atendimento para organizar o próximo passo.</li></ol></div></section>
  <section id="presenca" className="mx-auto max-w-7xl px-5 py-20"><p className="text-sm font-bold uppercase tracking-[.2em] text-[--ember]">Kit de presença</p><h2 className="mt-3 font-serif text-4xl font-black">A marca também ocupa a mesa.</h2><p className="mt-3 max-w-2xl text-[#c8b99e]">Estudos de cartão e panfleto criados para esta identidade. Conceitos sujeitos à aprovação do negócio.</p><div className="mt-9 grid gap-6 lg:grid-cols-2"><figure className="overflow-hidden rounded-[2rem] border border-white/10 bg-[#171d25]"><PortfolioImage src="/images/your-brutus-burguer/business-card-concept.png" alt="Mockup conceitual de cartão de visitas Your Brutus Burguer" width={1600} height={1000} className="aspect-[16/10] w-full object-cover" loading="lazy"/><figcaption className="p-5 text-sm text-[#c8b99e]">Cartão de visitas · conceito de presença e papelaria</figcaption></figure><figure className="overflow-hidden rounded-[2rem] border border-white/10 bg-[#171d25]"><PortfolioImage src="/images/your-brutus-burguer/flyer-concept.png" alt="Mockup conceitual de panfleto digital Your Brutus Burguer" width={1000} height={1250} className="aspect-[16/10] w-full object-cover object-center" loading="lazy"/><figcaption className="p-5 text-sm text-[#c8b99e]">Panfleto digital · conceito de presença e papelaria</figcaption></figure></div></section>
  <section className="border-t border-white/10 bg-[#171d25] px-5 py-16"><div className="mx-auto flex max-w-7xl flex-col gap-6 md:flex-row md:items-center md:justify-between"><div><h2 className="font-serif text-4xl font-black">Sua rota termina no cardápio.</h2><p className="mt-2 text-[#c8b99e]">Confira opções, disponibilidade e condições no canal oficial.</p></div><a href={menuUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#ed6a2c] px-7 font-black text-white transition-colors hover:bg-[#ff7a3d] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f5b84b]">Abrir cardápio oficial <ArrowUpRight className="h-4 w-4"/></a></div></section>
  </main></MotionScope><footer className="border-t border-white/10 px-5 py-10 text-sm text-[#c8b99e]"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><PortfolioImage src="/images/your-brutus-burguer/logo.svg" alt="Your Brutus Burguer" width={220} height={60} className="h-11 w-auto" loading="lazy"/><p className="mt-3">Hamburgueria artesanal · São José dos Pinhais — PR</p></div><PortfolioHostCredit linkClassName="font-semibold text-white underline underline-offset-4"/></div></footer><PortfolioUpsellPopup pageName="portfolio-your-brutus-burguer"/></div>;
}
