DO $$ DECLARE v_form_id uuid; BEGIN
 SELECT id INTO v_form_id FROM public.dynamic_forms WHERE slug='funnel-aguia-sul-sinalizacao';
 IF v_form_id IS NULL THEN INSERT INTO public.dynamic_forms (slug,name,description,status,config_json,whatsapp_config) VALUES ('funnel-aguia-sul-sinalizacao','Orçamento · Águia Sul Sinalização','Funil individual para pintura e sinalização horizontal','published','{"auto_advance_ms":250}'::jsonb,'{"enabled":true}'::jsonb) RETURNING id INTO v_form_id;
 ELSE UPDATE public.dynamic_forms SET status='published',name='Orçamento · Águia Sul Sinalização',description='Funil individual para pintura e sinalização horizontal' WHERE id=v_form_id; DELETE FROM public.dynamic_form_conditions WHERE form_id=v_form_id; DELETE FROM public.dynamic_form_questions WHERE form_id=v_form_id; END IF;
 INSERT INTO public.dynamic_form_questions (form_id,key,type,label,hint,placeholder,order_index,required,options_json) VALUES
 (v_form_id,'welcome','statement','Vamos planejar seu espaço 🚧','Conte o desafio e receba um orçamento personalizado.',NULL,0,false,'[]'::jsonb),
 (v_form_id,'nome','short_text','Qual é o seu nome?',NULL,'Seu nome',1,true,'[]'::jsonb),
 (v_form_id,'servico','radio','Qual serviço você precisa?',NULL,NULL,2,true,jsonb_build_array(jsonb_build_object('value','estacionamento','label','Pintura de estacionamento'),jsonb_build_object('value','vagas','label','Demarcação de vagas PCD e idosos'),jsonb_build_object('value','faixas','label','Faixas e setas'),jsonb_build_object('value','imobiliaria','label','Pintura imobiliária'),jsonb_build_object('value','industrial','label','Galpões e estruturas industriais'))),
 (v_form_id,'projeto','radio','Que tipo de espaço?',NULL,NULL,3,true,jsonb_build_array(jsonb_build_object('value','condominio','label','Condomínio'),jsonb_build_object('value','comercio','label','Comércio ou estacionamento'),jsonb_build_object('value','industria','label','Indústria ou galpão'),jsonb_build_object('value','empresa','label','Empresa ou imóvel'))),
 (v_form_id,'local','radio','Onde será o serviço?',NULL,NULL,4,true,jsonb_build_array(jsonb_build_object('value','curitiba','label','Curitiba e região'),jsonb_build_object('value','metropolitana','label','Região Metropolitana'),jsonb_build_object('value','confirmar','label','Vou confirmar o endereço'))),
 (v_form_id,'quando','radio','Quando deseja realizar?',NULL,NULL,5,true,jsonb_build_array(jsonb_build_object('value','breve','label','Preciso de orçamento em breve'),jsonb_build_object('value','planejando','label','Estou planejando'),jsonb_build_object('value','visita','label','Quero uma visita técnica'))),
 (v_form_id,'detalhes','long_text','Mais detalhes','Medidas, fotos e prazo ajudam na proposta.','Descreva o espaço',6,false,'[]'::jsonb),
 (v_form_id,'telefone','phone','Qual WhatsApp para retorno?',NULL,'(41) 99999-9999',7,true,'[]'::jsonb),
 (v_form_id,'confirmacao','statement','Solicitação recebida! ✅','A Águia Sul vai confirmar os próximos passos.',NULL,8,false,'[]'::jsonb); END $$;
